### ISSUE TITLE
Single Name Actress

### ISSUE THREAD

**Issue by fidofido300** [jvlflame/Javinizer#10]
With the Single name Actress like AIKA,Hitomi, etc.... the file name written in the .actor directory is aika_,jpg or Hitomi_.jpg. Can you look at this again please.
Thanks for this very robust Module

Windows 10
PowerShell 6.2.3
Module 1.1.6
## Your Environment

* Module version used:
* Operating System and PowerShell version:

**Comment by jvlflame** [comment]
Thanks for the report. I have implemented a fix for the upcoming release 7f8030e7750057be376d633a3365801871ba7856.

**Comment by fidofido300** [comment]
Thank you!

**Comment by fidofido300** [comment]
Umm Sorry but when I run the latest commit  I get :

WARNING: [Set-JavMovie] Error downloading actress images
Exception calling "EndInvoke" with "1" argument(s): "Index operation failed; the array index evaluated to null."

**Comment by jvlflame** [comment]
> Umm Sorry but when I run the latest commit I get :
> 
> WARNING: [Set-JavMovie] Error downloading actress images
> Exception calling "EndInvoke" with "1" argument(s): "Index operation failed; the array index evaluated to null."

Thanks, just re-checked the commit and noticed the issue. Will push another hotfix.

**Comment by fidofido300** [comment]
Thanks Working 👍
