### ISSUE TITLE
nfo file is not named the same as video file if "sort.renamefile": 0

### ISSUE THREAD

**Issue by org0ne** [jvlflame/Javinizer#102]
## Expected Behavior
NFO files are expected have the same name as the media they are describing.

## Current Behavior
This is a new issue, as previous versions would name the nfo file the same as the video file when asked to, regardless the name.

## Steps to Reproduce (for bugs)
- Name a video file with some extra text (I was using tikp-049 test.mp4)
- Scrape the file

## Your Environment
* Module version used:2.0.1
* Operating System and PowerShell version:Ubuntu 18.04, powershell 7.0.3

**Comment by org0ne** [comment]
Just tested this on 2.0.2 and see the same behaviour.

**Comment by jvlflame** [comment]
For clarification, `sort.create.nfoperfile` is the setting is forcing the nfo to be the same as the filename.
If that's set as false, then only a single nfo fill will be created per movie file, and it will follow the naming format of `sort.format.nfo`.

**Comment by org0ne** [comment]
Thanks for the clarification.  Confirmed here that `sort.create.nfoperfile` is set to true as well.
