### ISSUE TITLE
<ACTORS> data missing from "sort.metadata.nfo.displayname" if scraped actor name is in Japanese

### ISSUE THREAD

**Issue by org0ne** [jvlflame/Javinizer#103]
## Expected Behavior
jvThumbs.csv actor name should propagate to all fields

## Current Behavior
When scraping a title where the results are only in Japanese, the Folder name and <actor><name> and <altname> tags are correctly written, but the <ACTORS> filed inside of "sort.metadata.nfo.displayname" will be blank

## Steps to Reproduce (for bugs)
- use the attached jvSettings.json (mostly just to use my custom regex to capture the ID)
[jvSettings.txt](https://github.com/jvlflame/Javinizer/files/5261341/jvSettings.txt)

- scrape 010507_033.mp4
- review the outputted nfo file

## Your Environment
* Module version used: 2.0.1
* Operating System and PowerShell version: Ubuntu 18.04, powershell 7.0.3

**Comment by org0ne** [comment]
FYI - Just tested this on 2.0.2 and see the same behavior

**Comment by jvlflame** [comment]
I added logic to make it fallback to the non-selected actress language for all format names with `<ACTOR>` in it when the primary language name isn't available.
