### ISSUE TITLE
Feature request: allow users to write the "tagline" nfo file tag 

### ISSUE THREAD

**Issue by org0ne** [jvlflame/Javinizer#106]
I am currently using Jellyfin as my CMS, and have settled on using "Tagline" to display the movie ID.  Sadly tagline is not searchable in Jellyfin, but this tag still helps when the title is so long that users cannot see the movie ID if they chose to add to add the ID at the end of the movie title.

I am currently running a command line operation to add the tagline after I do a scrape, but it would be way less error prone to add this at nfo file creation time.

Example of tagline used in Jellyfin on a release with a long title:
[Screenshot_2020-09-22 Jellyfin](https://user-images.githubusercontent.com/70040652/93898454-d838bb00-fcb8-11ea-8b64-c1a490458919.jpg)

**Comment by jvlflame** [comment]
Added tagline feature as a setting in addition to changing the seriesastag setting:
- `sort.metadata.nfo.format.tagline`
-  `sort.metadata.nfo.seriesastag` => `sort.metadata.nfo.format.tag` 

Tagline specifies a format string i.e. for your use case `"sort.metadata.nfo.format.tagline": "<ID>"`
Tag specifies an array of format strings to create one or many tags i.e. `"sort.metadata.nfo.format.tag": ["<SET">", "<ORIGINALTITLE>"]`

**Comment by org0ne** [comment]
woohoo!  Thanks @jvlflame!
