### ISSUE TITLE
Feature Request: use Japanese name for actor role

### ISSUE THREAD

**Issue by org0ne** [jvlflame/Javinizer#110]
I have used this on most of my .nfo exports and realized that this is not something that Javinizer currently supports.

Using the Japanese name as role presents the Japanese characters in an easy to access location which helps immensely if a user wants to do some deeper searching on an actress.

**Comment by jvlflame** [comment]
Added setting `sort.metadata.nfo.altnamerole`  to add the actress `<altname>` as the actress role.

Also changed the `<altname>` field to be dynamic based on the selected actress language via `sort.metadata.nfo.actresslanguageja`.

If `sort.metadata.nfo.actresslanguageja: 1`, altname will be written as the English name.
If `sort.metadata.nfo.actresslanguageja: 0`, altname will be written as the Japanese name.
