### ISSUE TITLE
feature request: output into folder structure based on metadata

### ISSUE THREAD

**Issue by AreYouDeeWhy** [jvlflame/Javinizer#115]
I like how this project works so far, but it would be nice to output into specific folders based on the metadata of the videos. Unless this is already possible please let me know.

at the moment it appears it can only output everything into one single destination folder like:

-  E:\\javinizer\\output\\< ID> [< STUDIO>] - < TITLE> (< YEAR>).mp4

Personally i like to group my videos by studio so it would be nice to have that option to organize further, taking each scraped video and putting it into a folder of a specified metadata tag like:

-  E:\\javinizer\\output\\< STUDIO>\\< ID> - < TITLE> (< YEAR>).mp4

other possible uses:

year:
-  E:\\javinizer\\output\\< YEAR>\\< ID> [< STUDIO>] - < TITLE>.mp4

resolution:
-  E:\\javinizer\\output\\< RESOLUTION>\\< ID> [< STUDIO>] - < TITLE> (< YEAR>).mp4

**Comment by jvlflame** [comment]
Thanks for the request!
I've added a new setting: `sort.format.outputfolder` which accepts a format string.

An example case:

```json
// jvSettings.json
"sort.format.outputfolder": "[<STUDIO>] (<YEAR>)",
```

```powershell
PS C:\> Javinizer -Path C:\Javinizer\ -Verbose
VERBOSE: [ABP-420] [Set-JVMovie] Completed [C:\Javinizer\ABP-420.mp4] => [C:\Javinizer\[Prestige] (2016)\ABP-420 [Prestige] - Endless Sex Starring Rino Kirishima (2016)\ABP-420.mp4]
```

Leaving the `sort.format.outputfolder` setting blank will sort with the original behavior.
