### ISSUE TITLE
javinizer is not digitally signed so it won't run

### ISSUE THREAD

**Issue by Hakker** [jvlflame/Javinizer#12]
Javinizer.psm1 is not digitally signed. You cannot
run this script on the current system. For more information about running scripts and setting execution policy, see
about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170

This is on Windows 10 setting to remotesigned didn't help here either

I installed it using the Powershell Gallery

**Comment by jvlflame** [comment]
Open a PowerShell window as administrator and try running
```
Set-ExecutionPolicy Unrestricted
```

**Comment by Hakker** [comment]
This can be closed. By default Windows 10 still seem to use Powershell 5.1 I had mistakenly thought it would have been updated to 6.x by now.

When I updated and started using 6 I didn't get the message either.
