### ISSUE TITLE
does not match titles with format ABC-AA001

### ISSUE THREAD

**Issue by gedegede** [jvlflame/Javinizer#125]
## Expected Behavior
Match titles with format example ABC-AA001

## Current Behavior
Tries to match as ABC-AA-001

## Your Environment
* Module version used:
* Operating System and PowerShell version:

**Comment by jvlflame** [comment]
Can you give me an example of a movie that uses that format?

Javinizer will by default try to match the filenames to standard JAV formats.
If you want to bypass the default file matching, you can use the `-Strict` parameter, or use the regex match settings.

`Javinizer -Path 'C:\JAV\ABC-AA-001.mp4' -Strict`

**Comment by gedegede** [comment]
> Can you give me an example of a movie that uses that format?
> 
> Javinizer will by default try to match the filenames to standard JAV formats.
> If you want to bypass the default file matching, you can use the `-Strict` parameter, or use the regex match settings.
> 
> `Javinizer -Path 'C:\JAV\ABC-AA001.mp4' -Strict`

MBR-AA063

**Comment by jvlflame** [comment]
> > Can you give me an example of a movie that uses that format?
> > Javinizer will by default try to match the filenames to standard JAV formats.
> > If you want to bypass the default file matching, you can use the `-Strict` parameter, or use the regex match settings.
> > `Javinizer -Path 'C:\JAV\ABC-AA001.mp4' -Strict`
> 
> MBR-AA063

Interesting, thanks for that info. Haven't seen that before.
I'm probably not going to add logic to match that automatically due to how niche that case is, but `-Strict` should be able to handle it fine.

Though, I did notice that these fail on R18/Dmm URL scrapers due to the automatic contentid conversion, so I added `-Strict` to work there as well.
