### ISSUE TITLE
Feature Request: GUI that runs in Windows Environment

### ISSUE THREAD

**Issue by cavalia88** [jvlflame/Javinizer#129]
Would it be possible to create a GUI version that runs in the Windows Environment? Something similar to how JAVScrapper currently does it with Java.

JAVscrapper hasn't been updated in quite a while

**Comment by jvlflame** [comment]
Unfortunately I don't have any experience developing GUI or web-front ends, but I did play around with creating a simple web frontend that can be hosted via docker or on Windows.

I may try enhancing that functionality, but no guarantees it will be anywhere near as robust as javmoviescraper.
https://gfycat.com/courageousangryiguana

**Comment by cavalia88** [comment]
Thank you. The web frontend looks promising. Look forward to testing the web frontend on a Windows machine.

**Comment by DarkMask100** [comment]
@jvlflame I'm sure if you create a repo for it, people would contribute to it. :)

**Comment by jvlflame** [comment]
@DarkMask100 I'm actually developing it using [PowerShell Universal](https://ironmansoftware.com/powershell-universal/) which is probably the easiest way to get a quick GUI frontend for Javinizer.

I'm not sure I want to create a new repo for it yet, but I should have some more progress to show soon.

**Comment by jvlflame** [comment]
[I've put out an alpha release for the web GUI that I'm working on.](https://github.com/jvlflame/Javinizer/releases/tag/2.1.5-alpha1)
Feel free to test or offer any feedback!

**Comment by cavalia88** [comment]
I'm not really a tech person, so installing Docker and related stuff was really a challenge. Managed to have the Javinizer module installed and launched. However, as I did not know how to provide Docker access to my video files, was unable to test its functionality. 

Ideally, the Javinizer would be able to run natively in Windows, without having to install any Docker, enabling virtualization etc.

**Comment by jvlflame** [comment]
@cavalia88 Going to be updating documentation soon to include instructions on how to setup without Docker.

**Comment by jvlflame** [comment]
With 2.1.6, better documentation has been added for installation instructions for Windows (without Docker). 
Docs now live on GitBook [here](https://docs.jvlflame.net/installation/install-javinizer-web-gui).

Development for the GUI will continue alongside improvements to the Javinizer CLI. Let me know if you have any feedback or questions.
