### ISSUE TITLE
Rename poster/fanart 

### ISSUE THREAD

**Issue by Freakboo** [jvlflame/Javinizer#13]
a way to automatically rename the poster and fanart to <ID>-poster/fanart?
if not... add pls?

luv ya

**Comment by jvlflame** [comment]
Just to clarify,
You want to be able to set the poster image names to:

`<Video Title>-poster.jpg`
`<Video Title>-fanart.jpg`

Is that right?

**Comment by Freakboo** [comment]
I personally would prefer 

` <ID>-poster.jpg `
` <ID>-Fanart.jpg` 

But ill take whatever is easier for you. TY

**Comment by Freakboo** [comment]
Sorry for the confusion I didnt know how the insert code works ...

**Comment by jvlflame** [comment]
Feature has been added in [1.1.12](https://github.com/jvlflame/Javinizer/releases/tag/1.1.12).

Let me know if that works for you.

**Comment by Freakboo** [comment]
Tried it out, works great. Thanks!
