### ISSUE TITLE
Javinizer on network drives

### ISSUE THREAD

**Issue by Goldhawk1** [jvlflame/Javinizer#14]
Hi, first of all great job on this, it has already helped me alot, but there is one thing that I can't seem to get running properly. The problem is, that the "poster.jpg" is not created when I apply Javinizer to a network drive. 

I my case the drives are attached via SMB.
Javinizer only starts up using "//fileserver/videos/..." but not using "Z:/videos/..." as -Path.
Ther rest however, works flawlessly (except the missing "poster.jpg")

I have butchered the included crop.py to apply it manually afterwards, but this might still take quite a while with my limited skills. ^^'

As of right now, I'm assuming the "fanart.jpg" is pushed to my fileserver first and the cropping is done afterwards. Python might not appreciate the path it's given.
Maybe preparing the images locally might fix it.

If this is an easy fix, I would really appreciate it. 

The problem was encountered on Windows 10 using PS6.

**Comment by jvlflame** [comment]
Hi Goldhawk1,

I don't think I've ever run into that issue before. I sort all my videos from an SMB fileserver mounted on Windows 10 as well.

The symptoms you describe lead me to believe that the mapped network drives are unable to be found using PowerShell. One question I need to ask:

Are you using an **administrator** PowerShell window to run Javinizer? If so, try switching to a non-administrator prompt or [follow these instructions to map it as an administrator](https://stackoverflow.com/questions/4742992/cannot-access-network-drive-in-powershell-running-as-administrator)

If that doesn't fix your issue, please set `$DebugPreference = $true` in your PowerShell window, run Javinizer, and paste the output for me.

Thanks.

**Comment by Goldhawk1** [comment]
Hi, 
Thanks for the quick response.
I have indeed been running Powershell as admin the whole time.
It works now now and i kinda feel stupid. I makes sense now... better late then never, i guess. ^^'

Thank you soo much for your support. This tool is pure magic. :)
