### ISSUE TITLE
sort.metadata.nfo.format.tag field not splitting into multiple tags

### ISSUE THREAD

**Issue by thsu93** [jvlflame/Javinizer#141]
## Expected Behavior
Tags from the "sort.metadata.nfo.format.tag" field in JVSettings.json to be split into multiple tags within Emby.

## Current Behavior
"sort.metadata.nfo.format.tag" : ["<SET>", "<STUDIO>", "<LABEL>"], in JVSettings.json creates a singular long tag rather than 3 individual tags in Emby.  

## Steps to Reproduce (for bugs)
![image](https://user-images.githubusercontent.com/57927282/96649012-4abfa980-12fe-11eb-80ac-f821d6c89473.png)

## Your Environment
* Module version used: 2.1.4
* Operating System and PowerShell version: Windows 10, Powershell 7

**Comment by jvlflame** [comment]
Thanks for catching that bug! It'll be fixed in the next release.
