### ISSUE TITLE
Multi-actress lists print as "@Group" when "<ACTORS>" is requested

### ISSUE THREAD

**Issue by org0ne** [jvlflame/Javinizer#143]
## Expected Behavior
Names of actresses should be given as comma separated lists wherever the <ACTORS> tag is used (i.e. in NFO files or folder names)

## Current Behavior
<ACTORS> prints as @Grouop

## Steps to Reproduce (for bugs)
scrape a movie w/ multiple actresses, such as NHDTA-808

## Your Environment
* Module version used: 2.1.4
* Operating System and PowerShell version:7.0.3

**Comment by jvlflame** [comment]
I added an additional setting called `sort.format.groupactress` which groups multiple actresses into that `@Group` name. You can turn it off in the settings if you want the old behavior.

**Comment by org0ne** [comment]
Thanks for the clarification @jvlflame -- was not aware of the feature. Closing this out.
