### ISSUE TITLE
Plot translation does not seem to work

### ISSUE THREAD

**Issue by idontknownl** [jvlflame/Javinizer#154]
the plot is not translated despite installing the relevant package and the following configuration:

 "sort.metadata.nfo.translatedescription": 1,
 "sort.metadata.nfo.translatedescription.language": "en",

**Comment by jvlflame** [comment]
Install googletrans 4.0.0-rc1. The current 3.0.0 version is bugged.

```
pip install googletrans==4.0.0-rc1
```
