### ISSUE TITLE
BUG: write error

### ISSUE THREAD

**Issue by valiumx** [jvlflame/Javinizer#156]
## Expected Behavior

Search for movies
## Current Behavior
Write-Error: C:\Users\Ray\OneDrive\Documents\PowerShell\Modules\Javinizer\2.1.6\Public\Javinizer.ps1:821
Line |
 821 |  …             Write-JVLog -Write:$script:JVLogWrite -LogPath $script:JV …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [Javinizer] Error occurred when getting local movies in [G:\test\]: Cannot convert value "4)" to type
     | "System.Int32". Error: "Input string was not in a correct format."

## Steps to Reproduce (for bugs)
Javinizer -Path 'G:\test\'

## Your Environment
* Module version used: 2.16
* Operating System and PowerShell version: win 10 Powershell 7.0.3

**Comment by jvlflame** [comment]
Can you post your settings file? I think there's an incorrect setting somewhere.

`Javinizer -OpenSettings`

**Comment by valiumx** [comment]
Get-ChildItem: C:\Users\Ray\OneDrive\Documents\PowerShell\Modules\Javinizer\2.1.6\Public\Get-JVItem.ps1:72
Line |
  72 |  …    $files = Get-ChildItem -LiteralPath $Path -Recurse:$Recurse | Wher …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Users\Ray\G\test' because it does not exist.

**Comment by valiumx** [comment]
{
    "throttlelimit": 3,
    "location.input": "",
    "location.output": "",
    "location.thumbcsv": "",
    "location.genrecsv": "",
    "location.uncensorcsv": "",
    "location.historycsv": "",
    "location.log": "",
    "scraper.movie.dmm": 0,
    "scraper.movie.dmmja": 1,
    "scraper.movie.jav321ja": 0,
    "scraper.movie.javbus": 0,
    "scraper.movie.javbusja": 0,
    "scraper.movie.javbuszh": 0,
    "scraper.movie.javlibrary": 1,
    "scraper.movie.javlibraryja": 0,
    "scraper.movie.javlibraryzh": 0,
    "scraper.movie.r18": 1,
    "scraper.movie.r18zh": 0,
    "scraper.option.dmm.scrapeactress": 0,
    "scraper.option.idpreference": "id",
    "match.minimumfilesize": 0,
    "match.includedfileextension": [
        ".asf",
        ".avi",
        ".flv",
        ".m4v",
        ".mkv",
        ".mp4",
        ".mov",
        ".rmvb",
        ".wmv"
    ],
    "match.excludedfilestring": ["^.*-trailer*", "^.*-5\\."],
    "match.regex": 0,
    "match.regex.string": "([a-zA-Z|tT28]+-\\d+[zZ]?[eE]?)(?:-pt)?(\\d{1,2})?",
    "match.regex.idmatch": 1,
    "match.regex.ptmatch": 2,
    "sort.movetofolder": 1,
    "sort.renamefile": 1,
    "sort.maxtitlelength": 100,
    "sort.create.nfo": 1,
    "sort.create.nfoperfile": 1,
    "sort.download.actressimg": 0,
    "sort.download.thumbimg": 1,
    "sort.download.posterimg": 1,
    "sort.download.screenshotimg": 0,
    "sort.download.trailervid": 0,
    "sort.format.groupactress": 1,
    "sort.format.delimiter": ", ",
    "sort.format.file": "<ID>",
    "sort.format.folder": "<ID> [<STUDIO>] - <TITLE> (<YEAR>)",
    "sort.format.outputfolder": [],
    "sort.format.posterimg": ["folder"],
    "sort.format.thumbimg": "fanart",
    "sort.format.trailervid": "<ID>-trailer",
    "sort.format.nfo": "<ID>",
    "sort.format.screenshotimg": "fanart",
    "sort.format.screenshotfolder": "extrafanart",
    "sort.format.actressimgfolder": ".actors",
    "sort.metadata.nfo.mediainfo": 0,
    "sort.metadata.nfo.altnamerole": 0,
    "sort.metadata.nfo.translatedescription": 0,
    "sort.metadata.nfo.translatedescription.language": "en",
    "sort.metadata.nfo.displayname": "[<ID>] <TITLE>",
    "sort.metadata.nfo.firstnameorder": 0,
    "sort.metadata.nfo.actresslanguageja": 0,
    "sort.metadata.nfo.unknownactress": 1,
    "sort.metadata.nfo.originalpath": 0,
    "sort.metadata.nfo.format.tag": ["<SET>"],
    "sort.metadata.nfo.format.tagline": "",
    "sort.metadata.thumbcsv": 1,
    "sort.metadata.thumbcsv.autoadd": 1,
    "sort.metadata.thumbcsv.convertalias": 1,
    "sort.metadata.genrecsv": 0,
    "sort.metadata.genre.ignore": ["^Featured Actress", "^Hi-Def", ".*sale.*"],
    "sort.metadata.requiredfield": ["id", "coverurl", "genre", "maker", "releaseDate", "title"],
    "sort.metadata.priority.actress": ["r18", "javlibrary", "javbus"],
    "sort.metadata.priority.alternatetitle": ["dmmja"],
    "sort.metadata.priority.coverurl": ["r18", "dmmja", "javlibrary", "javbus"],
    "sort.metadata.priority.description": ["dmmja", "dmm"],
    "sort.metadata.priority.director": ["r18", "javlibrary"],
    "sort.metadata.priority.genre": ["r18", "javlibrary", "javbus"],
    "sort.metadata.priority.id": ["r18", "javlibrary", "javbus"],
    "sort.metadata.priority.contentid": ["r18", "dmmja"],
    "sort.metadata.priority.label": ["r18", "javlibrary"],
    "sort.metadata.priority.maker": ["r18", "javlibrary", "javbus"],
    "sort.metadata.priority.releasedate": ["r18", "javlibrary", "dmmja", "javbus"],
    "sort.metadata.priority.rating": ["dmmja"],
    "sort.metadata.priority.runtime": ["r18", "javlibrary", "dmmja", "javbus"],
    "sort.metadata.priority.series": ["r18", "r18zh"],
    "sort.metadata.priority.screenshoturl": ["r18", "javlibrary", "dmmja", "javbus"],
    "sort.metadata.priority.title": ["r18", "javlibrary", "javbus"],
    "sort.metadata.priority.trailerurl": ["r18", "dmmja"],
    "emby.url": "http:\/\/192.168.0.1:8096",
    "emby.apikey": "",
    "javlibrary.baseurl": "http:\/\/www.javlibrary.com",
    "javlibrary.browser.useragent": "",
    "javlibrary.cookie.cfduid": "",
    "javlibrary.cookie.cfclearance": "",
    "javlibrary.cookie.session": "",
    "javlibrary.cookie.userid": "",
    "web.sort.recurse": 1,
    "web.sort.strict": 0,
    "web.sort.interactive": 1,
    "web.sort.update": 0,
    "web.sort.force": 0,
    "web.sort.confirm": 0,
    "web.sort.manualsearch.dmm": false,
    "web.sort.manualsearch.dmmja": false,
    "web.sort.manualsearch.jav321ja": false,
    "web.sort.manualsearch.javbus": false,
    "web.sort.manualsearch.javbusja": false,
    "web.sort.manualsearch.javbuszh": false,
    "web.sort.manualsearch.javlibrary": false,
    "web.sort.manualsearch.javlibraryja": false,
    "web.sort.manualsearch.javlibraryzh": false,
    "web.sort.manualsearch.r18": false,
    "web.sort.manualsearch.r18zh": false,
    "web.navigation.pagesize": 5,
    "admin.log": 1,
    "admin.log.level": "info"
}

**Comment by jvlflame** [comment]
> Get-ChildItem: C:\Users\Ray\OneDrive\Documents\PowerShell\Modules\Javinizer\2.1.6\Public\Get-JVItem.ps1:72
> Line |
> 72 | … $files = Get-ChildItem -LiteralPath $Path -Recurse:$Recurse | Wher …
> | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> | Cannot find path 'C:\Users\Ray\G\test' because it does not exist.

Sorry, had a typo in my previous post.
Can you use `$Path = 'G:\test'`

```
$Path = 'G:\test'
$Settings = Get-Content 'C:\Users\Ray\OneDrive\Documents\PowerShell\Modules\Javinizer\2.1.6\jvSettings.json' | ConvertFrom-Json
$javMovies = $Settings | Get-JVItem -Path $Path -MinimumFileSize $Settings.'match.minimumfilesize' -RegexEnabled:$Settings.'match.regex' -RegexString $Settings.'match.regex.string' -RegexIdMatch $Settings.'match.regex.idmatch' -RegexPtMatch $Settings.'match.regex.ptmatch' -Recurse:$Recurse -Depth:$Depth -Strict:$Strict
```

**Comment by valiumx** [comment]
$javMovies = $Settings | Get-JVItem -Path $Path -MinimumFileSize $Settings.'match.minimumfilesize' -RegexEnabled:$Settings.'match.regex' -RegexString $Settings.'match.regex.string' -RegexIdMatch $Settings.'match.regex.idmatch' -RegexPtMatch $Settings.'match.regex.ptmatch' -Recurse:$Recurse -Depth:$Depth -Strict:$Strict
InvalidArgument: C:\Users\Ray\OneDrive\Documents\PowerShell\Modules\Javinizer\2.1.6\Private\Convert-JVTitle.ps1:203
Line |
 203 |                  $filePartNumber = [int]$filePartNum
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot convert value "4)" to type "System.Int32". Error: "Input string was not in a correct format."

InvalidArgument: C:\Users\Ray\OneDrive\Documents\PowerShell\Modules\Javinizer\2.1.6\Private\Convert-JVTitle.ps1:203
Line |
 203 |                  $filePartNumber = [int]$filePartNum
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot convert value "6M" to type "System.Int32". Error: "Input string was not in a correct format."

InvalidArgument: C:\Users\Ray\OneDrive\Documents\PowerShell\Modules\Javinizer\2.1.6\Private\Convert-JVTitle.ps1:203
Line |
 203 |                  $filePartNumber = [int]$filePartNum
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot convert value "6M" to type "System.Int32". Error: "Input string was not in a correct format."

**Comment by jvlflame** [comment]
There's a filename that's breaking the file matcher. Can I ask what the filenames are in your `G:\Test` directory?

If you test on an already-named file you can probably get it to work.
`Javinizer -Path G:\Test\ABP-420.mp4`

**Comment by valiumx** [comment]
Yes that seems to be the issue, I went through the file names and i found the offending file name from the error printouts. 

FHD-cawd-148_6M

Should have done some clean up first. sorry for the hassle.

**Comment by jvlflame** [comment]
No problem, thanks for letting me know which file was breaking it!
Normally a file should just be skipped if it's unable to be matched, so I'll have to fix that.
