### ISSUE TITLE
Folder Name ending with . would be created successfully without . at the end while reporting success without catching exception - leading to following reference to that folder failed

### ISSUE THREAD

**Issue by amdishigh** [jvlflame/Javinizer#168]
## Expected Behavior
When movetofolder is enabled, and one of folder name to be created is with "." at end, the folder should be created without "." at end intendenly 

## Current Behavior
The folder would be created without "." at end un-inendenly, i.e. OS create it without "." for us without error, thus script believe it's created successfully - while actually it's not. Thus, following code while creating files within that folder, that would be failed 

## Your Environment
* Module version used: 2.2.2 
* Operating System and PowerShell version: Windows / PowerShell 7.1 

##Solution
One quick workaround is to trim "." at the end before we create it, below is what I added to fix it - but sure if any other code need such fix or any better solution. 

In Set-JVMovie.ps1, before if ($Force -or $PSCmdlet.ShouldProcess($Path)) {

Add:        $folderPath = $folderPath.TrimEnd(".")

**Comment by jvlflame** [comment]
Good idea, I'll implement it in that way. I was thinking about it for a while the other day but wasn't sure how to go about it. #163
