### ISSUE TITLE
Javlibrary Actress Names 

### ISSUE THREAD

**Issue by fidofido300** [jvlflame/Javinizer#17]
With Movies That has Acress listed in JAVLIBRARY but not in R18 (eg. RCT-352)
The info file looks like 
    <actor>
        <name>Azumi MizushimaManami TakaokaChieri MinamiYukana Miyano</name>
        <thumb></thumb>
        <role>Actress</role>
    </actor>
The genre fields has the same problem as well same problem 
## Your Environment

* Module version used: 1.1.14
* Operating System and PowerShell version: 6.2.3
Regards

**Comment by jvlflame** [comment]
Thanks, I was able to reproduce it on my side as well.

The bug was introduced at the same time as the genres and I did not test it properly. Hotfix release will be pushed shortly.

**Comment by jvlflame** [comment]
[Hotfix release 1.1.15](https://github.com/jvlflame/Javinizer/releases/tag/1.1.15) resolves this bug.

**Comment by fidofido300** [comment]
Thank you!!
