### ISSUE TITLE
Please add autoadd function for genre

### ISSUE THREAD

**Issue by jraphael11** [jvlflame/Javinizer#181]
I convert all genre via genrecsv. I use this function as translator.
So, I want to know which genre item is not converted in my library.
If you add autoadd function for genre like thumbcsv, I think I can that work easily.

**Comment by jvlflame** [comment]
Great suggestion! Surprisingly, I have never thought to utilize the genre csv for this purpose but it actually makes perfect sense.
I'll add this to my backlog for the next release.

**Comment by jvlflame** [comment]
Added boolean setting `sort.metadata.genrecsv.autoadd` to add new genres to the genre csv automatically (does not rely on `sort.metadata.genrecsv`).

If `sort.metadata.genrecsv` is `true`, functionality has been updated to not perform a replacement if the `Replacement` csv field is null or empty.
