### ISSUE TITLE
Possible to call Javinizer from Dos Batch?

### ISSUE THREAD

**Issue by cavalia88** [jvlflame/Javinizer#188]
Hi,

I'm using the latest version of Javinizer CLI (version 2.2.10)

My Javinizer Powershell command is simply: Javinizer -Path 'D:\Input' -DestinationPath 'D:\Output'

Just wondering how I can call Javinizer from within a DOS (*.bat) file? Is it necessary to create a Powershell Script (*.ps1) file so that the DOS *.bat file can call it?

I have saved my Javinizer Powershell command (see above) as a powershell script and tried calling it from DOS-batch as follows:

Powershell.exe -executionpolicy Unrestricted -Command "& 'D:\javinzer.ps1'"

Doesn't seem to work. Wondering if you have any idea how it should be done?

## Your Environment
* Module version used: 2.2.10
* Operating System and PowerShell version: Windows 10 x64, PowerShell 7

**Comment by jvlflame** [comment]
You should be able to. I think I see the issue, you're calling `powershell.exe` which is Windows PowerShell.

You need to use `pwsh.exe` for PowerShell 7.

```
pwsh.exe -executionpolicy Unrestricted -Command "& 'D:\javinzer.ps1'"
```

**Comment by cavalia88** [comment]
Thanks for the prompt reply. It works. Didn't realize there was a difference between PowerShell 7 and Windows PowerShell.

Really saved me a lot of time trying to figure out on my own. Many thanks
