### ISSUE TITLE
Can actress name use origin Japanese name rather than Romanization of Japanese?

### ISSUE THREAD

**Issue by wangkezun** [jvlflame/Javinizer#19]
For instance  Ria Kashii -> 香椎りあ

**Comment by jvlflame** [comment]
I'll look into this.

Normally I'd just tell you to set `actress-priority=dmm` but for some reason even that's not working from my testing.

**Comment by jvlflame** [comment]
Feature has been added in #20 

Example usage:

```
# Setting values:

scrape-r18zh=True
scrape-javlibraryja=True

actress-priority=dmm,javlibraryja,r18zh
```

Let me know if you run into any issues with this.

**Comment by wangkezun** [comment]
I will try it out. Thanks for your support

**Comment by wangkezun** [comment]
Name seems fine to me. but the thumbs can't show correctly.Maybe the r18-thumbs.csv is not use Japanese name?

**Comment by jvlflame** [comment]
> Name seems fine to me. but the thumbs can't show correctly.Maybe the r18-thumbs.csv is not use Japanese name?

Can you give me an example of which movie you are experiencing the issue with? Also what platform are you using for viewing (plex, emby, etc)?

**Comment by wangkezun** [comment]
香椎りあ   
emby

**Comment by jvlflame** [comment]
The csv should work to import actresses with Japanese names into emby.

Use `Javinizer -SetEmbyActorThumbs` after you fill out your server information in the settings:
`server-url=`
`server-api-key=`

![image](https://user-images.githubusercontent.com/17932235/77874585-313ffe80-7202-11ea-96d7-7a5fe9f8d815.png)

**Comment by wangkezun** [comment]
Looks normal now. Thanks for your help.
