### ISSUE TITLE
Please add tagcsv

### ISSUE THREAD

**Issue by jraphael11** [jvlflame/Javinizer#193]
## Expected Behavior
Please add tag/set csv like Thunbcsv.
Autoadd is also required.
I want to organize tag same with thumb, genres.

## Current Behavior
No function

## Your Environment
* Module version used: 2.2.10
* Operating System and PowerShell version: 7.0.3

**Comment by jvlflame** [comment]
Can you elaborate on what csv fields you would be using as well as what it would do?

For example, `Tag` and `Replacement` or what purpose would you be using the tag csv for? I just want to make sure I have a better understanding of what you're asking for.

**Comment by jraphael11** [comment]
> Can you elaborate on what csv fields you would be using as well as what it would do?
> 
> For example, `Tag` and `Replacement` or what purpose would you be using the tag csv for? I just want to make sure I have a better understanding of what you're asking for.

I think 'Original', 'Replacement' is enough to my purpose. If I want to combine some tag, I can control it via entering same value in Replacement section for each original items.
My main purpose is translation from japanese to korean.
To find new Tag/Set item which is not converted, autoadd is required to me.

**Comment by jvlflame** [comment]
Thanks for that information.

I can probably add this to my backlog for the next release.
