### ISSUE TITLE
Please add function for adding actors to tag

### ISSUE THREAD

**Issue by jraphael11** [jvlflame/Javinizer#194]
## Expected Behavior
Please create new function for adding actors in movie to tag/set automatically.
I know I can search actor in PLEX or other system, but I want to make collection for each actor.
So, if Thumbscsv is set, I want to add actor to tag/set via Thumbcsv settings. (e.g., Alias is applied)

I think this request can be conflicted with my previous request #193.
In this case, I think #194 is applied first and then #193 function need to be applied.

## Current Behavior
No function.

## Your Environment
* Module version used: 2.2.10
* Operating System and PowerShell version: 7.0.3

**Comment by jvlflame** [comment]
Added setting `"sort.metadata.nfo.actressastag": true` to create `<tag>` elements for each actress.
This setting corresponds to other settings:
- `sort.metadata.nfo.actresslanguageja` -> determines the actress language
- `sort.metadata.nfo.firstnameorder` -> determines if using firstname lastname or lastname firstname if using english names

Example sort with setting enabled:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<movie>
    <title>[KNAM-020] #A Gal Bitch Threesome #Love Hotel Creampie Pay-For-Play Sex #A Cock-Loving Little Devil JK #Yui-tan, A Grinding Flesh Fantasy Gal Bitch x Shizuku-tan, A Bashful Black Hair Bitch</title>
    <originaltitle>＃ギャルビッチ3P ＃ラブホ中出し円光 ＃小悪魔チン好きJ● ＃グイグイ肉食ギャルビッチのゆいたん×恥ずかしがり屋の黒髪ビッチしずくたん</originaltitle>
    <id>KNAM-020</id>
    <premiered>2020-07-27</premiered>
    <year>2020</year>
    <director></director>
    <studio>First Star</studio>
    <rating>9</rating>
    <votes>9</votes>
    <plot>とんでもないビッチJ●を二人同時に生ハメするSPSPSPな円光動画。まだ発達しかけのふんわり唇でWフェラ！二つのお膣を出したり抜いたりズッポシ入れ替え！ギャルビッチのゆいたんは「私といっぱいやろ」とグイグイ。でも恥かしがり屋のしずくたんを苛めちゃう。最後は半中半外で完全中出し証明。おじさんキンタマからっぽになっちゃったおwww</plot>
    <runtime>139</runtime>
    <trailer>https://awscc3001.r18.com/litevideo/freepv/h/h_4/h_491knam020/h_491knam020_dmb_w.mp4</trailer>
    <mpaa>XXX</mpaa>
    <tagline></tagline>
    <set></set>
    <tag>Asahi Shizuku</tag>
    <tag>Satonaka Yui</tag>
    <genre>Schoolgirl</genre>
    <genre>Gym Clothes</genre>
    <genre>School Swimsuits</genre>
    <genre>Picking Up Girls</genre>
    <genre>Creampie</genre>
    <actor>
        <name>Asahi Shizuku</name>
        <altname>朝日しずく</altname>
        <thumb>https://pics.r18.com/mono/actjpgs/asahi_sizuku.jpg</thumb>
        <role>Actress</role>
    </actor>
    <actor>
        <name>Satonaka Yui</name>
        <altname>里中結衣</altname>
        <thumb>https://pics.r18.com/mono/actjpgs/satonaka_yui.jpg</thumb>
        <role>Actress</role>
    </actor>
</movie>
```
