### ISSUE TITLE
Update default file matcher behavior to be more flexible

### ISSUE THREAD

**Issue by raenoll** [jvlflame/Javinizer#196]
## Expected Behavior
Scrape Tokyo Hot correctly.

## Current Behavior
Javinizer will recognize ID n0100 to N-0100.

## Steps to Reproduce (for bugs)
1. Enable javbusja to true.
2. Name a video with n0100.avi
3. WARNING: [N-0100] [Get-JavbusUrl] not matched on JavBus
4. "javinizer -find n0100 -javbusja" works.

## Your Environment
* Module version used: 2.2.11
* Operating System and PowerShell version: debian 10 / PowerShell 7.1.1

**Comment by raenoll** [comment]
It can be qucikly fixed with -Strict. But need to clean manually before the command.

**Comment by jvlflame** [comment]
I've been meaning to update the file matcher to do some simple regex to detect if the file is a standard DVD ID or not. This would result hopefully result in less of a reliance on using the -Strict parameter for uncensored JAV sources.

Thanks for bringing this up though, I can add to the next release.

**Comment by jvlflame** [comment]
n0100 might be a special case where I wouldn't really be able to change the default functionality. The cleaned filename of N-0100 is a valid DVD Id format (for example there are DVDs named D-1005, etc.) so if I were to change the file matcher logic for that it would break functionality elsewhere.

I have added a regex check for other cases that might not match DVD Id formats though to decrease the reliance of `-Strict`.
