### ISSUE TITLE
Import-Module fail on certain Scraper .ps1 files

### ISSUE THREAD

**Issue by idontknownl** [jvlflame/Javinizer#212]
## Expected Behavior
My Javinizer suddenly stopped working so I tried to reinstall it but, I fail at the latest step when running Import-Module.
The error seems due to some of the ps1 that contains the scraper.

## Current Behavior
Import-Module : Unable to dot source [C:\Javinizer\Private\Scraper.DLgetchu.ps1]
At line:1 char:1
+ Import-Module C:\Javinizer\Javinizer.psm1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to dot s...r.DLgetchu.ps1]:String) [Import-Module], RuntimeExc
   eption
    + FullyQualifiedErrorId : Unable to dot source [C:\Javinizer\Private\Scraper.DLgetchu.ps1],Microsoft.PowerShell.Co
   mmands.ImportModuleCommand

(This is just an example, also Scraper.Jav321.ps1
## Steps to Reproduce (for bugs)
follow the guide as described on https://docs.jvlflame.net/installation/install-javinizer-cli to install the CLI version OF Javinizer.

## Your Environment
* Module version used: Latest Javinizer
* Operating System and PowerShell version: 7
Windows 10,

**Comment by jvlflame** [comment]
Can you just install the module via `Install-Module Javinizer`? That should get you the latest version without needing to import it. If it's already installed, use `Update-Module Javinizer`.

**Comment by idontknownl** [comment]
Hey,
I have tried that but this is the following message when I try to check if it is installed correctly:
Javinizer : The 'Javinizer' command was found in the module 'Javinizer', but the module could not be loaded. For more
information, run 'Import-Module Javinizer'.
At line:1 char:1
+ Javinizer -v
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Javinizer:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

**Comment by jvlflame** [comment]
Are you sure you're running it in a powershell 7 window (pwsh.exe)? It errors out in the way you're describing it if you try to run in Windows Powershell.

**Comment by idontknownl** [comment]
Thank you,
indeed, my bad, that was the issues.
You can close both the the Bug.
maybe add a warning in the explanation of the installation that pwsh.exe is the correct, and not "windows PowerShell 7" (for noob like me)
