### ISSUE TITLE
DMM scraper ID mismatch when using -Strict

### ISSUE THREAD

**Issue by raenoll** [jvlflame/Javinizer#214]
## Expected Behavior
Match correctly.

## Current Behavior
Mismatch with -strict

## Steps to Reproduce (for bugs)
1. Name a video with SM3D2DBD-17.avi
2. Javinizer -strict
3. It will be mismatched to SM-003 in dmmja, correct in aventertainment, javbus and javdb, skipped in r18.
"javinizer -find SM3D2DBD-17 -strict -aventertainment -javbus -javdb -dmmja -r18"

## Your Environment
* Module version used: 2.3.1
* Operating System and PowerShell version: debian 10 / PowerShell 7.1.1

**Comment by jvlflame** [comment]
Thanks for bringing this up. Did some optimizations on scrapers in the last release and forgot to address that.
