### ISSUE TITLE
Write Error Javinizer.ps1:927

### ISSUE THREAD

**Issue by Rgoodermote** [jvlflame/Javinizer#215]
## Expected Behavior
Sorts, downloads, and all of that fun stuff

## Current Behavior
Crash with poor explanation

Write-Error: C:\Program Files\PowerShell\Modules\Javinizer\2.3.1\Public\Javinizer.ps1:927
Line |
 927 |  …             Write-JVLog -Write:$script:JVLogWrite -LogPath $script:JV …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [Javinizer] Error occurred when getting local movies in [D:\JAV\Unsorted]: Cannot convert the
     | "System.Object[]" value of type "System.Object[]" to type "System.Char".

## Steps to Reproduce (for bugs)
Run Javinizer -Path "D:\JAV\Unsorted" -DestinationPath "D:\JAV\Sorted" -Recurse or just Javinizer in folder you want sorted

## Your Environment
* Module version used: 2.3.1
* Operating System and PowerShell version: Windows 10 (up to date) and Powershell 7.1.1

**Comment by jvlflame** [comment]
That happens when the filematcher breaks due to a filename it can't parse correctly. Test with smaller batches of files.

**Comment by Rgoodermote** [comment]
Yup, that was it. Honestly not the cause I was expecting.

**Comment by Rgoodermote** [comment]
I forgot to say why I was getting this, for those in the future who may run into this. I found that a multipart DVD was causing the issue. I changed the naming scheme to be [ID]-pt[increment]. So basically, OFJE-291CD1A became OFJE-291-pt1 and so on. This fixed this issue pretty quick. Only found out which one it was by doing smaller batches, as suggested.

**Comment by jvlflame** [comment]
Yup, I thought I had fixed this issue but edge case file naming keeps creeping up on me. I'll see if I can add a better error handling on that.
