### ISSUE TITLE
Javinizer cannot access path

### ISSUE THREAD

**Issue by mylifeishel** [jvlflame/Javinizer#216]
Hi, here's the problem
Javinizer won't access path even the path exist.
![1PNG](https://user-images.githubusercontent.com/20217680/107505824-39b1e580-6bd8-11eb-988a-0197ee994bba.PNG)
Restart computer doesn't help

## Log
[2021-02-10T19:44:51][ERROR] [Javinizer] Path [.\KAWD-949 `[HD`]\] is not a valid path

## Your Environment
* Module version used: 2.3.1
* Operating System and PowerShell version:
WIndows 10 
Powershell 7.0.4

**Comment by mylifeishel** [comment]
![2](https://user-images.githubusercontent.com/20217680/107511040-e6439580-6bdf-11eb-870d-173cb75afd34.PNG)

And i tried to input the parent directory of that directory results in the error:
Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Int32".

#log
[Javinizer] Error occurred when getting local movies in [D:\JD2\]: Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Int32".

**Comment by jvlflame** [comment]
Try with smaller batches of files. You have a file with a naming convention that's breaking the filematcher.
I already have a fix in place that addresses it in the upcoming release #215. 

---

> 
> 
> Hi, here's the problem
> Javinizer won't access path even the path exist.
> ![1PNG](https://user-images.githubusercontent.com/20217680/107505824-39b1e580-6bd8-11eb-988a-0197ee994bba.PNG)

For the first screenshot, it's because you need to reference the path without the ticks escaping the brackets. There's some weird interactions with brackets in PowerShell paths.

**Comment by mylifeishel** [comment]
> 
> 
> Try with smaller batches of files. You have a file with a naming convention that's breaking the filematcher.
> I already have a fix in place that addresses it in the upcoming release #215.
> 
> > Hi, here's the problem
> > Javinizer won't access path even the path exist.
> > ![1PNG](https://user-images.githubusercontent.com/20217680/107505824-39b1e580-6bd8-11eb-988a-0197ee994bba.PNG)
> 
> For the first screenshot, it's because you need to reference the path without the ticks escaping the brackets. There's some weird interactions with brackets in PowerShell paths.

Thanks! Solved.

Also, I found that for MIDE-845, the actress name is not scraped correctly: the actress name is ---- as a result the folder structure is incorrect.
But it actually found the actress name according the log

I used default config, could that be the reason?

**Comment by jvlflame** [comment]
> Also, I found that for MIDE-845, the actress name is not scraped correctly: the actress name is ---- as a result the folder structure is incorrect.
> But it actually found the actress name according the log
> 
> I used default config, could that be the reason?

Oh seems like there was an issue with Ono Rikka in the actress csv. It's being used for actress name replacements to keep metadata consistent between scrapers and it seems like there was an error for her entry.

You'll have to make a change in the csv via `Javinizer -OpenThumbs` with the change I'm pushing.

**Comment by mylifeishel** [comment]
Fixed. Thanks
