### ISSUE TITLE
Missing releasedate tag in nfo.

### ISSUE THREAD

**Issue by zuko7177** [jvlflame/Javinizer#225]
I have not run Javinizer in a while... I just updated to latest and see it's no longer creating <releasedate> tag in the NFO file.
However, I do see <premiered> tag.
Was this intentional change? Reason?
And is it configurable?
Thanks for all your work.

**Comment by jvlflame** [comment]
It was changed to `premiered` to conformat with the latest Kodi standards.

**Comment by zuko7177** [comment]
Ah ok. I wasn't aware Kodi changed their standards.
