### ISSUE TITLE
Video IDs are being modified slightly making them unfindable in different sites

### ISSUE THREAD

**Issue by Aaeeschylus** [jvlflame/Javinizer#227]
## Expected Behavior
If I have a video called JMSZ-83.mp4, when I run the sorter, I expect it to search sites for JMSZ-83.
If I have a video called DMM-070807.mp4, when I run the sorter, I expect it to search sites for DMM-070807.

## Current Behavior
Using the above two examples, it searches for JMSZ-083 and DMM-70807, making both videos unfindable in different sites.

## Steps to Reproduce (for bugs)
Have files with trailing 0 in the ID (DMM-070807) or only 2 numbers in the ID (JMSZ-83)

## Your Environment
* Module version used:  2.3.3
* Operating System and PowerShell version: Win10 20H2, Powershell 7.1.2

**Comment by TheWhiteDoll** [comment]
You need to use -Strict if you don't want Javinizer to try to clean the file ID.

Check the documentation here: https://docs.jvlflame.net/using-javinizer/general-usage/sorting-files#using-strict
And file matching page for more info: https://docs.jvlflame.net/using-javinizer/file-matching

**Comment by Aaeeschylus** [comment]
> You need to use -Strict if you don't want Javinizer to try to clean the file ID.
> 
> Check the documentation here: https://docs.jvlflame.net/using-javinizer/general-usage/sorting-files#using-strict
> And file matching page for more info: https://docs.jvlflame.net/using-javinizer/file-matching

I read that -Strict doesn't work with multi part videos. In the case that I have a situation like above and it is also multipart, is there any other solution? Or will I just have to sort with Javinizer on the first part and then manually put the other parts in the resulting folder?

**Comment by TheWhiteDoll** [comment]
Personally, I would sort based on the first part of the video and then copy the rest of the parts over manually. Then adjust the file names, duplicate the nfo if necessary, etc.

I don't believe there is a better solution at this point.

I've only had to do this a couple times, with older titles or titles with weird ID naming.

**Comment by jvlflame** [comment]
Isn't the expected behavior already the case in 2.3.3. Can you show me your output with `-Preview`?

Test:
```
Javinizer -Path C:\Javinizer -Preview
```

Output:
```
Id         : DMM-070807
ContentId  : DMM070807
FileName   : DMM-070807.mp4
BaseName   : DMM-070807
Directory  : C:\Javinizer
FullName   : C:\Javinizer\DMM-070807.mp4
Extension  : .mp4
Length     : 0
PartNumber :

Id         : JMSZ-83
ContentId  : JMSZ00083
FileName   : JMSZ-83.mp4
BaseName   : JMSZ-83
Directory  : C:\Javinizer
FullName   : C:\Javinizer\JMSZ-83.mp4
Extension  : .mp4
Length     : 0
PartNumber :
```

The `Id` from the filematcher preview output is what is being used by the scrapers.

**Comment by Aaeeschylus** [comment]
> Isn't the expected behavior already the case in 2.3.3. Can you show me your output with `-Preview`?
> 
> Test:
> 
> ```
> Javinizer -Path C:\Javinizer -Preview
> ```
> 
> Output:
> 
> ```
> Id         : DMM-070807
> ContentId  : DMM070807
> FileName   : DMM-070807.mp4
> BaseName   : DMM-070807
> Directory  : C:\Javinizer
> FullName   : C:\Javinizer\DMM-070807.mp4
> Extension  : .mp4
> Length     : 0
> PartNumber :
> 
> Id         : JMSZ-83
> ContentId  : JMSZ00083
> FileName   : JMSZ-83.mp4
> BaseName   : JMSZ-83
> Directory  : C:\Javinizer
> FullName   : C:\Javinizer\JMSZ-83.mp4
> Extension  : .mp4
> Length     : 0
> PartNumber :
> ```
> 
> The `Id` from the filematcher preview output is what is being used by the scrapers.

Apologies, I did not realise all the cases I had which were the same were multi-part cases. Here is my output:

```
Id         : DMM-70807
ContentId  : DMM70807
FileName   : DMM-070807_1.m4v
BaseName   : DMM-070807_1
Directory  : N:\Testing
FullName   : N:\Testing\DMM-070807_1.m4v
Extension  : .m4v
Length     : 976.14
PartNumber : 1

Id         : DMM-70807
ContentId  : DMM70807
FileName   : DMM-070807_2.m4v
BaseName   : DMM-070807_2
Directory  : N:\Testing
FullName   : N:\Testing\DMM-070807_2.m4v
Extension  : .m4v
Length     : 1062.78
PartNumber : 2

Id         : JMSZ-083
ContentId  : JMSZ00083
FileName   : JMSZ-83_1.mp4
BaseName   : JMSZ-83_1
Directory  : N:\Testing
FullName   : N:\Testing\JMSZ-83_1.mp4
Extension  : .mp4
Length     : 1346.89
PartNumber : 1

Id         : JMSZ-083
ContentId  : JMSZ00083
FileName   : JMSZ-83_2.mp4
BaseName   : JMSZ-83_2
Directory  : N:\Testing
FullName   : N:\Testing\JMSZ-83_2.mp4
Extension  : .mp4
Length     : 1069.16
PartNumber : 2
```

**Comment by jvlflame** [comment]
Ah yep, didn't see the comment where you said both cases were multi-part. There's some special interactions going on with the multi-part to correctly get the part number. I'll see if there's any adjustments that can be made for these cases.

**Comment by jvlflame** [comment]
Updated matcher for logic differentiating contentId from dvdId for 5 digit IDs.

```
C:\> Javinizer -Path 'C:\Javinizer\Old Files\' -Preview

Id         : DMM-070807
ContentId  : DMM070807
FileName   : DMM-070807_1.mp4
BaseName   : DMM-070807_1
Directory  : C:\Javinizer\Old Files
FullName   : C:\Javinizer\Old Files\DMM-070807_1.mp4
Extension  : .mp4
Length     : 0
PartNumber : 1

Id         : DMM-234
ContentId  : DMM00234
FileName   : DMM00234_1.mp4
BaseName   : DMM00234_1
Directory  : C:\Javinizer\Old Files
FullName   : C:\Javinizer\Old Files\DMM00234_1.mp4
Extension  : .mp4
Length     : 0
PartNumber : 1
```
