### ISSUE TITLE
trouble with mapped network drive being recognized as a valid path

### ISSUE THREAD

**Issue by AreYouDeeWhy** [jvlflame/Javinizer#228]
## Expected Behavior
javinizer should run without errors in the path made in the settings file, which in my case is a mapped network drive with the letter Z (Z:\)

## Current Behavior
Warning thrown, Javinizer doesn't run

"WARNING: [Javinizer] Path [Z:\UnsortedJav] is not a valid path"

## Steps to Reproduce (for bugs)

i recently updated this version from, i think 2.1.6 to 2.3.3 so it's possible i could have messed something up during the upgrade process. i manually re-edited the settings json myself to be closely similar to my original settings in 2.1.6

## Your Environment
* Module version used: 2.3.3
* Operating System and PowerShell version: ps 7.1.0, windows 10 home 64-bit VM

**Comment by jvlflame** [comment]
Can powershell see your Z:\ drive? For example, can you do `cd z:\` successfully?

This is sometimes an issue if you're running PowerShell in administrator mode and your network drive isn't mapped in an admin scope. If so, then switch back to a non-admin shell and try again.

**Comment by AreYouDeeWhy** [comment]
> Can powershell see your Z:\ drive? For example, can you do `cd z:\` successfully?
> 
> This is sometimes an issue if you're running PowerShell in administrator mode and your network drive isn't mapped in an admin scope. If so, then switch back to a non-admin shell and try again.

oh yeah i got i figured out, thanks. something with administrator mode on all of my programs doesn't want to recognize mapped drives. seems like my VM has been causing me all sorts of issues lately
