### ISSUE TITLE
Genre Not Auto-Updating

### ISSUE THREAD

**Issue by Satir12** [jvlflame/Javinizer#235]
## Expected Behavior

To rename genre's according to the jvGenre.cv rules

## Current Behavior

Keeps old names, logs show that they are being updated, UI does not reflect. Tried through both the GUI and CLI and neither renamed the genres accordingly.

## Steps to Reproduce (for bugs)

Import any movie that has genre's that should be auto changed. Genre's will not change. 

## Your Environment
* Module version used: Works fine on 2.3.3, does not work at all on 2.4.2
* Operating System and PowerShell version: Windows 10 x64, PS7.1.2

**Comment by jvlflame** [comment]
Thanks for the report, confirmed it on my side as well. I was doing a bit of code refactoring on that part and it seems like I missed a line.
