### ISSUE TITLE
Downloading screenshot images does not work in 2.4.3

### ISSUE THREAD

**Issue by herbrot** [jvlflame/Javinizer#239]
## Expected Behavior
downloading images to extrafanart

## Current Behavior
Get-RunspaceData: C:\Users\------\Documents\PowerShell\Modules\Javinizer\2.4.3\Public\Invoke-JVParallel.ps1:568
Line |
 568 |              Get-RunspaceData -Wait
     |              ~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "EndInvoke" with "1" argument(s): "The running command stopped because the
     | preference variable "ErrorActionPreference" or common parameter is set to Stop: [AUKG-506]
     | [Set-JVMovie] Error occurred when creating screenshot image files: Exception calling "DownloadFile"
     | with "2" argument(s): "An exception occurred during a WebClient request.""

## Steps to Reproduce (for bugs)
"sort.download.screenshotimg": true,

## Your Environment
* Module version used: 2.4.3
* Operating System and PowerShell version:
* Major  Minor  Build  Revision
* 7      1      0      -1

**Comment by jvlflame** [comment]
Thanks for reporting... seems to be an issue with the filename creation of the screenshot images in 2.4.0+.
