### ISSUE TITLE
JavDB scraping does not appear to work

### ISSUE THREAD

**Issue by Aaeeschylus** [jvlflame/Javinizer#243]
## Expected Behavior
Scraping data from JavDB that is there when manually going to the site in a browser should be pulled when using it in Javinizer.

## Current Behavior
When scraping a title from javdb, required fields "id", "coverurl", "genre", "maker", "releaseDate", "title" are not found, even though all are present on the JavDB site when manually going there.

## Steps to Reproduce (for bugs)
1) have a file called HEYZO-1212.mp4
2) try to scrape from JavDB (only ```"scraper.movie.javdb": true,``` is set to true)
3) error :
```WARNING: [HEYZO-1212.mp4] Skipped -- missing required fields [id, coverurl, genre, maker, releaseDate, title]```

## Your Environment
* Module version used: 2.4.5
* Operating System and PowerShell version: Win10 20H2, Powershell 7.1.2

**Comment by jvlflame** [comment]
Do you have javdb set in your metadata priorities?

**Comment by Aaeeschylus** [comment]
Ah damn. I swear I had changed that but I musnt have saved the config. Sorry
