### ISSUE TITLE
InstallGUI throws exception at german windows

### ISSUE THREAD

**Issue by herbrot** [jvlflame/Javinizer#244]
## Expected Behavior
Install GUI

## Current Behavior
Line |
 681 |                      Install-JVGui -Force:$Force
     |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error occurred when setting ACL on [C:\Program Files\Javinizer\1.5.13\Universal]: Exception calling "AddAccessRule" with "1" argument(s): "Some or all identity references could not be translated."
	 

## Your Environment
* Module version used:
* Operating System and PowerShell version:
changing line 118 in Install-JVGui.ps1
$aclRule = New-Object System.Security.AccessControl.FileSystemAccessRule("everyone", "FullControl", "ContainerInherit,Objectinherit", "none", "Allow")
to
$aclRule = New-Object System.Security.AccessControl.FileSystemAccessRule(([wmi]"Win32_SID.SID='S-1-1-0'").AccountName, "FullControl", "ContainerInherit,Objectinherit", "none", "Allow")

works for me
( PS C:\> 
([wmi]"Win32_SID.SID='S-1-1-0'").AccountName
Jeder)

**Comment by jvlflame** [comment]
Didn't even occur to me that different language windows would have that issue. Thanks for also providing a solution to finding the `Everyone` user account.

Going to also link [this](https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/security-identifiers-in-windows#well-known-sids-all-versions-of-windows) doc here for my reference.
