### ISSUE TITLE
Can't insert actor image on jellyfin

### ISSUE THREAD

**Issue by pize98** [jvlflame/Javinizer#252]
## Current Behavior
It worked well at the beginning of the installation, but when I run it again, the above error appears.

## Steps to Reproduce (for bugs)

![image](https://user-images.githubusercontent.com/81085413/111999313-322f1600-8b60-11eb-95c8-1c4ebdb86c31.png)

## Your Environment
* Module version used:2.4.4
* Operating System and PowerShell version:

**Comment by jvlflame** [comment]
Interesting, do you know if that error is occurring on all the actors, or only a select few?

Can you try running with verbose? It will show you name of the actor image being set.
```powershell
Javinizer -SetEmbyThumbs -Verbose
```
```
VERBOSE: [Set-JVEmbyThumbs] Set [Aoyama Yui] => [https://pics.r18.com/mono/actjpgs/aoyama_yui.jpg]
VERBOSE: [Set-JVEmbyThumbs] Set [Kimura Tsuna] => [https://pics.r18.com/mono/actjpgs/kimura_tuna.jpg]
VERBOSE: [Set-JVEmbyThumbs] Set [Mizuno Asahi] => [https://pics.r18.com/mono/actjpgs/mizuno_asahi.jpg]
[...]
etc.
```

**Comment by pize98** [comment]
cvs file exists, but I can't insert an actor image into jellyfin.
It is a phenomenon that occurs with all actors.

**Comment by jvlflame** [comment]
I need more information.

What Jellyfin version are you running?

Can you run with `-Verbose`?
Run this command and screenshot the output for me.
```
Javinizer -SetEmbyThumbs -ReplaceAll -Verbose
```

**Comment by pize98** [comment]
![image](https://user-images.githubusercontent.com/81085413/112313970-d0031c00-8ceb-11eb-8fe7-01d9ec179e69.png)

jellyfin version is 10.7.1

**Comment by jvlflame** [comment]
That error is different than the one from earlier? Can you double check that your API key is correct in setting `emby.apikey`? If possible, try recreating the api key as well and re-inserting it into that setting.

**Comment by yumesakiri** [comment]
I had a similar issue and did some debugging - I think Jellyfin's API for POSTing changed, because I was getting 404's on Jellyfin 10.7.1 but downgraded to 10.6.4 and successfully updated actress images.

Example output of it failing and giving a 404:

```
(venv) PS /Users/yumesakiri/Desktop> Javinizer -SetEmbyThumbs -Verbose -Debug
DEBUG: [Set-JVEmbyThumbs] Performing [GET] on URL [http://localhost:8096/emby/Persons/?api_key=259999de34914a23882663f0306988f6]
DEBUG: [Set-JVEmbyThumbs] [ActressCsv - /Users/yumesakiri/.local/share/powershell/Modules/Javinizer/2.4.7/jvThumbs.csv] imported
[Set-JVEmbyThumbs] [Url - http://localhost:8096] [Actress without thumbs - 60]
DEBUG: Performing [POST] on URL [http://localhost:8096/emby/Items/a2ab512c047db79a62cdf2aee0321a73/Images/Thumb?api_key=259999de34914a23882663f0306988f6]
Write-Error: /Users/yumesakiri/.local/share/powershell/Modules/Javinizer/2.4.7/Public/Set-JVEmbyThumbs.ps1:152
Line |
 152 |  …             Write-JVLog -Write:$script:JVLogWrite -LogPath $script:JV …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [Set-JVEmbyThumbs] Error occurred on [POST] on URL
     | [http://localhost:8096/emby/Items/a2ab512c047db79a62cdf2aee0321a73/Images/Thumb?api_key=259999de34914a23882663f0306988f6]: {"type":"https://tools.ietf.org/html/rfc7231#section-6.5.4","title":"Not Found","status":404,"traceId":"00-f02ee012431ed541ab0ae5077d67c663-ac66b34c62d35e42-00"}


```

Example output of it working with Jellyfin 10.6.4:

```
(venv) PS /Users/yumesakiri/Desktop> Javinizer -SetEmbyThumbs -Verbose -Debug
DEBUG: [Set-JVEmbyThumbs] Performing [GET] on URL [http://localhost:8096/emby/Persons/?api_key=e3fa1d5aa37f4d91b5d77e36d6fce904]
DEBUG: [Set-JVEmbyThumbs] [ActressCsv - /Users/yumesakiri/.local/share/powershell/Modules/Javinizer/2.4.7/jvThumbs.csv] imported
[Set-JVEmbyThumbs] [Url - http://localhost:8096] [Actress without thumbs - 60]
DEBUG: Performing [POST] on URL [http://localhost:8096/emby/Items/a2ab512c047db79a62cdf2aee0321a73/Images/Thumb?api_key=e3fa1d5aa37f4d91b5d77e36d6fce904]
DEBUG: Performing [POST] on URL [http://localhost:8096/emby/Items/a2ab512c047db79a62cdf2aee0321a73/Images/Primary?api_key=e3fa1d5aa37f4d91b5d77e36d6fce904]

```

**Comment by jvlflame** [comment]
> I had a similar issue and did some debugging - I think Jellyfin's API for POSTing changed, because I was getting 404's on Jellyfin 10.7.1 but downgraded to 10.6.4 and successfully updated actress images.
> 
> Example output of it failing and giving a 404:
> 
> ```
> (venv) PS /Users/yumesakiri/Desktop> Javinizer -SetEmbyThumbs -Verbose -Debug
> DEBUG: [Set-JVEmbyThumbs] Performing [GET] on URL [http://localhost:8096/emby/Persons/?api_key=259999de34914a23882663f0306988f6]
> DEBUG: [Set-JVEmbyThumbs] [ActressCsv - /Users/yumesakiri/.local/share/powershell/Modules/Javinizer/2.4.7/jvThumbs.csv] imported
> [Set-JVEmbyThumbs] [Url - http://localhost:8096] [Actress without thumbs - 60]
> DEBUG: Performing [POST] on URL [http://localhost:8096/emby/Items/a2ab512c047db79a62cdf2aee0321a73/Images/Thumb?api_key=259999de34914a23882663f0306988f6]
> Write-Error: /Users/yumesakiri/.local/share/powershell/Modules/Javinizer/2.4.7/Public/Set-JVEmbyThumbs.ps1:152
> Line |
>  152 |  …             Write-JVLog -Write:$script:JVLogWrite -LogPath $script:JV …
>      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | [Set-JVEmbyThumbs] Error occurred on [POST] on URL
>      | [http://localhost:8096/emby/Items/a2ab512c047db79a62cdf2aee0321a73/Images/Thumb?api_key=259999de34914a23882663f0306988f6]: {"type":"https://tools.ietf.org/html/rfc7231#section-6.5.4","title":"Not Found","status":404,"traceId":"00-f02ee012431ed541ab0ae5077d67c663-ac66b34c62d35e42-00"}
> ```
> 
> Example output of it working with Jellyfin 10.6.4:
> 
> ```
> (venv) PS /Users/yumesakiri/Desktop> Javinizer -SetEmbyThumbs -Verbose -Debug
> DEBUG: [Set-JVEmbyThumbs] Performing [GET] on URL [http://localhost:8096/emby/Persons/?api_key=e3fa1d5aa37f4d91b5d77e36d6fce904]
> DEBUG: [Set-JVEmbyThumbs] [ActressCsv - /Users/yumesakiri/.local/share/powershell/Modules/Javinizer/2.4.7/jvThumbs.csv] imported
> [Set-JVEmbyThumbs] [Url - http://localhost:8096] [Actress without thumbs - 60]
> DEBUG: Performing [POST] on URL [http://localhost:8096/emby/Items/a2ab512c047db79a62cdf2aee0321a73/Images/Thumb?api_key=e3fa1d5aa37f4d91b5d77e36d6fce904]
> DEBUG: Performing [POST] on URL [http://localhost:8096/emby/Items/a2ab512c047db79a62cdf2aee0321a73/Images/Primary?api_key=e3fa1d5aa37f4d91b5d77e36d6fce904]
> ```

I just tested on Jellyfin 10.7.1 running on docker image `jellyfin/jellyfin:latest` and it seems to be working as expected. Can you let me know what platform you're running on? Maybe I can reproduce it that way.

I did just check the Jellyfin release notes and for 10.7.0 and I do see one line that may have broken the requests (though I'm not experiencing it somehow).
> We have migrated from ServiceStack to ASP.NET. Web API endpoints no longer accept HTTP Form requests; everything must be application/json. NOTE: Plugins that implement endpoints will also have to migrate.

**Comment by yumesakiri** [comment]
I'm on MacOS Big Sur 11.2.3, on an M1 mac.

**Comment by jvlflame** [comment]
@yumesakiri Unfortunately I don't have a Mac to test on... @pize98 are you also on Mac?

**Comment by damenootoko** [comment]
just to jump in, I'm on windows and I have this issue too, haven't tried to downgrade the jellyfin though.

also, I have other libraries on my jellyfin instance (tv shows, movies, cartoon) I assumed that it was error for those libraries characters but it seems it also affected the jav actress, as some of the actress that showed up fine on emby didn't show up in jellyfin

I'm on jellyfin 10.7.2

**Comment by jvlflame** [comment]
@damenootoko Weird. Possibly a change/bug in Jellyfin in one of the inbetween versions?
