### ISSUE TITLE
i have too much files . is it a way for  continue  "sorting and create nfo " if i cant sort it all in time.

### ISSUE THREAD

**Issue by maloadjav** [jvlflame/Javinizer#264]
## Expected Behavior

everything is fine . i just dont know how to . i have too much jav movies on my pc and my pc can sort it   200 item per hours.

for me ,running my pc for  20 +  hours is not good  for my old pc . 0 0  

so i am here then i will tell you something too

1 javdb  ban your access  *..............................  i got it from the log but it really not much.  other  website is fine anyway.

2 i dont see any  nfo file when i use  javzinier  gui for  sorting  but  it can  scrap data  very  good  ....... may be i dont know where to look for  nfo file .  when i using  command line then i see it creat nfo  somewhere that i want them to be 

3 in gui  ... i cant sort  form   example   e:\data   ,  it will error

i need to  begin at    e:\  and then  goto  e\data  so it will  work 

## Current Behavior

sorting with  cmd  

## Your Environment
* Module version used:  window 10
* Operating System and PowerShell version:
o i dont no  but its can run  javzinier

**Comment by jvlflame** [comment]
> for me ,running my pc for 20 + hours is not good for my old pc . 0 0

I'd recommend just splitting the files you need to sort into different directories. Then you can do batches of something like 20-30 movies at a time or whatever number you want.

> 1 javdb ban your access *.............................. i got it from the log but it really not much. other website is fine anyway.

Yes.. it seems like javdb is cracking down on scraping their site. I don't have any solution at the moment.

> 2 i dont see any nfo file when i use javzinier gui for sorting but it can scrap data very good ....... may be i dont know where to look for nfo file . when i using command line then i see it creat nfo somewhere that i want them to be

Are you completing the sort after you do the metadata search? You need to use either the single sort or complete sort after you have the metadata. 
![image](https://user-images.githubusercontent.com/17932235/122317826-fbed0280-ced2-11eb-997a-a67d5a73d105.png)

> 3 in gui ... i cant sort form example e:\data , it will error i need to begin at e:\ and then goto e\data so it will work

I'm not sure exactly what issue that is... if you are able to get any error logs that would help. Also maybe try running that some command from the commandline with `Javinizer -Path e:\data` and see if that shows any errors.

**Comment by maloadjav** [comment]
thank you so much. for the error that  i mention in the topic that because  i  dont  check my tying carefully.
sorry .the program work fine .
