### ISSUE TITLE
report bug about  Get-RunspaceData  . 

### ISSUE THREAD

**Issue by maloadjav** [jvlflame/Javinizer#265]
Get-RunspaceData: C:\Users\\Documents\PowerShell\Modules\Javinizer\2.4.11\Public\Invoke-JVParallel.ps1:561
Line |
 561 |                      Get-RunspaceData
     |                      ~~~~~~~~~~~~~~~~
     | Exception calling "EndInvoke" with "1" argument(s): "The running command stopped because the
     | preference variable "ErrorActionPreference" or common parameter is set to Stop: [CWPBD-99]
     | [Set-JVMovie] Error occurred when creating thumbnail image file [e:\2nfc\CWPBD-99 [CATWALK] - CATWALK
     | POISON 99 My sister has Goddess Butt, so I did Crean Pie.  Yu Shinoda (Blu-ray) (2014)\fanart.jpg]:
     | Exception calling "DownloadFile" with "2" argument(s): "Could not find file
     | 'C:\imgs\cover\47z_b.jpg'.""

## Your Environment
* Module version used:
* newversion
* Operating System and PowerShell version: win 10

**Comment by jvlflame** [comment]
Is it a consistent error? It may just be a network error.

**Comment by maloadjav** [comment]
no  finally i got  datas from that movies.  i run command so many times.  and now i try to grab the data of this id and get the error again  .  may be its network error . thank you so much
