### ISSUE TITLE
Add option to save coverUrl field into .nfo file

### ISSUE THREAD

**Issue by mgelln** [jvlflame/Javinizer#267]
## Expected Behavior

I think it would be worthwhile to save the coverUrl in the .nfo file (other scrapers use the .nfo field "thumb" or "fanart.thumb"). This way the .nfo file can contain information on the location of the movies cover image, incase the local .jpgs are lost or the .nfos are moved to other directories.

## Current Behavior

Currently in the metadata editor there is a field "coverUrl" which is correctly scraped and filled in with a URL to the cover of the video.

However when sorting the movie the resulting .nfo file does not have this coverUrl field.

**Comment by jvlflame** [comment]
Sure, that's an easy change.

So `<thumb></thumb>` for this field?

**Comment by mgelln** [comment]
Thank you! Yeah  `<thumb></thumb>` would be best.
