### ISSUE TITLE
Feature Request: Rename existing folder and video

### ISSUE THREAD

**Issue by joejoe0243** [jvlflame/Javinizer#268]
## Expected Behavior
A function to rename the existing folder and video name for re-organize purpose

## Current Behavior
Currently, sorting only create new folder and move video inside

## Your Environment
* Module version used: 2.4.11
* Operating System and PowerShell version: Win 10 / PowerShell 7.1.1

**Comment by jvlflame** [comment]
Can you explain more on the functionality of this?

Are you talking about refreshing metadata of already sorted videos? If so, you can achieve this by using the `-Update` switch, or setting `"sort.movetofolder"` to false.

**Comment by joejoe0243** [comment]
example, I already have a folder of contains a video and a cover photo

  SSNI-963 Japan's No. 1 SEX Cosplayer Yua Mikami
        -- video.mp4
        -- cover.jpg

I would like to rename the folder name (e.g. to Japanese), video and cover (file name is able to rename or re-download in App). But the there is no option to rename folder. I don't mind to do it one by one in App.

**Comment by jvlflame** [comment]
If I am understanding correctly, I think it would be easier to re-sort the movie using Javinizer rather than having a custom function to read existing folders and perform a rename.

The default setting for the folder name is: `"sort.format.folder": "<ID> [<STUDIO>] - <TITLE> (<YEAR>)",` which would result in: `SSNI-963 [S1 NO.1 STYLE] - The Top Sex Cosplayer In Japan - Yua Mikami (2021)` with the default priority settings.

If you wanted it in Japanese, you can change the setting to something like `"sort.format.folder": "<ID> <ALTERNATETITLE>` which would make it: `SSNI-963 日本一のSEXコスプレイヤー 三上悠亜` with the default priority settings.

You can also add `"dmmja"` to the top of setting `"sort.metadata.priority.title"` or any scraper that has Japanese data if you want to use `<TITLE>` instead of `<ALTERNATETITLE>`.

Similarly, the following files can be renamed using "Format Strings" using the following settings:
```powershell
"sort.format.file": "<ID>", # MOVIE FILE NAME
"sort.format.folder": "<ID> [<STUDIO>] - <TITLE> (<YEAR>)", # FOLDER NAME
"sort.format.posterimg": ["folder"], # COVER IMAGE NAME (Poster)
"sort.format.thumbimg": "fanart", # THUMB IMAGE NAME (Full-size)
"sort.format.trailervid": "<ID>-trailer", # TRAILER VIDEO NAME
"sort.format.nfo": "<ID>", # NFO NAME
"sort.format.screenshotimg": "fanart", # SCREENSHOT IMAGE NAME
"sort.format.screenshotfolder": "extrafanart", # SCREENSHOT FOLDER NAME
"sort.format.actressimgfolder": ".actors", # ACTOR IMAGE FOLDER NAME
```

Here's the [documentation reference](https://docs.jvlflame.net/configuration/custom-naming) for how the format string tags match up to the metadata. If I am misunderstanding what you are trying to accomplish please let me know.

**Comment by joejoe0243** [comment]
> If I am understanding correctly, I think it would be easier to re-sort the movie using Javinizer rather than having a custom function to read existing folders and perform a rename.
> 
> The default setting for the folder name is: `"sort.format.folder": "<ID> [<STUDIO>] - <TITLE> (<YEAR>)",` which would result in: `SSNI-963 [S1 NO.1 STYLE] - The Top Sex Cosplayer In Japan - Yua Mikami (2021)` with the default priority settings.
> 
> If you wanted it in Japanese, you can change the setting to something like `"sort.format.folder": "<ID> <ALTERNATETITLE>"` which would make it: `SSNI-963 日本一のSEXコスプレイヤー 三上悠亜` with the default priority settings.
> 
> You can also add `"dmmja"` to the top of setting `"sort.metadata.priority.title"` or any scraper that has Japanese data if you want to use `<TITLE>` instead of `<ALTERNATETITLE>`.
> 
> Similarly, the following files can be renamed using "Format Strings" using the following settings:
> 
> ```powershell
> "sort.format.file": "<ID>", # MOVIE FILE NAME
> "sort.format.folder": "<ID> [<STUDIO>] - <TITLE> (<YEAR>)", # FOLDER NAME
> "sort.format.posterimg": ["folder"], # COVER IMAGE NAME (Poster)
> "sort.format.thumbimg": "fanart", # THUMB IMAGE NAME (Full-size)
> "sort.format.trailervid": "<ID>-trailer", # TRAILER VIDEO NAME
> "sort.format.nfo": "<ID>", # NFO NAME
> "sort.format.screenshotimg": "fanart", # SCREENSHOT IMAGE NAME
> "sort.format.screenshotfolder": "extrafanart", # SCREENSHOT FOLDER NAME
> "sort.format.actressimgfolder": ".actors", # ACTOR IMAGE FOLDER NAME
> ```
> 
> Here's the [documentation reference](https://docs.jvlflame.net/configuration/custom-naming) for how the format string tags match up to the metadata. If I am misunderstanding what you are trying to accomplish please let me know.

If re-sort, it would create a new folder and move the video in. Then I have to move the folder up a level for retain folder structure.
But I have thousands of folder have to rename. It is not possible.

**Comment by jvlflame** [comment]
Can you give me an example of the full folder structure that you're trying to maintain? I'm trying to understand since my thought would be that you could move batches of them (e.g. 100 at a time) into a single folder and then sort them all and just recreate the structure from scratch.

**Comment by joejoe0243** [comment]
> Can you give me an example of the full folder structure that you're trying to maintain? I'm trying to understand since my thought would be that you could move batches of them (e.g. 100 at a time) into a single folder and then sort them all and just recreate the structure from scratch.

Indeed, that is a way. But I would like to retain all file's timestamp. So I am looking for a rename approach.

**Comment by jvlflame** [comment]
Ok, I'll do a bit of testing to see how hard it is to implement.

**Comment by jvlflame** [comment]
I have a somewhat working version on my dev branch. The functionality will kind of bug out if multiple different videos are in the same folder such as `SNIS-963.mp4` and `SNIS-950.mp4`.

It requires settings `"sort.movetofolder": false` amd `"sort.renamefolderinplace": true`.
I'll probably push a new release tomorrow with this included.
