### ISSUE TITLE
Add option to leave role field empty

### ISSUE THREAD

**Issue by xjdvn** [jvlflame/Javinizer#273]
## Expected Behavior
There should be a toggle within the settings to allow for actress roles to be written within the nfo file.

## Current Behavior
Currently, it is a bit redundant having "ACTRESS" as Actress written into the nfo file. Having just the actress name is a lot cleaner.

**Comment by jvlflame** [comment]
I added setting ` "sort.metadata.nfo.addgenericrole": true,` which you can set to default to remove the role.
