### ISSUE TITLE
Complete Sort on All Movies used to update covers Crashes

### ISSUE THREAD

**Issue by gummykage** [jvlflame/Javinizer#277]
## Expected Behavior
Sort completes all remaining items when click on "Complete Sort on All Movies"

## Current Behavior
Crashes with Message

## Steps to Reproduce (for bugs)
1.) Select existing sorted folder to update.
2.) Toggle update (Need to fetch covers)
3.) Wait for Sort Search to finish to Preview to change metadata
4.) Clicking on complete sort on current movie works.
5.) Clicking on Complete Sort on All Movies Causes crash in picture.
6.) Have to re-sort parse again.

## Your Environment
* Module version used:
* Operating System and PowerShell version:

![image](https://user-images.githubusercontent.com/9695713/125956096-318425a6-7ed7-4fca-b1da-5dc8f0d354a6.png)

**Comment by jvlflame** [comment]
Thanks for catching this issue. I pushed a new GUI version.

If you're using the windows version, just close the application and re-run `Javinizer -OpenGUI` and it will automatically update to the latest version. Otherwise, new docker versions will be out shortly.

**Comment by gummykage** [comment]
Great thank you! I will test and see if it still occurs.

**Comment by gummykage** [comment]
Looks like its working! I'll reopen with you if it occurs again. Smooth sailing again. I also dropped my threads down to 2 at a time after seeing people getting banned on javdb.
