### ISSUE TITLE
Config file gets corrupted randomly

### ISSUE THREAD

**Issue by gummykage** [jvlflame/Javinizer#278]
## Expected Behavior
Making changes to settings will commit and be applied.

## Current Behavior
Sometimes making changes to settings causes the config file to get corrupted setting some boolean values to null. In this case the Advanced Search in the preview mode has areas that are displayed and not working after corruption occurs.

## Steps to Reproduce (for bugs)
Making changes to which scrapers to be used and hitting "Apply" seems to cause this randomly. Seems to happen more often when toggling AVEntertainment, DMM, and JAVLibrary (English one).

## Your Environment
* Module version used: Windows GUI - Latest
* Operating System and PowerShell version: Win7 - Powershell - Latest

![image](https://user-images.githubusercontent.com/9695713/125977546-6a01b967-e06f-48da-813a-d95d365f3fa2.png)

**Comment by jvlflame** [comment]
Do you have the tokyohot scrapers in your settings? Those were adding in one of the latest releases so if you copy pasted your previous config it might be missing when you updated.

```
  "scraper.movie.tokyohot": false,
  "scraper.movie.tokyohotja": false,
  "scraper.movie.tokyohotzh": false,
```

**Comment by gummykage** [comment]
I downloaded the one from the official release, unzipped it and copied the json settings over.

Didn't modify it. I'm guessing, but maybe the official link one has it missing I'll manually add it to mine.

![image](https://user-images.githubusercontent.com/9695713/125979411-a8369790-64e7-4fc0-9306-e42876075e1e.png)

![image](https://user-images.githubusercontent.com/9695713/125979429-a82ff80a-53e9-4aa9-954c-45bbe6b472b6.png)

**Comment by gummykage** [comment]
I redownloaded and unzipped. It looks like it was missing.

I added:

  "web.sort.manualsearch.tokyohot": false,
  "web.sort.manualsearch.tokyohotja": false,
  "web.sort.manualsearch.tokyohotzh": false,

![image](https://user-images.githubusercontent.com/9695713/125980372-f486ba26-5780-4a6a-8d29-b297f27b5466.png)

![image](https://user-images.githubusercontent.com/9695713/125980405-1734ad31-a1bd-4201-8d7b-0dcde84f0ceb.png)

Resolve this issue. Thanx for all your hardword =D This JAVLibrary having to reenter the cookies and user agent is really annoying... Is there someway to save it? Or does the cookies constantly change?

**Comment by jvlflame** [comment]
Glad you got it working!

If you enter the cookies, it should persist in your settings and let you scrape for around ~30 minutes. After that the cookies expire and you'll have to enter them again. It's annoying but usually the Cloudflare blocking will go away after a few days.
