### ISSUE TITLE
please try to scrap that  https://www.mgstage.com  . because   the prestige and msg left  r18 and javlibrary 

### ISSUE THREAD

**Issue by maloadjav** [jvlflame/Javinizer#279]
## Expected Behavior

add new  new jav database s website . they have something that javlibrary , dmm  , r18  dont have  it 
## Current Behavior

-
## Your Environment
new version
* Module version used:
* update
* Operating System and PowerShell version:
win 10  and up to date powershell

**Comment by jvlflame** [comment]
There is already a scraper for mgstage.

Use setting `"scraper.movie.mgstageja": true` and add `mgstageja` to your metadata priority settings.

**Comment by maloadjav** [comment]
OHH.. Thank you so much.
can i ask you anothee question ?

i read the  topic   https://docs.jvlflame.net/configuration/output-folder-structure

i dont understand it but i think its about  i can do some sort folder  with my designing .

hmm.. the other question come in

i  want to create folder like this 

actress/the  studio that create movie / id of the movies.

what is the command line that i need to  put in the powershell

thank you so much

**Comment by jvlflame** [comment]
> i want to create folder like this
> actress/the studio that create movie / id of the movies.

You can use these settings to get that folder format. Movies with multiple actresses will be grouped into a `@Group` folder.

```
"sort.format.outputfolder": ["<ACTORS>", "<STUDIO>"]
"sort.format.folder": "<ID>"
```

**Comment by maloadjav** [comment]
thank you so much
