### ISSUE TITLE
javinizer unable to dot source

### ISSUE THREAD

**Issue by Camuska67** [jvlflame/Javinizer#281]
Hi,

I encounter an issue while trying to use Javinizer :

This appears, and stop the installation process in its track, when I try the "Import-Module C:\Users\Maxime\Downloads\Compressed\Javinizer.2.5.3\Javinizer\Javinizer.psm1" command in Powershell

"Unable to dot source [C:\Users\Maxime\Downloads\Compressed\Javinizer.2.5.3\Javinizer\Public\Get-TokyoHotUr 
   l.ps1],Microsoft.PowerShell.Commands.ImportModuleCommand"

**Comment by jvlflame** [comment]
Make sure you use PowerShell 7, not Windows PowerShell.

**Comment by Camuska67** [comment]
Works perfectly, thank you :)
