### ISSUE TITLE
ERROR: Cannot validate argument on parameter 'Year' [...]

### ISSUE THREAD

**Issue by jvlflame** [jvlflame/Javinizer#282]
Update to 2.5.4 for fix

-----------------

R18 has updated their movie page which has broken the current iteration of the scraper.
Fixes are incoming to address this.

![image](https://user-images.githubusercontent.com/17932235/127337628-f06c1d8a-e7fd-4a42-a56a-d52b35f7346c.png)

**Comment by chandi1988** [comment]
> Update to 2.5.4 for fix
> 
> R18 has updated their movie page which has broken the current iteration of the scraper.
> Fixes are incoming to address this.
> 
> ![image](https://user-images.githubusercontent.com/17932235/127337628-f06c1d8a-e7fd-4a42-a56a-d52b35f7346c.png)
