### ISSUE TITLE
R18 problem

### ISSUE THREAD

**Issue by RabidWolf** [jvlflame/Javinizer#285]
## Expected Behavior
Move file to folder
Create .nfo, covers

## Current Behavior
It creates the folder but it doesn't move the file or create .nfo or cover. Comes up with Error: Could not find part of path

## Your Environment
* Module version used:
* Operating System and PowerShell version:
Win 10 Pro
2.55 GUI
Powershell: 7.1.3

**Comment by jvlflame** [comment]
1. Are you using the Windows GUI `javinizer -opengui` or docker?

2. Can you post your settings file? I'm unable to reproduce on my end.

**Comment by RabidWolf** [comment]
Yep Javinizer -OpenGUI

Do I paste the jvsetting.json here?

**Comment by jvlflame** [comment]
Can you attach the file instead? I think some of the fields in your paste got deleted due to github's markdown.

**Comment by RabidWolf** [comment]
[jvSettings.txt](https://github.com/jvlflame/Javinizer/files/6909637/jvSettings.txt)

Hope this works.

**Comment by jvlflame** [comment]
I think I found your issue.

Remove the extra space at the end of your setting and try sorting again.
```
### Before
"sort.format.folder": "<ID> <TITLE><ACTORS> "  <-- Extra space here after <ACTORS>

### After
"sort.format.folder": "<ID> <TITLE><ACTORS>"
```

**Comment by RabidWolf** [comment]
So that's what it was. All good here now thank you.
