### ISSUE TITLE
Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request.

### ISSUE THREAD

**Issue by kmh1616** [jvlflame/Javinizer#286]
The error message is as follows. Due to my network speed, each file larger than 30-40Mb may report this error, and I can download it manually in 30 seconds. How can I modify the default timeout setting?

Get-RunspaceData: C:\Users\kmh\Documents\PowerShell\Modules\Javinizer\2.5.5\Public\Invoke-JVParallel.ps1:561
Exception calling "EndInvoke" with "1" argument(s): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: [SSNI-780]
[Set-JVMovie] Error occurred when creating trailer video file [https://awscc3001.r18.com/litevideo/freepv/s/ssn/ssni00780/ssni00780_dmb_w.mp4] to [SSNI-780-trailer]: Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request.""

**Comment by jvlflame** [comment]
I would need to add additional functionality to adjust the timeout.

**Comment by jvlflame** [comment]
I added a setting to configure the timeout duration. The number value is specified in milliseconds (ms) with a default of 100,000 (100 seconds). This will be released in 2.5.6.

```
  "sort.download.timeoutduration": 100000,
```
