### ISSUE TITLE
EnglishAlias with Emby

### ISSUE THREAD

**Issue by Avatarthe** [jvlflame/Javinizer#290]
## Expected Behavior
Using JAVinizer with Emby when scrapping a film with an actress who has changed her name previously I would like to search on emby using her old or new name and be directed to ALL of her films (old name and new name)
Maybe give the option of adding the EnglishAlias name as another actress in the film?
## Current Behavior
When I scrape a film with JAVinizer I can get the current name, the older alias or normilize to the old Alias. However while some actresses are best know by their original names (RION), others are best know by the newer name (Kurea Hasumi, Eimi Fukada)

It would be nice to be able to get the actresses films under all of her names 

## Your Environment
* Module version used:
* Operating System and PowerShell version:
Windows 10
Powershell 7.02

**Comment by jvlflame** [comment]
So say for example JAVLibrary provides both the actress's current name as well as her older aliases, you would want all versions of the actress's name as a separate entry in the nfo metadata?

**Comment by Avatarthe** [comment]
Yes. I would like the option of including actress listings for all the actresses aliases (old and new) on getting off her films, but this could get very messy if she had lots of aliases, maybe a better way would be to normalize based on the actresses oldest name but also include a listing for the name the actress is billed under for that film. That way say you search Eimi Fukada it will bring up all of her films for her new Eimi personal but you will see her old name, Amami Kokoro . listed on these films as well.  Selecting the old name will then bring up her complete catalog.

I think this gives you the best of both worlds, you can find all of her films or just the Eimi ones.

Thanks
________________________________

**Comment by jvlflame** [comment]
Added `sort.metadata.nfo.addaliases` in 2.5.7
