### ISSUE TITLE
Ability to scrape javlibrary actresses including other names in parenthesis? 

### ISSUE THREAD

**Issue by Borisbee1** [jvlflame/Javinizer#291]
I'm wondering if there is a way to have javlibrary scrape the actress names without stripping out the alternate names.  The ability to look at the csv and pick the oldest name is actually really useful but my library has already been scraped using the complete javlibrary name so I need to stick with the same convention.

Is there a way to, for example, have it keep Hasumi Kurea (Adachi Ami) as the name instead of stripping out the (Adachi Ami ) part?

**Comment by jvlflame** [comment]
I think the main issue is that if javlibrary ever adds additional actress aliases to the site, the name will change. I will add a way to include all aliases as separate actresses in the metadata as per #290.

**Comment by jvlflame** [comment]
Added `sort.metadata.nfo.addaliases` in 2.5.7
