### ISSUE TITLE
> Update to 2.5.4 for fix

### ISSUE THREAD

**Issue by chandi1988** [jvlflame/Javinizer#292]
> Update to 2.5.4 for fix
> 
> R18 has updated their movie page which has broken the current iteration of the scraper.
> Fixes are incoming to address this.
> 
> ![image](https://user-images.githubusercontent.com/17932235/127337628-f06c1d8a-e7fd-4a42-a56a-d52b35f7346c.png)

_Originally posted by @chandi1988 in https://github.com/jvlflame/Javinizer/issues/282#issuecomment-898943416_

**Comment by jvlflame** [comment]
Did you receive this error on the newest version? Can you let me know the movie ID that you received this error on?
