### ISSUE TITLE
Is it only for cencored JAVs? Is there any way to port the uncencored database?

### ISSUE THREAD

**Issue by bonepyaesone** [jvlflame/Javinizer#296]
## Expected Behavior
Can we add support for the uncensored JAV codes as well?

## Current Behavior
Some of the uncensored JAV codes including Jgirl-Paradise, CWP, LAF, MCDV, RHJ, SMBD were left out as they are not in Javlibrary, R18, and DMM.

## Steps to Reproduce (for bugs)
I am trying to sort both censored and uncensored videos but only the censored JAV code works.

## Your Environment
* Module version used: 2.5.7
* Operating System and PowerShell version: 7

**Comment by endofthescope** [comment]
CWP, LAF and SMBD are available if you scrape AVEntertainments, the rest you will probably find on other scrapes too.

**Comment by jvlflame** [comment]
Like @endofthescope mentioned, there are a couple of other scrapers you can enable by viewing the settings file with `Javinizer -OpenSettings`. Enable the scrapers and add them into your [metadata priorities](https://docs.jvlflame.net/configuration/metadata-priorities). Obviously not all uncensored titles will be there, but hopefully this scrapes the majority of them for you.

I don't really have plans to add any additional scrapers in the short-term, but that may change in the future.
