### ISSUE TITLE
Google Trans and Google Trans New doesn't works.

### ISSUE THREAD

**Issue by EvilKing3** [jvlflame/Javinizer#299]
## Expected Behavior
Translating the description/plot.

## Current Behavior
It doesn't translate anything.

## Steps to Reproduce (for bugs)
  "sort.metadata.nfo.translate": true,
  "sort.metadata.nfo.translate.module": "googletrans", or "google_trans_new" (tried both)
  "sort.metadata.nfo.translate.field": "plot", or "description" (tried both)
  "sort.metadata.nfo.translate.language": "en",
  "sort.metadata.nfo.translate.keeporiginaldescription": false,

## Your Environment
* Module version used: 2.5.7 cli

* Operating System and PowerShell version: Windows 10, PowerShell 7.1.4, latest version of google trans and google trans new.

**Comment by jvlflame** [comment]
I believe google_trans_new is currently non-functional, but googletrans is still working for me.
Did you install the `4.0.0rc1` version of the module? The older versions are currently unsupported.

```
pip install googletrans==4.0.0rc1
```

**Comment by EvilKing3** [comment]
Yes I have that version installed, I noticed that in the output file the description is called plot, so I tried to change it in the settings file but still doesn't works.

**Comment by jvlflame** [comment]
Keep it as `description`, not plot. Is your Python path set correctly? Open a pwsh terminal type `python`.
![image](https://user-images.githubusercontent.com/17932235/132647045-27700bcf-43e3-4ec6-a3fa-12c5c261034a.png)

You can also do a bit of troubleshooting directly with the translate script if you run it directly.
![image](https://user-images.githubusercontent.com/17932235/132647732-4ba815c4-978c-4a00-9d61-f40777864149.png)

1. Run `Javinizer -OpenModule` and copy the module path
2. Navigate to the module path in powershell with `cd`
3. Run the translate.py script with `python .\translate.py おはよう en`
4. Output the content of the temp path that the script returns with `Get-Content [..path]`

If any of the above steps fail, I'm sure we can figure out where it's not working.

**Comment by EvilKing3** [comment]
Ok probably I've found the problem, but I have no clue on how to solve it, I did all the steps, on the first one python worked correctly (version 3.9.7)
second step I've found the path, but when I tried to input the translate command the kanji character were bugged when inserted on powershell.. so I think that maybe the main problem:
![image](https://user-images.githubusercontent.com/5150545/132668531-339ce650-a814-4650-bd0f-6a2b86c5574b.png)

**Comment by jvlflame** [comment]
Go to your W10 settings, add the Japanese language, and then reboot.
![image](https://user-images.githubusercontent.com/17932235/132684773-490650e3-831d-46e7-ac9a-676373d0c8bf.png)

If that doesn't work, you can try changing your system locale to Japan as well.

**Comment by EvilKing3** [comment]
Ok so I've added Japanese language pack to Windows 10, rebooted, tried again, no success, changed the locale to Japanese, rebooted, tried again, stil doesn't works.
I decided to use the default PowerShell on windows and apparently it let me past Kanji there, but still doesn't works, probably because it works differently this powershell, but at least the kanji works:
![image](https://user-images.githubusercontent.com/5150545/132696458-8c59823b-6178-48c9-b0d9-9d81a54d03e0.png)

**Comment by jvlflame** [comment]
Oh, you need to add a space between the japanese letters and `en`.

```
python .\translate.py おはよう en
```

The list index is out of range because it's missing the second parameter.

**Comment by EvilKing3** [comment]
You were right, I tried to translate with OpenShell 7, even if it still show the "unicode error" instead of the kanji, the translation works, I tried to do few JAV to test it, and it works fine now.
Thanks I think I was missing the japanese locale it was probably the root of the problem <_<
