### ISSUE TITLE
Unable to Scrape Movie for R18

### ISSUE THREAD

**Issue by ukiya21** [jvlflame/Javinizer#309]
I'm trying to match some JAV from R18 start with STARS but returned nothing.. Noticed this behaviour since last mmonth.. I checked the actress is still at R18. Any idea why it failed? 

STARS-435

**Comment by aka-fork** [comment]
Hi there,
I also not receive any result when find with "SCUTE-1015" (code with 4 number) from R18.
![image](https://user-images.githubusercontent.com/93849402/141183016-5cbd62da-2e6d-4d49-a064-d6db580b4fe9.png)

**Comment by jvlflame** [comment]
@aka-fork You have to search it with the exact ID: `Javinizer -Find 'SCUTE-1015-kotone' -R18`
![image](https://user-images.githubusercontent.com/17932235/141228776-de03a706-c493-4626-b4b7-a3b8f7bcb8bd.png)

Rename your file to `SCUTE-1015-kotone` and you can sort it with `Javinizer -Path . -Strict`
