### ISSUE TITLE
deepl translate doesn't work on Javinizer Web GUI v2.5.9-1

### ISSUE THREAD

**Issue by fumbleone** [jvlflame/Javinizer#312]
## Expected Behavior
Description and title should be translated from japanese when I scrape. I have set
```
"sort.metadata.nfo.translate.field": [
    "Description",
    "Title"
  ]
```

I double checked my `sort.metadata.nfo.translate.deeplapikey`

I even downloaded `translate_deepl.py` to my computer and ran it. It works properly so my API key is not the problem.

## Current Behavior
Description and title remains in japanese. googletrans does work properly.

## Your Environment
* Module version used: Javinizer Web GUI v2.5.9-1
* Operating System and PowerShell version: Docker on Mac OS 11.5.2

**Comment by shashibici** [comment]
I have the same issue. Use Javinizer Web GUI v2.5.9-1 on Windows. Is there a fix for windows?

**Comment by jvlflame** [comment]
> I have the same issue. Use Javinizer Web GUI v2.5.9-1 on Windows Powershell 7. Is there a fix for windows?

@shashibici  Have you tried sorting via the CLI and seeing what error you receive in the console?
I'm guessing it's the same error with the missing `requests` module, so run `pip install requests`, restart the gui, and then retry the sort.

**Comment by shashibici** [comment]
Resolved. 
https://developers.google.com/admin-sdk/directory/v1/languages
The language code must be 'zh' rather than 'zh-CN'
Error from deepl translate if using 'zh-CN'

{"message":"\"Value for 'target_lang' not supported.\""}
