### ISSUE TITLE
How can I save sort results to my file system on GUI?

### ISSUE THREAD

**Issue by shashibici** [jvlflame/Javinizer#317]
## Expected Behavior
With web GUI, I should be able to save sort results to my local file system. 

## Current Behavior
I cannot find a button on web GUI nor a document stating how to save a sort result (of 100 videos) to my local file system.  
After I click the 'sort' button, it takes some time to run over the 100 videos and populate the web page with correct information. However, after that I cannot see any outputs to my local file system. 
I leave the 'location.input' field blank by manually choosing a path of videos. 
I leave the 'location.output' field blank hoping it will figure out a default place or let me choose a path to save to after sort. 

## Steps to Reproduce (for bugs)
N/A

## Your Environment
* Module version used: 2.5.9
* Operating System and PowerShell version: N/A

**Comment by jvlflame** [comment]
You can use the buttons on the top left panel to sort the results.

https://docs.jvlflame.net/using-javinizer/using-the-gui

**Comment by shashibici** [comment]
> 
> 
> You can use the buttons on the top left panel to sort the results.
> 
> https://docs.jvlflame.net/using-javinizer/using-the-gui

Thanks for your promptly response. But this is not what I am asking. 
After I use the sort buttons and the web page is showing the cotents grabed from Internet (this step works fine), I cannot find a way to **export** them to my file system. If I kick off another sort, the previous sort got lost.

**Comment by shashibici** [comment]
I finally figure out the 'complete sort' button on the top left panel. Thanks.
