### ISSUE TITLE
Javinizer -Find -Aggregated -Nfo Not Created folder

### ISSUE THREAD

**Issue by nova168168** [jvlflame/Javinizer#318]
Hi, 

Why after running command  'Javinizer -Find "xxxxx.mp4" -R18 -Javlibrary -DmmJa -Aggregated -Nfo' , the Javinizer Not Create anything  !!  But it had scrape output like below !  thanks !

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<movie>
    <title>[STARS-094] Furukawa Iori I Am Alone In The Company Of The Woman Boss
 And The Company Yearning For The Night Of Guerrilla Heavy Rain ... We Were Not
Able To Go Back We Had SEX Until Morning</title>
    <originaltitle>古川いおり ゲリラ豪雨の夜に憧れの女上司と会社で2人きり…帰れ
なくなった僕らは朝までSEXしまくった</originaltitle>
    <id>STARS-094</id>
    <premiered>2019-07-11</premiered>
    <year>2019</year>
    <director>Kirin</director>
    <studio>SOD Create</studio>
    <rating>8.12</rating>
    <votes>17</votes>
    <plot>突然のゲリラ豪雨で1人オフィスに閉じ込められてしまった残業中の伸一。そ
こへびしょ濡れになって駆け込んできたのは女上司のいおりだった。雨の影響で電車が止
まってしまい、憧れの先輩と2人きり。つい理性の糸が切れてしまったのは先輩も同じだ
ったようで、雨と汗にまみれながら貪ように朝までSEXしまくった。</plot>

Nova

**Comment by jvlflame** [comment]
Using the `-Find` command only outputs to the console. If you want to create a file from that output, you can either copy that to a file or you can pipe the output to a file.

```powershell
Javinizer -Find "xxxxx.mp4" -R18 -Javlibrary -DmmJa -Aggregated -Nfo | Out-File .\STARS-094.nfo
```

If you want to actually "sort" the file, use the `-Path` parameter instead of `-Find`.

```powershell
Javinizer -Path "xxxxx.mp4"
```

**Comment by nova168168** [comment]
> 
> 
> Using the `-Find` command only outputs to the console. If you want to create a file from that output, you can either copy that to a file or you can pipe the output to a file.
> 
> ```powershell
> Javinizer -Find "xxxxx.mp4" -R18 -Javlibrary -DmmJa -Aggregated -Nfo | Out-File .\STARS-094.nfo
> ```
> 
> If you want to actually "sort" the file, use the `-Path` parameter instead of `-Find`.
> 
> ```powershell
> Javinizer -Path "xxxxx.mp4"
> ```

thanks !
