### ISSUE TITLE
GUI not able to match while CLI giving errors

### ISSUE THREAD

**Issue by obiwone2000** [jvlflame/Javinizer#323]
Been trying to sort this issue, but not sure what was done wrong. Have followed the installation instruction fully.

![Screenshot](https://user-images.githubusercontent.com/96230480/146336516-1669b613-a7f6-4146-b008-baf7f9135cd2.png)
![Screenshot2](https://user-images.githubusercontent.com/96230480/146336535-305a5b78-de7e-4e37-8f3c-a236ecafdf64.png)

**Comment by jvlflame** [comment]
Either you need to install the `mediainfo` cli application or you can turn off the setting. It should work after that.

**Comment by obiwone2000** [comment]
I installed mediainfo though, is there a reason why GUI can't match?

**Comment by jvlflame** [comment]
Did you add `mediainfo` to your [system PATH](https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/)?

If you've done it correctly, then you should receive the mediainfo output when running from the CLI.

![image](https://user-images.githubusercontent.com/17932235/146449128-aa2d8cb4-199c-469f-9c5f-bd5bd94e49ed.png)

**Comment by obiwone2000** [comment]
It's working now! Thanks
