### ISSUE TITLE
duplicates / videos with the same code

### ISSUE THREAD

**Issue by KagamiButchaU** [jvlflame/Javinizer#327]
## Expected Behavior

videos with the same code scraping with mixed info from different sources. looking for a way to get consistent results

## Current Behavior

example: scraping "MIDV-003" will take the info from maker "graffiti japan" when the desired result is the information from "moodyz" 

## Your Environment
* Module version used: 2.5.10
* Operating System and PowerShell version: windows 10, PS 7.1.2

**Comment by seeyabye** [comment]
This is where aggregated data priority comes in. You will be able to pick your source of choice that suits you better and arrange the list accordingly.
