### ISSUE TITLE
Specify a different jvSettings.json

### ISSUE THREAD

**Issue by arno56** [jvlflame/Javinizer#332]
Is there any way to specify a different setting file (jvSettings.json) when running Javinizer?
I created jvSettings2.json

That's the code line I am using in my Linux Terminal.
pwsh -Command Javinizer -Path /my/path -DestinationPath /my/destination/path -force

Thanks

**Comment by jvlflame** [comment]
Use the `-SettingsPath` parameter.

https://docs.jvlflame.net/using-javinizer/general-usage/updating-settings-via-the-cmdline

**Comment by arno56** [comment]
Thanks [jvlflame](https://github.com/jvlflame)
