### ISSUE TITLE
'sort.download.posterimg' is not working

### ISSUE THREAD

**Issue by Gygun** [jvlflame/Javinizer#335]
## Expected Behavior
Download and Sort Poster Image

## Current Behavior
none (skips the file)

## Steps to Reproduce (for bugs)
Normal sort (even tried with a fresh install)
It was working fine a few days ago, but it stopped. I don't know why.
Other IMG download works fine (backdrop, screens, actors)

## Your Environment
* Module version used: 2.5.10 alpha
* Operating System and PowerShell version: Windows 10H2 Pro v19042.985

**Comment by jvlflame** [comment]
It's likely a python issue.

1. Make sure that `python` is working correctly on your PATH
![image](https://user-images.githubusercontent.com/17932235/165418385-9fccdbcf-c66a-4fa1-9324-f6fedffa5b3f.png)

2. Run `pip list` and ensure that the `Pillow` package is installed
```
Package             Version
------------------- -----------
Pillow              8.1.0
```

**Comment by Gygun** [comment]
Hey, thank you for the quick reply.

Pillow is installed

`Requirement already satisfied: pillow in c:\utl\system\python\lib\site-packages (9.1.0)`

and Python is on path. I updated it just in case.

`$ python
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.`

Poster IMG still doesn't' work
In the log it only shows this:

`[2022-04-26T22:30:26][DEBUG] [SDJS-089] [Set-JVMovie] [Thumbnail - https://pics.r18.com/digital/video/1sdjs00089/1sdjs00089pl.jpg] downloaded to path [F:\Downloads\Asai Kokoha\SDJS-089-backdrop.jpg]`
`[2022-04-26T22:30:26][DEBUG] [SDJS-089] [Set-JVMovie] [Poster - F:\Downloads\Asai Kokoha\SDJS-089-backdrop.jpg] cropped to path [F:\Downloads\Asai Kokoha\SDJS-089-poster.jpg]`

But it doesn't create the file.
Any ideas?

**Comment by jvlflame** [comment]
Did you change your settings?

Open the settings file with `Javinizer -OpenSettings` and check that the following are enabled:
```
"sort.download.posterimg": true,
"sort.format.posterimg": ["folder"],
```

**Comment by Gygun** [comment]
I had it working with this settings, but I noticed today that it stopped cropping the "poster" Everything else works fine.

`  "sort.format.groupactress": true,`
`  "sort.format.delimiter": ", ",`
`  "sort.format.file": "<FILENAME>",`
`  "sort.format.folder": "<ID> [<STUDIO>] - <TITLE> (<YEAR>)",`
`  "sort.format.outputfolder": "",`
`  "sort.format.posterimg": "<FILENAME>-poster",`
`  "sort.format.thumbimg": "<FILENAME>-backdrop",`
`  "sort.format.trailervid": "<ID>-trailer",`
`  "sort.format.nfo": "<FILENAME>",`
`  "sort.format.screenshotimg": "<ID>-screens",`
`  "sort.format.screenshotimg.padding": 1,`
`  "sort.format.screenshotfolder": "extras",`
`  "sort.format.actressimgfolder": "<ID>-actors",`

I just did a fresh install from Powershell with default settings but it didn't work either.

**Comment by Gygun** [comment]
I got it working, It was Pillow! I reinstalled it and now it works. (It was installed, but somehow got corrupted... maybe?) Anyway, thank you for pointing me in the right direction.

**Comment by jvlflame** [comment]
Glad you got it working! I was all out of ideas if it wasn't either of the two solutions.
