### ISSUE TITLE
Unable To Import-Module

### ISSUE THREAD

**Issue by aminhusni** [jvlflame/Javinizer#345]
## Current Behavior
```
Import-Module Javinizer
Exception: Unable to dot source [C:\Program Files\WindowsPowerShell\Modules\Javinizer\2.5.10\Public\Update-JVModule.ps1]
```

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by seeyabye** [comment]
Please see #363 

You shouldn't need to use `Import-Module`. Please install it with `Install-Module`.
