### ISSUE TITLE
Is it possible to add jav321.com to scrapers

### ISSUE THREAD

**Issue by fidofido300** [jvlflame/Javinizer#35]
Is it possible to add jav321.com to scrapers because most of the times I find missing r18 and dmm titles metadata to exist there.

Thanks

**Comment by jvlflame** [comment]
I will look into it. I may just add these as japanese only scrapers.

**Comment by fidofido300** [comment]
You can treat it as you treat dmm???

**Comment by jvlflame** [comment]
Added in release 1.6.0
