### ISSUE TITLE
GUI: Could not load cover image and screenshot urls are wrong with Javbus

### ISSUE THREAD

**Issue by pnthach95** [jvlflame/Javinizer#354]
## Expected Behavior

Cover image from javbus should be loaded. Screenshot urls should be right.

## Current Behavior

Could not load cover, the cover url can be opened in new tab:
![image](https://user-images.githubusercontent.com/31266357/215292620-d69fb3e3-9055-4d43-97d2-7dfd60335e58.png)

Screenshot urls are wrong, example with code SKY-225:
![image](https://user-images.githubusercontent.com/31266357/215293652-e49100c9-ceef-44ee-8131-3101c2001ce2.png)

## Steps to Reproduce (for bugs)

- Check Javbus in Settings
- Start sort a file
- See result

## Your Environment
* Module version used: 2.5.10
* Operating System and PowerShell version: Windows 11 Home, PS 7.3.1.0

**Comment by seeyabye** [comment]
This issue is similar to (#324).

Unfortunately this one is related to Cloudflare.
At this time, this will be marked as **won't fix**
