### ISSUE TITLE
How to update to the 2.5.11

### ISSUE THREAD

**Issue by nova168168** [jvlflame/Javinizer#357]
I use the command "Javinizer -UpdateModule" , it said already have the latest version 2.5.10 
--------------------------------------------------------------------------------------------------------------
PS C:\Windows\System32> Javinizer -UpdateModule
WARNING: You already have the latest version of Javinizer! [2.5.10]
PS C:\Windows\System32> javinizer -v

Version      : 2.5.10
Prerelease   : alpha
Project      : https://github.com/jvlflame/Javinizer
License      : https://github.com/jvlflame/Javinizer/blob/master/LICENSE
ReleaseNotes : https://github.com/jvlflame/Javinizer/blob/master/.github/CHANGELOG.md
--------------------------------------------------------------------------------------------------------------

And I copied the 2.5.11 files to C:\Program Files\WindowsPowerShell\Modules\Javinizer\2.5.10 , it's work only one time.  After reboot the computer , Javinizer is not work again, I need to reinstall the Javinizer.

**Comment by gummykage** [comment]
Having the same issue.

**Comment by org0ne** [comment]
@jvlflame suggested this on the Discord support `Install-Module javinizer -RequiredVersion 2.5.11`

**Comment by Random-Ultra** [comment]
> @jvlflame suggested this on the Discord support `Install-Module javinizer -RequiredVersion 2.5.11`

This worked for me, Thank you

Also what is the discord address ? I didn't know there was a discord.

**Comment by org0ne** [comment]
@Random-Ultra https://discord.com/invite/Pds7xCpzpc.  Used to be easier to find when the documentation page link worked.  Now the only surviving docs are here (which has the link in them): https://jvlflame.gitbook.io/2.5.5/troubleshooting/frequently-asked-questions

**Comment by nova168168** [comment]
thx , the issue is fix !
