### ISSUE TITLE
finding nfo path error

### ISSUE THREAD

**Issue by berrysoda** [jvlflame/Javinizer#366]
I feel like it's probably some dumb formatting thing or something minor I'm overlooking... any ideas based off the error log?

## Expected Behavior
Sort

## Current Behavior
Not finding nfo path

## Steps to Reproduce (for bugs)
[2023-05-02T08:52:51][ERROR] [SSIS-623] [Set-JVMovie] Error occurred when creating nfo file [F:\Movies\Action Videos\Downloads\Sorted\Yumeno Aika - SSIS-623\Yumeno Aika - SSIS-623.nfo]: Could not find a part of the path 'F:\Movies\Action Videos\Downloads\Sorted\Yumeno Aika - SSIS-623\Yumeno Aika - SSIS-623.nfo'.

## Your Environment
* Module version used: 2.5.10
* Operating System and PowerShell version: 7.3.4

**Comment by seeyabye** [comment]
I need more info. How are you running this? If it's from CLI, can you write out the full command?

**Comment by berrysoda** [comment]
> I need more info. How are you running this? If it's from CLI, can you write out the full command?

I'm using the GUI. Is there a log I can check somewhere that'll give you what it runs? Should I just share my settings JSON?
I'm not an expert at all this, but I've been figuring out what I can and almost have it perfect. Any help is great.

**Comment by berrysoda** [comment]
> I need more info. How are you running this? If it's from CLI, can you write out the full command?

I'm using the GUI. Is there a log I can check somewhere that'll give you what it runs? Should I just share my settings JSON?
I'm not an expert at all this, but I've been figuring out what I can and almost have it perfect. Any help is great.

**Comment by seeyabye** [comment]
It would definitely be helpful if you could share it.

**Comment by berrysoda** [comment]
It looks like I've fixed it by turning "sort.renamefolderinplace" back to false
