### ISSUE TITLE
r18.dev not showing in Scraper list

### ISSUE THREAD

**Issue by RabidWolf** [jvlflame/Javinizer#367]
## Expected Behavior
r18.dev to show in scraper list. used Install-Module javinizer -RequiredVersion 2.5.12 to install.

## Current Behavior
As title

## Your Environment
* Module version used: 2.5.12
* Operating System and PowerShell version:7.1.3

**Comment by seeyabye** [comment]
Thanks. Will be fixed in 2.5.13.
