### ISSUE TITLE
Error When Downloading Actress Images

### ISSUE THREAD

**Issue by berrysoda** [jvlflame/Javinizer#370]
## Expected Behavior
Sort as normal

## Current Behavior
ERROR MESSAGE:
[2023-05-06T00:25:40][ERROR] [EBOD-945] [Set-JVMovie] Error occurred when creating actress image files: Exception calling "DownloadFile" with "2" argument(s): "Could not find file 'C:\Windows\system32\arioka_miu.jpg'."

SETTINGS:
{
  "throttlelimit": 3,
  "location.input": "F:\\Movies\\Action Videos\\Downloads\\Complete",
  "location.output": "F:\\Movies\\Action Videos\\Downloads\\Sort",
  "location.thumbcsv": "",
  "location.genrecsv": "",
  "location.uncensorcsv": "",
  "location.historycsv": "",
  "location.tagcsv": "",
  "location.log": "",
  "scraper.movie.aventertainment": false,
  "scraper.movie.aventertainmentja": false,
  "scraper.movie.r18dev": true,
  "scraper.movie.dmm": false,
  "scraper.movie.dmmja": true,
  "scraper.movie.jav321ja": false,
  "scraper.movie.javbus": false,
  "scraper.movie.javbusja": false,
  "scraper.movie.javbuszh": false,
  "scraper.movie.javdb": true,
  "scraper.movie.javdbzh": false,
  "scraper.movie.javlibrary": true,
  "scraper.movie.javlibraryja": false,
  "scraper.movie.javlibraryzh": false,
  "scraper.movie.mgstageja": false,
  "scraper.movie.tokyohot": false,
  "scraper.movie.tokyohotja": false,
  "scraper.movie.tokyohotzh": false,
  "scraper.option.dmm.scrapeactress": false,
  "scraper.option.idpreference": "id",
  "scraper.option.addmaleactors": false,
  "match.minimumfilesize": 0,
  "match.includedfileextension": [
    ".asf",
    ".avi",
    ".flv",
    ".m4v",
    ".mkv",
    ".mp4",
    ".mov",
    ".rmvb",
    ".wmv"
  ],
  "match.excludedfilestring": [
    "^.*-trailer*",
    "^.*-5\\."
  ],
  "match.regex": false,
  "match.regex.string": "([a-zA-Z|tT28]+-\\d+[zZ]?[eE]?)(?:-pt)?(\\d{1,2})?",
  "match.regex.idmatch": 1,
  "match.regex.ptmatch": 2,
  "sort.movetofolder": true,
  "sort.renamefile": true,
  "sort.renamefolderinplace": false,
  "sort.maxtitlelength": 100,
  "sort.movesubtitles": false,
  "sort.create.nfo": true,
  "sort.create.nfoperfile": true,
  "sort.download.actressimg": true,
  "sort.download.thumbimg": true,
  "sort.download.posterimg": true,
  "sort.download.screenshotimg": true,
  "sort.download.trailervid": false,
  "sort.download.timeoutduration": 100000,
  "sort.format.groupactress": true,
  "sort.format.delimiter": ", ",
  "sort.format.file": " <TITLE>",
  "sort.format.folder": " <TITLE>",
  "sort.format.outputfolder": "",
  "sort.format.posterimg": "folder",
  "sort.format.thumbimg": "fanart",
  "sort.format.trailervid": "",
  "sort.format.nfo": " <TITLE>",
  "sort.format.screenshotimg": "fanart",
  "sort.format.screenshotimg.padding": 1,
  "sort.format.screenshotfolder": "extrafanart",
  "sort.format.actressimgfolder": ".actors",
  "sort.metadata.nfo.addaliases": false,
  "sort.metadata.nfo.mediainfo": true,
  "sort.metadata.nfo.addgenericrole": true,
  "sort.metadata.nfo.altnamerole": false,
  "sort.metadata.nfo.translate": false,
  "sort.metadata.nfo.translate.module": "googletrans",
  "sort.metadata.nfo.translate.field": "description",
  "sort.metadata.nfo.translate.language": "en",
  "sort.metadata.nfo.translate.deeplapikey": "",
  "sort.metadata.nfo.translate.keeporiginaldescription": false,
  "sort.metadata.nfo.displayname": "<ACTORS> - <ID>",
  "sort.metadata.nfo.firstnameorder": true,
  "sort.metadata.nfo.actresslanguageja": false,
  "sort.metadata.nfo.unknownactress": true,
  "sort.metadata.nfo.originalpath": true,
  "sort.metadata.nfo.actressastag": false,
  "sort.metadata.nfo.preferactressalias": false,
  "sort.metadata.nfo.format.tag": "",
  "sort.metadata.nfo.format.tagline": "",
  "sort.metadata.nfo.format.credits": [],
  "sort.metadata.thumbcsv": true,
  "sort.metadata.thumbcsv.autoadd": true,
  "sort.metadata.thumbcsv.convertalias": true,
  "sort.metadata.genrecsv": false,
  "sort.metadata.genrecsv.autoadd": false,
  "sort.metadata.tagcsv": false,
  "sort.metadata.tagcsv.autoadd": false,
  "sort.metadata.genre.ignore": [
    "^Featured Actress",
    "^Hi-Def",
    ".*sale.*",
    ".*mosaic.*"
  ],
  "sort.metadata.requiredfield": [
    "id",
    "coverurl",
    "genre",
    "maker",
    "releaseDate"
  ],
  "sort.metadata.priority.actress": [
    "javlibrary",
    "r18dev",
    "javdb",
    "dmmja"
  ],
  "sort.metadata.priority.alternatetitle": "",
  "sort.metadata.priority.coverurl": [
    "javlibrary",
    "r18dev",
    "javdb",
    "dmmja"
  ],
  "sort.metadata.priority.description": "",
  "sort.metadata.priority.director": [
    "javlibrary",
    "r18dev",
    "javdb",
    "dmmja"
  ],
  "sort.metadata.priority.genre": "",
  "sort.metadata.priority.id": [
    "javlibrary",
    "r18dev",
    "javdb",
    "dmmja"
  ],
  "sort.metadata.priority.contentid": [
    "r18dev",
    "dmmja"
  ],
  "sort.metadata.priority.label": [
    "javlibrary",
    "r18dev",
    "javdb",
    "dmmja"
  ],
  "sort.metadata.priority.maker": [
    "javlibrary",
    "r18dev",
    "javdb",
    "dmmja"
  ],
  "sort.metadata.priority.releasedate": [
    "javlibrary",
    "r18dev",
    "javdb",
    "dmmja"
  ],
  "sort.metadata.priority.rating": "",
  "sort.metadata.priority.runtime": [
    "javlibrary",
    "r18dev",
    "javdb",
    "dmmja"
  ],
  "sort.metadata.priority.series": [
    "javlibrary",
    "r18dev",
    "javdb",
    "dmmja"
  ],
  "sort.metadata.priority.screenshoturl": [
    "javlibrary",
    "r18dev",
    "javdb",
    "dmmja"
  ],
  "sort.metadata.priority.title": "",
  "sort.metadata.priority.trailerurl": "",
  "emby.url": "http://192.168.0.1:8096",
  "emby.apikey": "",
  "javlibrary.baseurl": "http://www.javlibrary.com",
  "javlibrary.browser.useragent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0",
  "javlibrary.cookie.cf_chl_2": "",
  "javlibrary.cookie.cf_chl_prog": "",
  "javlibrary.cookie.cf_clearance": "",
  "javlibrary.cookie.session": "[REDACTED]",
  "javlibrary.cookie.userid": "[REDACTED]",
  "javdb.cookie.session": "[REDACTED]",
  "proxy.enabled": false,
  "proxy.host": "",
  "proxy.username": "",
  "proxy.password": "",
  "web.favorites.genre": [],
  "web.favorites.tag": [],
  "web.sort.recurse": false,
  "web.sort.strict": false,
  "web.sort.interactive": true,
  "web.sort.update": false,
  "web.sort.force": false,
  "web.sort.preview": false,
  "web.sort.recursedepth": 0,
  "web.sort.confirm": false,
  "web.sort.manualsearch.aventertainment": false,
  "web.sort.manualsearch.aventertainmentja": false,
  "web.sort.manualsearch.dmm": false,
  "web.sort.manualsearch.dmmja": true,
  "web.sort.manualsearch.jav321ja": false,
  "web.sort.manualsearch.javbus": false,
  "web.sort.manualsearch.javbusja": false,
  "web.sort.manualsearch.javbuszh": false,
  "web.sort.manualsearch.javdb": false,
  "web.sort.manualsearch.javdbzh": false,
  "web.sort.manualsearch.javlibrary": true,
  "web.sort.manualsearch.javlibraryja": false,
  "web.sort.manualsearch.javlibraryzh": false,
  "web.sort.manualsearch.mgstageja": false,
  "web.sort.manualsearch.r18dev": true,
  "web.sort.manualsearch.tokyohot": true,
  "web.sort.manualsearch.tokyohotja": true,
  "web.sort.manualsearch.tokyohotzh": true,
  "web.theme": "dark",
  "admin.log": true,
  "admin.log.level": "info",
  "admin.updates.check": true
}

## Your Environment
* Module version used
* Operating System and PowerShell version

**Comment by seeyabye** [comment]
Will be fixed in `2.4.14`.
