### ISSUE TITLE
-Multi is causing renaming issues

### ISSUE THREAD

**Issue by fluxtheory** [jvlflame/Javinizer#39]
Hey Boss,

Just noticed that some of the videos that were left behind after a ```-Multi``` sort are actually part two's and three's of already moved JAVs. Running Javinizer again over these files results in :

```
Move-Item: C:\Users\Bailey\Documents\PowerShell\Modules\Javinizer\1.4.2\Private\
Set-JavMovie.ps1:91
Line |
  91 |  . tion Stop | Move-Item -Destination $folderPath -Force:$Force -ErrorAc
.
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot create a file when that file already exists.

```
Unfortunately I cannot reproduce this unless I go back and rename the moved files by hand.

**Comment by jvlflame** [comment]
You will receive that error when sorting multipart movies using `-Multi`. Unfortunately I don't have a good way of suppressing that error on successful sorts, but it should be working properly as long as the files are named properly. 

What is the current naming scheme of your multipart videos that you're trying to sort. Do you have an example?

**Comment by fluxtheory** [comment]
They're a mixed bag since im getting them from public trackers. But they usually follow one of the following schema:
ID-001A
ID-001CD1
ID-001_1

**Comment by jeffvli** [comment]
Unfortunately the ID-001CD1 format isn't supported. The other two should be though.

```
# Naming schemes  - Example filename
------------------------------------
ID-###[a-iA-I]    - ID-069A, ID-069B
ID-###-[a-iA-I]   - ID-069-a, ID-069-b
ID-###-\d         - ID-069-1, ID-069-2
ID-###-0\d        - ID-069-01, ID-069-02
ID-###-00\d       - ID-069-001, ID-069-003
ID-###-pt\d       - ID-069-pt1, ID-069-pt2
ID-### - pt\d     - ID-069 - pt1, ID-069 - pt2
ID-###-part\d     - ID-069-part1, ID-069-part2
ID-### - part\d   - ID-069 - part1, ID-069 - part2
ID-###_\d         - ID-069_1, ID-069_2
ID-###_0\d        - ID-069_01, ID-069_02
ID-###-cd\d       - ID-069-cd1, ID-069-cd2
```

**Comment by fluxtheory** [comment]
Ah, I didnt see the dash in ID-069-cd1. My mistake.
