### ISSUE TITLE
ID-009

### ISSUE THREAD

**Issue by Yukkun** [jvlflame/Javinizer#42]
I really like how this works, but there is one big issue. Which is the JAV with ID of ID-009.
According to JAVLibrary there is 5 JAV's with that ID, 
In future when this happens, maybe make the script ask which one is the right one?

**Comment by jvlflame** [comment]
Hey Yukkun,

I'm not sure if adding a prompt to match single videos would be feasible given how Javinizer currently runs with `-Multi`. I can take a look into it and see if I can maybe implement it in single sort mode.

**Comment by jvlflame** [comment]
Unfortunately with the direction I have taken Javinizer I don't think an interactive single-sort mode is in the works, at least not within the commandline. With the 2.x.x release, Javinizer now always run with multi-sort mode, but has improved functionality for sorting single files with direct URLs using the `-Url` parameter.
