### ISSUE TITLE
Issue with getting posters

### ISSUE THREAD

**Issue by electro309** [jvlflame/Javinizer#43]
i have set **_download-poster-img=True_** but it doesn't seem to be working as i understand it crops the "fanart" image but it is not doing that any fixes on this problem? i have everything installed and updated to the latest version

**Comment by jvlflame** [comment]
The dependency there should be the Python `pillow` module.
Can you try running the following and check if you receive output.
```
PS> pip show pillow

Name: Pillow
Version: 7.0.0
Summary: Python Imaging Library (Fork)
Home-page: https://python-pillow.org
Author: Alex Clark (PIL Fork Author)
Author-email: aclark@python-pillow.org
License: HPND
Location: c:\python38\lib\site-packages
Requires:
Required-by:
```

**Comment by jvlflame** [comment]
Are you getting any errors in the console, or are the poster images just not showing up after the movie has been sorted?

**Comment by electro309** [comment]
No errors in the console just that the poster images are not showing up. my settings are all still the same from when i downloaded the file just changed the directories.

**Comment by jvlflame** [comment]
Can you share your settings file and the full command you're using to run Javinizer in the console?

**Comment by electro309** [comment]
im using the command PS> Javinizer -apply


> [Main]
> scrape-r18=True
> scrape-r18zh=False
> scrape-dmm=True
> scrape-javlibrary=True
> scrape-javlibraryja=False
> scrape-javlibraryzh=False
> 
> [General]
> Maximum number of threads to sort with if parameter '-Multi' is applied (range 1-15)
> multi-sort-throttle-limit=10
> move-to-folder=True
> rename-file=True
> Available tags for file/folder rename string
> <ID> <TITLE> <STUDIO> <YEAR> <RELEASEDATE> <RUNTIME> <ACTORS> <LABEL> <ORIGINALTITLE> <SET>
> I do not recommend changing the filename other than <ID> as you may have to manually rename files if you need to re-sort them at a later date
> rename-file-string="<ID>"
> rename-folder-string="<ID> [<STUDIO>] - <TITLE> (<YEAR>)"
> cms-displayname-string="[<ID>] <TITLE>"
> actors-name-delimiter=", "
> poster-file-string="folder"
> thumbnail-file-string="fanart"
> trailer-file-string="<ID>-trailer"
> nfo-file-string will only apply if create-nfo-per-file=False
> nfo-file-string="<ID>"
> screenshot-folder-string="extrafanart"
> screenshot-img-string="fanart"
> actorimg-folder-string=".actors"
> Max-title-length will limit the length of your <TITLE> string
> max-title-length=100
> This option will allow Javinizer to ignore video files below a certain size (in MB)
> minimum-filesize-to-sort=0
> included-file-extensions=asf,avi,flv,m4v,mkv,mp4,mov,rmvb
> excluded-file-strings=*-trailer
> 
> [Metadata]
> General metadata options
> If you use Emby/Jellyfin, create-nfo-per-file is required (nfo is required to have the same filename)
> create-nfo=True
> create-nfo-per-file=True
> download-thumb-img=True
> Download-poster-img requires download-thumb-img to be true
> download-poster-img=True
> download-screenshot-img=False
> download-trailer-vid=False
> download-actress-img=False
> translate-description=True
> View language codes: https://developers.google.com/admin-sdk/directory/v1/languages
> translate-description-language=en
> Use this if you want R18 series names to be set as clickable tag in Emby. If you primarily use Plex, you can set this to false.
> add-series-as-tag=False
> True = FirstName LastName / False = LastName FirstName
> first-last-name-order=False
> This option will convert actress names matching 'Alias' in r18-thumbs.csv to their original full name
> convert-alias-to-originalname=True
> This will convert all JavLibrary genres to their R18 counterparts to keep a consistent genre schema. If you want to use JAVLibrary genres, set this to false.
> normalize-genres=True
> List of genres to ignore in comma separated format (no spaces)
> ignored-genres="Featured Actress,Hi-Def"
> 
> Metadata scraping priorities
> Javinizer will fail the sort on a movie if any fields listed in required-metadata-fields is null
> required-metadata-fields=coverurl,genre,id,maker,title,releasedate,releaseyear
> actress-priority=r18,javlibrary
> actressthumburl-priority=r18
> alternatetitle-priority=dmm
> coverurl-priority=r18,dmm,javlibrary
> description-priority=dmm
> director-priority=r18,javlibrary
> genre-priority=r18,javlibrary
> id-priority=r18,javlibrary
> label-priority=r18,javlibrary
> maker-priority=r18,javlibrary
> rating-priority=dmm
> ratingcount-priority=dmm
> releasedate-priority=r18,javlibrary,dmm
> releaseyear-priority=r18,javlibrary,dmm
> runtime-priority=r18,javlibrary,dmm
> series-priority=r18
> screenshoturl-priority=r18,dmm
> title-priority=r18,javlibrary
> trailerurl-priority=r18
> 
> [Locations]
> These locations will only be used if you are running Javinizer with the -Apply parameter
> input-path="H:\WebRip\Asian\Sorted\Unsorted"
> output-path="H:\WebRip\Asian\Sorted"
> 
> [Emby/Jellyfin]
> You can create an Emby/Jellyfin API key under Dashboard -> Advanced -> Security
> server-url=192.168.0.1:8096
> server-api-key=
> 
> [Other]
> Log path will default to the javinizer.log file inside your module directory
> log-path=
> check-updates=True
> verbose-shell-output=True
> debug-shell-output=False
>

**Comment by jvlflame** [comment]
Can you set `debug-shell-output=` to True and run a sort on a single movie.

Copy the shell output for me, thanks.

**Comment by electro309** [comment]
Alright this is what i got back
> [2020-06-04T05:34:31][Javinizer] Function started
> DEBUG: [2020-06-04T05:34:31][Javinizer] R18: [True]; R18Zh: [False] Dmm: [True]; Javlibrary: [True]; JavlibraryZh: [False]; JavlibraryJa: [False]
> DEBUG: [2020-06-04T05:34:31][Javinizer] Attempting to read file(s) from path: [H:\WebRip\Asian\Sorted\Unsorted]
> DEBUG: [2020-06-04T05:34:31][Convert-JavTitle] Function started
> DEBUG: [2020-06-04T05:34:31][Get-VideoFile] Function started
> DEBUG: [2020-06-04T05:34:31][Convert-CommaDelimitedString] Begin string: [*-trailer], End string [*-trailer]
> DEBUG: [2020-06-04T05:34:31][Convert-CommaDelimitedString] Begin string: [asf,avi,flv,m4v,mkv,mp4,mov,rmvb], End string [asf avi flv m4v mkv mp4 mov rmvb]
> DEBUG: [2020-06-04T05:34:31][Get-VideoFile] Function ended
> DEBUG: [2020-06-04T05:34:31][Convert-JavTitle] Match 11
> DEBUG: [2020-06-04T05:34:31][Convert-JavTitle] Function ended
> DEBUG: [2020-06-04T05:34:31][Javinizer] Detected path: [H:\WebRip\Asian\Sorted\Unsorted] as directory and destinationpath: [H:\WebRip\Asian\Sorted] as directory
> [2020-06-04T05:34:31][Javinizer] Sort path: [H:\WebRip\Asian\Sorted\Unsorted]
> [2020-06-04T05:34:31][Javinizer] Destination path: [H:\WebRip\Asian\Sorted]
> [2020-06-04T05:34:31][Javinizer] Included file ext: [asf,avi,flv,m4v,mkv,mp4,mov,rmvb]
> [2020-06-04T05:34:31][Javinizer] Excluded file strings: [*-trailer]
> [2020-06-04T05:34:31][Javinizer] (1 of 1) Sorting [SSNI-742.mp4]
> DEBUG: [2020-06-04T05:34:31][Get-AggregatedDataObject] Function started
> DEBUG: [2020-06-04T05:34:31][Get-MetadataPriority] Priority type loaded: [actress]; Priority setting: [r18 javlibrary]
> DEBUG: [2020-06-04T05:34:31][Get-MetadataPriority] Priority type loaded: [actressthumburl]; Priority setting: [r18]
> DEBUG: [2020-06-04T05:34:31][Get-MetadataPriority] Priority type loaded: [alternatetitle]; Priority setting: [dmm]
> DEBUG: [2020-06-04T05:34:31][Get-MetadataPriority] Priority type loaded: [coverurl]; Priority setting: [r18 dmm javlibrary]
> DEBUG: [2020-06-04T05:34:31][Get-MetadataPriority] Priority type loaded: [description]; Priority setting: [dmm]
> DEBUG: [2020-06-04T05:34:31][Get-MetadataPriority] Priority type loaded: [director]; Priority setting: [r18 javlibrary]
> DEBUG: [2020-06-04T05:34:31][Get-MetadataPriority] Priority type loaded: [genre]; Priority setting: [r18 javlibrary]
> DEBUG: [2020-06-04T05:34:31][Get-MetadataPriority] Priority type loaded: [id]; Priority setting: [r18 javlibrary]
> DEBUG: [2020-06-04T05:34:31][Get-MetadataPriority] Priority type loaded: [label]; Priority setting: [r18 javlibrary]
> DEBUG: [2020-06-04T05:34:31][Get-MetadataPriority] Priority type loaded: [runtime]; Priority setting: [r18 javlibrary dmm]
> DEBUG: [2020-06-04T05:34:31][Get-MetadataPriority] Priority type loaded: [maker]; Priority setting: [r18 javlibrary]
> DEBUG: [2020-06-04T05:34:31][Get-MetadataPriority] Priority type loaded: [rating]; Priority setting: [dmm]
> DEBUG: [2020-06-04T05:34:31][Get-MetadataPriority] Priority type loaded: [ratingcount]; Priority setting: [dmm]
> DEBUG: [2020-06-04T05:34:31][Get-MetadataPriority] Priority type loaded: [releasedate]; Priority setting: [r18 javlibrary dmm]
> DEBUG: [2020-06-04T05:34:31][Get-MetadataPriority] Priority type loaded: [releaseyear]; Priority setting: [r18 javlibrary dmm]
> DEBUG: [2020-06-04T05:34:31][Get-MetadataPriority] Priority type loaded: [series]; Priority setting: [r18]
> DEBUG: [2020-06-04T05:34:31][Get-MetadataPriority] Priority type loaded: [screenshoturl]; Priority setting: [r18 dmm]
> DEBUG: [2020-06-04T05:34:31][Get-MetadataPriority] Priority type loaded: [title]; Priority setting: [r18 javlibrary]
> DEBUG: [2020-06-04T05:34:31][Get-MetadataPriority] Priority type loaded: [trailerurl]; Priority setting: [r18]
> DEBUG: [2020-06-04T05:34:31][Get-AggregatedDataObject] Type: [FileDetails]
> DEBUG: [2020-06-04T05:34:31][Get-R18DataObject] Function started
> DEBUG: [2020-06-04T05:34:31][Get-R18Url] Function started
> DEBUG: [2020-06-04T05:34:31][Get-R18Url] Performing [GET] on Uri [https://www.r18.com/common/search/searchword=SSNI-742/]
> DEBUG: [2020-06-04T05:34:32][Get-R18Url] Searching [1] of [1] results for [SSNI-742]
> DEBUG: [2020-06-04T05:34:32][Get-R18Url] Performing [GET] on Uri [https://www.r18.com/videos/vod/movies/detail/-/id=ssni00742/?i3_ref=search&amp;i3_ord=1]
> DEBUG: [2020-06-04T05:34:34][Get-R18Url] Result [1] is [SSNI-742]
> DEBUG: [2020-06-04T05:34:34][Get-R18Url] Function ended
> DEBUG: [2020-06-04T05:34:34][Get-R18DataObject] Performing GET on Uri [https://www.r18.com/videos/vod/movies/detail/-/id=ssni00742/?i3_ref=search&amp;i3_ord=1]
> DEBUG: Trailer Url is https://awscc3001.r18.com/litevideo/freepv/s/ssn/ssni00742/ssni00742_sm_w.mp4 https://awscc3001.r18.com/litevideo/freepv/s/ssn/ssni00742/ssni00742_dm_w.mp4 https://awscc3001.r18.com/litevideo/freepv/s/ssn/ssni00742/ssni00742_dmb_w.mp4
> DEBUG: [2020-06-04T05:34:34][Get-R18DataObject] R18 data object:
> DEBUG:
> Source          : r18
> Url             : https://www.r18.com/videos/vod/movies/detail/-/id=ssni00742/?i3_ref=search&amp;i3_ord=1
> ContentId       : ssni00742
> Id              : SSNI-742
> Title           : Fresh Face No. 1 Style Izuna Maki 18 Years Old Porn Debut
> Description     :
> Date            : 2020-03-14
> Year            : 2020
> Runtime         : 201
> Director        : Mon C
> Maker           : S1 NO.1 STYLE
> Label           : S1 NO.1 STYLE
> Series          : New Face NO.1 STYLE
> Rating          :
> Actress         : {Izuna Maki}
> Genre           : {Beautiful Girl, Slender, Shaved Pussy, Featured Actress…}
> ActressThumbUrl : {https://pics.r18.com/mono/actjpgs/maki_izuna.jpg}
> CoverUrl        : https://pics.r18.com/digital/video/ssni00742/ssni00742pl.jpg
> ScreenshotUrl   : {https://pics.r18.com/digital/video/ssni00742/ssni00742jp-1.jpg, https://pics.r18.com/digital/video/ssni00742/ssni00742jp-2.jpg, https://pics.r18.com/digital/video/ssni00742/ssni00742jp-3.jpg, https://pics.r18.com/digital/video/ssni00742/ssni00742jp-4.jpg…}
> TrailerUrl      : {https://awscc3001.r18.com/litevideo/freepv/s/ssn/ssni00742/ssni00742_sm_w.mp4, https://awscc3001.r18.com/litevideo/freepv/s/ssn/ssni00742/ssni00742_dm_w.mp4, https://awscc3001.r18.com/litevideo/freepv/s/ssn/ssni00742/ssni00742_dmb_w.mp4}
> 
> 
> 
> DEBUG: [2020-06-04T05:34:35][Get-R18DataObject] Function ended
> DEBUG: [2020-06-04T05:34:35][Get-DmmDataObject] Function started
> DEBUG: [2020-06-04T05:34:35][Get-R18Url] Function started
> DEBUG: [2020-06-04T05:34:35][Get-R18Url] Performing [GET] on Uri [https://www.r18.com/common/search/searchword=SSNI-742/]
> DEBUG: [2020-06-04T05:34:35][Get-R18Url] Searching [1] of [1] results for [SSNI-742]
> DEBUG: [2020-06-04T05:34:35][Get-R18Url] Performing [GET] on Uri [https://www.r18.com/videos/vod/movies/detail/-/id=ssni00742/?i3_ref=search&amp;i3_ord=1]
> DEBUG: [2020-06-04T05:34:36][Get-R18Url] Result [1] is [SSNI-742]
> DEBUG: [2020-06-04T05:34:36][Get-R18Url] Function ended
> DEBUG: [2020-06-04T05:34:36][Get-DmmDataObject] R18 ID is: ssni00742
> DEBUG: [2020-06-04T05:34:36][Get-DmmDataObject] DMM url is: https://www.dmm.co.jp/digital/videoa/-/detail/=/cid=ssni00742
> DEBUG: [2020-06-04T05:34:36][Get-DmmDataObject] Performing [GET] on Uri [https://www.dmm.co.jp/digital/videoa/-/detail/=/cid=ssni00742]
> DEBUG: [2020-06-04T05:34:38][Get-DmmDataObject] DMM data object:
> DEBUG:
> Source        : dmm
> Url           : https://www.dmm.co.jp/digital/videoa/-/detail/=/cid=ssni00742
> ContentId     : ssni00742
> Title         : 新人NO.1STYLE 槙いずな 18歳 AVデビュー
> Description   : 控えめに言って最高―エスワン新世代アイドル誕生！大人と子供の間、18歳の奇跡の美少女‘槙いずな’鮮烈デビュー 。身長148cmウエスト55cm小さなカラダに圧倒的なクビレ。どこまでも透き通る白い肌。敏感でエロ過ぎるスレンダーBODY。それはま るで、今にも消えてしまいそうな儚い笑顔。消えてしまいそうで、でもなぜか頭から離れない。ただひたすらに儚すぎる18歳の美少女、決意のAVデビュー！
> Date          : 2020-03-14
> Year          : 2020
> Runtime       : 201
> Director      : 紋℃
> Maker         : エスワン ナンバーワンスタイル
> Label         : S1 NO.1 STYLE
> Series        : 新人NO.1 STYLE
> Rating        : 8
> RatingCount   : 38
> Actress       : 槙いずな
> Genre         : {ハイビジョン, 独占配信, ギリモザ, デビュー作品…}
> CoverUrl      : https://pics.dmm.co.jp/digital/video/ssni00742/ssni00742pl.jpg
> ScreenshotUrl : {https://pics.dmm.co.jp/digital/video/ssni00742/ssni00742jp-1.jpg, https://pics.dmm.co.jp/digital/video/ssni00742/ssni00742jp-2.jpg, https://pics.dmm.co.jp/digital/video/ssni00742/ssni00742jp-3.jpg, https://pics.dmm.co.jp/digital/video/ssni00742/ssni00742jp-4.jpg…}
> 
> 
> 
> DEBUG: [2020-06-04T05:34:38][Get-DmmDataObject] Function ended
> DEBUG: [2020-06-04T05:34:38][Get-JavlibraryDataObject] Function started
> DEBUG: [2020-06-04T05:34:38][Get-JavlibraryUrl] Function started
> DEBUG: [2020-06-04T05:34:38][Get-JavlibraryUrl] Performing [GET] on Uri [http://www.javlibrary.com/en/vl_searchbyid.php?keyword=SSNI-742] with Session: [] and UserAgent: []
> DEBUG: [2020-06-04T05:34:38][Get-JavlibraryUrl] Session to JAVLibrary is unsuccessful, attempting to start a new session with Cloudflare
> DEBUG: [2020-06-04T05:34:38][New-CloudflareSession] Function started
> VERBOSE: [2020-06-04T05:34:38][Get-JavlibraryUrl] Search [SSNI-742] not matched on JAVLibrary
> DEBUG: [2020-06-04T05:34:38][Get-JavlibraryUrl] Function ended
> DEBUG: [2020-06-04T05:34:38][Get-JavlibraryDataObject] JAVLibrary data object:
> DEBUG:
> DEBUG: [2020-06-04T05:34:38][Get-JavlibraryDataObject] Function ended
> DEBUG: [2020-06-04T05:34:38][Get-TranslatedString] Function started
> DEBUG: [2020-06-04T05:34:39][Get-TranslatedString] Function ended
> DEBUG: [2020-06-04T05:34:39][Convert-CommaDelimitedString] Begin string: [Featured Actress,Hi-Def], End string [Featured Actress Hi-Def]
> DEBUG: [2020-06-04T05:34:39][Get-AggregatedDataObject] Ignored genres: [Featured Actress Hi-Def]
> DEBUG: [2020-06-04T05:34:39][Get-NewFileDirName] Function started
> DEBUG: [2020-06-04T05:34:39][Get-NewFileDirName] Function ended
> DEBUG:
> Search               : SSNI-742
> Id                   : SSNI-742
> Title                : Fresh Face No. 1 Style Izuna Maki 18 Years Old Porn Debut
> AlternateTitle       : 新人NO.1STYLE 槙いずな 18歳 AVデビュー
> Description          : 控えめに言って最高―エスワン新世代アイドル誕生！大人と子供の間、18歳の奇跡の美少女‘槙いずな’鮮烈デビュー。身長148cmウエスト55cm小さなカラダに圧倒的なクビレ。どこまでも透き通る白い肌。敏感でエロ過ぎるスレンダーBODY。そ れはまるで、今にも消えてしまいそうな儚い笑顔。消えてしまいそうで、でもなぜか頭から離れない。ただひたすらに儚すぎる18歳の美少女、決意のAVデビュー！
> ReleaseDate          : 2020-03-14
> ReleaseYear          : 2020
> Runtime              : 201
> Director             : Mon C
> Maker                : S1 NO.1 STYLE
> Label                : S1 NO.1 STYLE
> Series               : New Face NO.1 STYLE
> Rating               : 8
> RatingCount          : 38
> Actress              : {Maki Izuna}
> Genre                : {Beautiful Girl, Slender, Shaved Pussy, Debut…}
> ActressThumbUrl      : {https://pics.r18.com/mono/actjpgs/maki_izuna.jpg}
> CoverUrl             : https://pics.r18.com/digital/video/ssni00742/ssni00742pl.jpg
> ScreenshotUrl        : {https://pics.r18.com/digital/video/ssni00742/ssni00742jp-1.jpg, https://pics.r18.com/digital/video/ssni00742/ssni00742jp-2.jpg, https://pics.r18.com/digital/video/ssni00742/ssni00742jp-3.jpg, https://pics.r18.com/digital/video/ssni00742/ssni00742jp-4.jpg…}
> TrailerUrl           : {https://awscc3001.r18.com/litevideo/freepv/s/ssn/ssni00742/ssni00742_dmb_w.mp4}
> DisplayName          : [SSNI-742] Fresh Face No. 1 Style Izuna Maki 18 Years Old Porn Debut
> FolderName           : SSNI-742 [S1 NO.1 STYLE] - Fresh Face No. 1 Style Izuna Maki 18 Years Old Porn Debut (2020)
> ScreenshotFolderName : extrafanart
> ScreenshotImgName    : fanart
> ActorImgFolderName   : .actors
> FileName             : SSNI-742
> PosterName           : folder
> ThumbnailName        : fanart
> TrailerName          : SSNI-742-trailer
> NfoName              : SSNI-742
> OriginalFileName     : SSNI-742.mp4
> OriginalBaseName     : SSNI-742
> OriginalDirectory    : H:\WebRip\Asian\Sorted\Unsorted
> OriginalFullName     : H:\WebRip\Asian\Sorted\Unsorted\SSNI-742.mp4
> PartNumber           :
> 
> 
> 
> DEBUG: [2020-06-04T05:34:39][Get-AggregatedDataObject] Function ended
> DEBUG: [2020-06-04T05:34:39][Set-JavMovie] Function started
> DEBUG: [2020-06-04T05:34:39][Set-JavMovie] Crop path: [C:\Users\matt\Documents\PowerShell\Modules\Javinizer\1.4.2\crop.py]
> DEBUG: [2020-06-04T05:34:39][Set-JavMovie] Folder path: [H:\WebRip\Asian\Sorted\SSNI-742 [S1 NO.1 STYLE] - Fresh Face No. 1 Style Izuna Maki 18 Years Old Porn Debut (2020)]
> DEBUG: [2020-06-04T05:34:39][Set-JavMovie] Nfo path: [H:\WebRip\Asian\Sorted\SSNI-742 [S1 NO.1 STYLE] - Fresh Face No. 1 Style Izuna Maki 18 Years Old Porn Debut (2020)\SSNI-742.nfo]
> DEBUG: [2020-06-04T05:34:39][Set-JavMovie] Cover path: [H:\WebRip\Asian\Sorted\SSNI-742 [S1 NO.1 STYLE] - Fresh Face No. 1 Style Izuna Maki 18 Years Old Porn Debut (2020)\fanart.jpg]
> DEBUG: [2020-06-04T05:34:39][Set-JavMovie] Poster path: [H:\WebRip\Asian\Sorted\SSNI-742 [S1 NO.1 STYLE] - Fresh Face No. 1 Style Izuna Maki 18 Years Old Porn Debut (2020)\folder.jpg]
> DEBUG: [2020-06-04T05:34:39][Set-JavMovie] Screenshot path: [H:\WebRip\Asian\Sorted\SSNI-742 [S1 NO.1 STYLE] - Fresh Face No. 1 Style Izuna Maki 18 Years Old Porn Debut (2020)\extrafanart]
> DEBUG: [2020-06-04T05:34:39][Set-JavMovie] Trailer path: [H:\WebRip\Asian\Sorted\SSNI-742 [S1 NO.1 STYLE] - Fresh Face No. 1 Style Izuna Maki 18 Years Old Porn Debut (2020)\SSNI-742-trailer.mp4]
> DEBUG: [2020-06-04T05:34:39][Test-RequiredMetadata] Function started
> DEBUG: [2020-06-04T05:34:39][Convert-CommaDelimitedString] Begin string: [coverurl,genre,id,maker,title,releasedate,releaseyear], End string [coverurl genre id maker title releasedate releaseyear]
> DEBUG: [2020-06-04T05:34:39][Test-RequiredMetadata] Function ended
> DEBUG: [2020-06-04T05:34:39][Get-MetadataNfo] NFO String:
>         <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
> <movie>
>     <title>[SSNI-742] Fresh Face No. 1 Style Izuna Maki 18 Years Old Porn Debut</title>
>     <originaltitle>新人NO.1STYLE 槙いずな 18歳 AVデビュー</originaltitle>
>     <id>SSNI-742</id>
>     <releasedate>2020-03-14</releasedate>
>     <year>2020</year>
>     <director>Mon C</director>
>     <studio>S1 NO.1 STYLE</studio>
>     <rating>8</rating>
>     <votes>38</votes>
>     <plot>控えめに言って最高―エスワン新世代アイドル誕生！大人と子供の間、18歳の奇跡の美少女‘槙いずな’鮮烈デビュー。身長148cmウエスト55cm小さなカラダに圧倒的なクビレ。どこまでも透き通る白い肌。敏感でエロ過ぎるスレンダーBODY。それはまるで、今にも消えてしまいそうな儚い笑顔。消えてしまいそうで、でもなぜか頭から離れない。ただひたすらに儚すぎる18歳の美少女、決意のAVデビュー！</plot>
>     <runtime>201</runtime>
>     <trailer>https://awscc3001.r18.com/litevideo/freepv/s/ssn/ssni00742/ssni00742_dmb_w.mp4</trailer>
>     <mpaa>XXX</mpaa>
>     <set>New Face NO.1 STYLE</set>
>     <genre>Beautiful Girl</genre>
>     <genre>Slender</genre>
>     <genre>Shaved Pussy</genre>
>     <genre>Debut</genre>
>     <genre>Minimal Mosaic</genre>
>     <actor>
>         <name>Maki Izuna</name>
>         <thumb>https://pics.r18.com/mono/actjpgs/maki_izuna.jpg</thumb>
>         <role>Actress</role>
>     </actor>
> </movie>
> DEBUG: [2020-06-04T05:34:39][Set-JavMovie] Function ended

**Comment by jvlflame** [comment]
Strange, it doesn't seem to be erroring.

I still think it has to do with the python Pillow module not working properly. I would say to try completely reinstalling Python on your computer.

1. Uninstall all Python versions
2. Reboot
3. Download and install [Python Windows x86-64 executable installer](https://www.python.org/downloads/windows/)
4. Re-install python modules with `pip install` -> cloudscraper, pillow, googletrans
5. Reboot
6. Try again

**Comment by electro309** [comment]
Alright cool, ill try that. Thanks for your speedy replies!

**Comment by electro309** [comment]
Did what you said but it still isn't working what i did was
 pip uninstall -> cloudscraper, pillow, googletrans and reinstalled python

**Comment by electro309** [comment]
> PS C:\WINDOWS\system32> C:\> python
> C:\> : The term 'C:\>' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> + C:\> python
> + ~~~~
> + CategoryInfo          : ObjectNotFound: (C:\>:String) [], CommandNotFoundException
> + FullyQualifiedErrorId : CommandNotFoundException

**Comment by electro309** [comment]
it opened the microsoft store for python 3.8 but i already have it installed from the website itself

**Comment by jvlflame** [comment]
Great, seems it was a PATH issue!
