### ISSUE TITLE
Folder path length limitations

### ISSUE THREAD

**Issue by xblizzy** [jvlflame/Javinizer#44]
As the title states, a lot of my files when trying to use Javinizer has a folder path length limitation. I've changed it in the settings to allow higher amounts of characters in renaming but it may just be the file name and not the folder name. I don't think there's a setting to change that unless I cut out the title completely when creating folders for each video. Is there a command or any specific setting for me to change to allow longer names for folders?

Some files won't allow the renaming as they have between 220-400+ characters but folders can be named with way more characters than that.

![skip](https://user-images.githubusercontent.com/66752514/84318634-bcac0900-ab3c-11ea-896f-1a03d255f5c1.PNG)

**Comment by jvlflame** [comment]
Hey there.

A few updates back, I decided to put in an artificial limit on the max path lengths. Now that you mention it, I'll probably add it to the settings to be user-defined.

**Comment by jvlflame** [comment]
Added in [1.5.0]
