### ISSUE TITLE
uncensored required metadata failure

### ISSUE THREAD

**Issue by demiurge21** [jvlflame/Javinizer#47]
When using a custom ini (attached) for uncensored sorting, it is failing to identify the returned metadata. it looks like a successful query to javbus, but the ending shows maybe some of it was parsed incorrectly? see verbose output below:

PS C:\Users\User> Javinizer -Path d:\asian\sort3 -ImportSettings C:\Users\User\Documents\PowerShell\Modules\Javinizer\1.6.0\uncensored.ini -strict                                                                                         DEBUG: [2020-06-14T14:10:46][Javinizer] R18: [False]; R18Zh: [False] Dmm: [False]; Javlibrary: [False]; JavlibraryZh: [False]; JavlibraryJa: [False]; Javbus: [True]; JavbusJa: [False]; Jav321: [False]
DEBUG: [2020-06-14T14:10:46][Javinizer] Attempting to read file(s) from path: [D:\asian\sort3]
DEBUG: [2020-06-14T14:10:46][Convert-JavTitle] Function started
DEBUG: [2020-06-14T14:10:46][Get-VideoFile] Function started
DEBUG: [2020-06-14T14:10:46][Convert-CommaDelimitedString] Begin string: [*-trailer.*,*-5.*], End string [*-trailer.* *-5.*]
DEBUG: [2020-06-14T14:10:46][Convert-CommaDelimitedString] Begin string: [asf,avi,flv,m4v,mkv,mp4,mov,rmvb], End string [asf avi flv m4v mkv mp4 mov rmvb]
DEBUG: [2020-06-14T14:10:46][Get-VideoFile] Function ended
DEBUG: [2020-06-14T14:10:46][Convert-JavTitle] Match 11
DEBUG: [2020-06-14T14:10:46][Convert-JavTitle] Function ended
DEBUG: [2020-06-14T14:10:46][Javinizer] Detected path: [D:\asian\sort3] as directory and destinationpath: [D:\asian\sort3] as directory
[2020-06-14T14:10:46][Javinizer] Sort path: [D:\asian\sort3]
[2020-06-14T14:10:46][Javinizer] Destination path: [D:\asian\sort3]
[2020-06-14T14:10:46][Javinizer] Included file ext: [asf,avi,flv,m4v,mkv,mp4,mov,rmvb]
[2020-06-14T14:10:46][Javinizer] Excluded file strings: [*-trailer.*,*-5.*]
[2020-06-14T14:10:46][Javinizer] (1 of 1) Sorting [HEYZO-2189.mp4]
DEBUG: [2020-06-14T14:10:46][Get-AggregatedDataObject] Function started
DEBUG: [2020-06-14T14:10:46][Get-MetadataPriority] Priority type loaded: [actress]; Priority setting: [r18 javlibrary]
DEBUG: [2020-06-14T14:10:46][Get-MetadataPriority] Priority type loaded: [actressthumburl]; Priority setting: [r18]
DEBUG: [2020-06-14T14:10:46][Get-MetadataPriority] Priority type loaded: [alternatetitle]; Priority setting: [dmm]
DEBUG: [2020-06-14T14:10:46][Get-MetadataPriority] Priority type loaded: [coverurl]; Priority setting: [r18 dmm javlibrary]
DEBUG: [2020-06-14T14:10:46][Get-MetadataPriority] Priority type loaded: [description]; Priority setting: [dmm]
DEBUG: [2020-06-14T14:10:46][Get-MetadataPriority] Priority type loaded: [director]; Priority setting: [r18 javlibrary]
DEBUG: [2020-06-14T14:10:46][Get-MetadataPriority] Priority type loaded: [genre]; Priority setting: [r18 javlibrary]
DEBUG: [2020-06-14T14:10:46][Get-MetadataPriority] Priority type loaded: [id]; Priority setting: [r18 javlibrary]
DEBUG: [2020-06-14T14:10:46][Get-MetadataPriority] Priority type loaded: [label]; Priority setting: [r18 javlibrary]
DEBUG: [2020-06-14T14:10:46][Get-MetadataPriority] Priority type loaded: [runtime]; Priority setting: [r18 javlibrary dmm]
DEBUG: [2020-06-14T14:10:46][Get-MetadataPriority] Priority type loaded: [maker]; Priority setting: [r18 javlibrary]
DEBUG: [2020-06-14T14:10:46][Get-MetadataPriority] Priority type loaded: [rating]; Priority setting: [dmm]
DEBUG: [2020-06-14T14:10:46][Get-MetadataPriority] Priority type loaded: [ratingcount]; Priority setting: [dmm]
DEBUG: [2020-06-14T14:10:46][Get-MetadataPriority] Priority type loaded: [releasedate]; Priority setting: [r18 javlibrary dmm]
DEBUG: [2020-06-14T14:10:46][Get-MetadataPriority] Priority type loaded: [releaseyear]; Priority setting: [r18 javlibrary dmm]
DEBUG: [2020-06-14T14:10:46][Get-MetadataPriority] Priority type loaded: [series]; Priority setting: [r18]
DEBUG: [2020-06-14T14:10:46][Get-MetadataPriority] Priority type loaded: [screenshoturl]; Priority setting: [r18 dmm]
DEBUG: [2020-06-14T14:10:46][Get-MetadataPriority] Priority type loaded: [title]; Priority setting: [r18 javlibrary]
DEBUG: [2020-06-14T14:10:46][Get-MetadataPriority] Priority type loaded: [trailerurl]; Priority setting: [r18]
DEBUG: [2020-06-14T14:10:46][Get-AggregatedDataObject] Type: [FileDetails]
DEBUG: [2020-06-14T14:10:46][Get-JavbusDataObject] Function started
DEBUG: [2020-06-14T14:10:46][Get-JavbusUrl] Function started
DEBUG: [2020-06-14T14:10:46][Get-JavbusUrl] Performing [GET] on Uri [https://www.javbus.com/search/HEYZO-2189&type=0&parent=uc]
DEBUG: [2020-06-14T14:10:46][Get-JavbusUrl] Searching [1] of [1] results for [HEYZO-2189]
DEBUG: [2020-06-14T14:10:46][Get-JavbusUrl] Performing [GET] on Uri [https://www.javbus.com/HEYZO-2189]
DEBUG: [2020-06-14T14:10:46][Get-JavbusDataObject] Performing [GET] on Uri [https://www.javbus.com/en/HEYZO-2189]
DEBUG: [2020-06-14T14:10:46][Get-JavbusDataObject] JavBus data object:
DEBUG:
Source          : javbus
Url             : https://www.javbus.com/en/HEYZO-2189
Id              : HEYZO-2189
Title           : Sex Heaven -Tall Girl With Hot Legs Gets Multiple Orgasm-
Date            : 2020-02-08
Year            : 2020
Runtime         : 64
Director        :
Maker           : HEYZO
Label           :
Series          : Sex Heaven
Rating          :
Actress         : 日向るな
ActressThumbUrl : https://images.javbus.com/actress/nowprinting.gif
Genre           : {ギャル, shaved, AV女優, Creampie…}
CoverUrl        : https://images.javbus.com/cover/18xd_b.jpg
ScreenshotUrl   : {https://images.javbus.com/bigsample/18xd_b_1.jpg, https://images.javbus.com/bigsample/18xd_b_2.jpg, https://images.javbus.com/bigsample/18xd_b_3.jpg, https://images.javbus.com/bigsample/18xd_b_4.jpg…}

DEBUG: [2020-06-14T14:10:46][Get-JavbusDataObject] Function ended
DEBUG: [2020-06-14T14:10:46][Convert-CommaDelimitedString] Begin string: [Featured Actress,Hi-Def], End string [Featured Actress Hi-Def]
DEBUG: [2020-06-14T14:10:46][Get-AggregatedDataObject] Ignored genres: [Featured Actress Hi-Def]
DEBUG: [2020-06-14T14:10:46][Convert-CommaDelimitedString] Begin string: [Featured Actress,Hi-Def], End string [Featured Actress Hi-Def]
DEBUG: [2020-06-14T14:10:46][Get-AggregatedDataObject] Ignored genres: [Featured Actress Hi-Def]
DEBUG: [2020-06-14T14:10:46][Get-NewFileDirName] Function started
DEBUG: [2020-06-14T14:10:46][Get-NewFileDirName] Function ended
DEBUG:
Search               : HEYZO-2189
Id                   :
Title                :
AlternateTitle       :
Description          :
ReleaseDate          :
ReleaseYear          :
Runtime              :
Director             :
Maker                :
Label                :
Series               :
Rating               :
RatingCount          :
Actress              : {}
Genre                :
ActressThumbUrl      :
CoverUrl             :
ScreenshotUrl        :
TrailerUrl           :
DisplayName          : []
FolderName           :
ScreenshotFolderName : extrafanart
ScreenshotImgName    : fanart
ActorImgFolderName   : .actors
FileName             :
PosterName           : folder
ThumbnailName        : fanart
TrailerName          : -trailer
NfoName              :
OriginalFileName     : HEYZO-2189.mp4
OriginalBaseName     : HEYZO-2189
OriginalDirectory    : D:\asian\sort3
OriginalFullName     : D:\asian\sort3\HEYZO-2189.mp4
PartNumber           :

DEBUG: [2020-06-14T14:10:46][Get-AggregatedDataObject] Function ended
DEBUG: [2020-06-14T14:10:46][Set-JavMovie] Function started
DEBUG: [2020-06-14T14:10:46][Set-JavMovie] Crop path: [C:\Users\User\Documents\PowerShell\Modules\Javinizer\1.6.0\crop.py]
DEBUG: [2020-06-14T14:10:46][Set-JavMovie] Folder path: [D:\asian\sort3\]
DEBUG: [2020-06-14T14:10:46][Set-JavMovie] Nfo path: [D:\asian\sort3\.nfo]
DEBUG: [2020-06-14T14:10:46][Set-JavMovie] Cover path: [D:\asian\sort3\fanart.jpg]
DEBUG: [2020-06-14T14:10:46][Set-JavMovie] Poster path: [D:\asian\sort3\folder.jpg]
DEBUG: [2020-06-14T14:10:46][Set-JavMovie] Screenshot path: [D:\asian\sort3\extrafanart]
DEBUG: [2020-06-14T14:10:46][Set-JavMovie] Trailer path: [D:\asian\sort3\-trailer.mp4]
DEBUG: [2020-06-14T14:10:46][Test-RequiredMetadata] Function started
DEBUG: [2020-06-14T14:10:46][Convert-CommaDelimitedString] Begin string: [coverurl,genre,id,maker,title,releasedate,releaseyear], End string [coverurl genre id maker title releasedate releaseyear]
WARNING: [2020-06-14T14:10:46][Test-RequiredMetadata] Skipped: [HEYZO-2189.mp4] 7 null required fields: [coverurl, genre, id, maker, title, releasedate, releaseyear]

[uncensored.ini.txt](https://github.com/jvlflame/Javinizer/files/4776990/uncensored.ini.txt)

**Comment by jvlflame** [comment]
You'll need to add the scraper you're using into your priority settings under `[Metadata]`.

```
[Main]
scrape-javbus=True
scrape-jav321=True

required-metadata-fields=coverurl,genre,id,maker,title,releasedate,releaseyear
actress-priority=javbus,jav321
actressthumburl-priority=javbus,jav321
alternatetitle-priority=javbus,jav321
coverurl-priority=javbus,jav321
description-priority=javbus,jav321
director-priority=javbus,jav321
genre-priority=javbus,jav321
id-priority=javbus,jav321
label-priority=javbus,jav321
maker-priority=javbus,jav321
rating-priority=javbus,jav321
ratingcount-priority=javbus,jav321
releasedate-priority=javbus,jav321
releaseyear-priority=javbus,jav321
runtime-priority=javbus,jav321
series-priority=javbus,jav321
screenshoturl-priority=javbus,jav321
title-priority=javbus,jav321
trailerurl-priority=javbus,jav321
```

These scrapers don't necessarily have all the fields, but if you're using the separate settings.ini file it should be fine to keep it as this.
