### ISSUE TITLE
nfo not being created - uncensored

### ISSUE THREAD

**Issue by demiurge21** [jvlflame/Javinizer#49]
RE: https://github.com/jvlflame/Javinizer/issues/47#issue-638402199
after adding javbus and jav321 into metadata priority settings, it seems to identify correctly, but does not create an nfo, cover, or poster despite it being scraped correctly. It seems to only sort the .mp4 file into a new folder. 
ini file is the same from https://github.com/jvlflame/Javinizer/issues/47#issue-638402199 except corrected metadata priority settings

PS C:\Users\User> Javinizer -Path d:\asian\sort3 -ImportSettings C:\Users\User\Documents\PowerShell\Modules\Javinizer\1.6.0\uncensored.ini -strict
DEBUG: [2020-06-15T17:02:08][Javinizer] R18: [False]; R18Zh: [False] Dmm: [False]; Javlibrary: [False]; JavlibraryZh: [False]; JavlibraryJa: [False]; Javbus: [True]; JavbusJa: [False]; Jav321: [True]
DEBUG: [2020-06-15T17:02:08][Javinizer] Attempting to read file(s) from path: [D:\asian\sort3]
DEBUG: [2020-06-15T17:02:08][Convert-JavTitle] Function started
DEBUG: [2020-06-15T17:02:08][Get-VideoFile] Function started
DEBUG: [2020-06-15T17:02:08][Convert-CommaDelimitedString] Begin string: [*-trailer.*,*-5.*], End string [*-trailer.* *-5.*]
DEBUG: [2020-06-15T17:02:08][Convert-CommaDelimitedString] Begin string: [asf,avi,flv,m4v,mkv,mp4,mov,rmvb], End string [asf avi flv m4v mkv mp4 mov rmvb]
DEBUG: [2020-06-15T17:02:08][Get-VideoFile] Function ended
DEBUG: [2020-06-15T17:02:08][Convert-JavTitle] Match 11
DEBUG: [2020-06-15T17:02:08][Convert-JavTitle] Function ended
DEBUG: [2020-06-15T17:02:08][Javinizer] Detected path: [D:\asian\sort3] as directory and destinationpath: [D:\asian\sort3] as directory
[2020-06-15T17:02:08][Javinizer] Sort path: [D:\asian\sort3]
[2020-06-15T17:02:08][Javinizer] Destination path: [D:\asian\sort3]
[2020-06-15T17:02:08][Javinizer] Included file ext: [asf,avi,flv,m4v,mkv,mp4,mov,rmvb]
[2020-06-15T17:02:08][Javinizer] Excluded file strings: [*-trailer.*,*-5.*]
[2020-06-15T17:02:08][Javinizer] (1 of 1) Sorting [HEYZO-2189.mp4]
DEBUG: [2020-06-15T17:02:08][Get-AggregatedDataObject] Function started
DEBUG: [2020-06-15T17:02:08][Get-MetadataPriority] Priority type loaded: [actress]; Priority setting: [javbus jav321]
DEBUG: [2020-06-15T17:02:08][Get-MetadataPriority] Priority type loaded: [actressthumburl]; Priority setting: [javbus jav321]
DEBUG: [2020-06-15T17:02:08][Get-MetadataPriority] Priority type loaded: [alternatetitle]; Priority setting: [javbus jav321]
DEBUG: [2020-06-15T17:02:08][Get-MetadataPriority] Priority type loaded: [coverurl]; Priority setting: [javbus jav321]
DEBUG: [2020-06-15T17:02:08][Get-MetadataPriority] Priority type loaded: [description]; Priority setting: [javbus jav321]
DEBUG: [2020-06-15T17:02:08][Get-MetadataPriority] Priority type loaded: [director]; Priority setting: [javbus jav321]
DEBUG: [2020-06-15T17:02:08][Get-MetadataPriority] Priority type loaded: [genre]; Priority setting: [javbus jav321]
DEBUG: [2020-06-15T17:02:08][Get-MetadataPriority] Priority type loaded: [id]; Priority setting: [javbus jav321]
DEBUG: [2020-06-15T17:02:08][Get-MetadataPriority] Priority type loaded: [label]; Priority setting: [javbus jav321]
DEBUG: [2020-06-15T17:02:08][Get-MetadataPriority] Priority type loaded: [runtime]; Priority setting: [javbus jav321]
DEBUG: [2020-06-15T17:02:08][Get-MetadataPriority] Priority type loaded: [maker]; Priority setting: [javbus jav321]
DEBUG: [2020-06-15T17:02:08][Get-MetadataPriority] Priority type loaded: [rating]; Priority setting: [javbus jav321]
DEBUG: [2020-06-15T17:02:08][Get-MetadataPriority] Priority type loaded: [ratingcount]; Priority setting: [javbus jav321]
DEBUG: [2020-06-15T17:02:08][Get-MetadataPriority] Priority type loaded: [releasedate]; Priority setting: [javbus jav321]
DEBUG: [2020-06-15T17:02:08][Get-MetadataPriority] Priority type loaded: [releaseyear]; Priority setting: [javbus jav321]
DEBUG: [2020-06-15T17:02:08][Get-MetadataPriority] Priority type loaded: [series]; Priority setting: [javbus jav321]
DEBUG: [2020-06-15T17:02:08][Get-MetadataPriority] Priority type loaded: [screenshoturl]; Priority setting: [javbus jav321]
DEBUG: [2020-06-15T17:02:08][Get-MetadataPriority] Priority type loaded: [title]; Priority setting: [javbus jav321]
DEBUG: [2020-06-15T17:02:08][Get-MetadataPriority] Priority type loaded: [trailerurl]; Priority setting: [javbus jav321]
DEBUG: [2020-06-15T17:02:08][Get-AggregatedDataObject] Type: [FileDetails]
DEBUG: [2020-06-15T17:02:08][Get-JavbusDataObject] Function started
DEBUG: [2020-06-15T17:02:08][Get-JavbusUrl] Function started
DEBUG: [2020-06-15T17:02:08][Get-JavbusUrl] Performing [GET] on Uri [https://www.javbus.com/search/HEYZO-2189&type=0&parent=uc]
DEBUG: [2020-06-15T17:02:08][Get-JavbusUrl] Searching [1] of [1] results for [HEYZO-2189]
DEBUG: [2020-06-15T17:02:08][Get-JavbusUrl] Performing [GET] on Uri [https://www.javbus.com/HEYZO-2189]
DEBUG: [2020-06-15T17:02:08][Get-JavbusDataObject] Performing [GET] on Uri [https://www.javbus.com/en/HEYZO-2189]
DEBUG: [2020-06-15T17:02:09][Get-JavbusDataObject] JavBus data object:
DEBUG:
Source          : javbus
Url             : https://www.javbus.com/en/HEYZO-2189
Id              : HEYZO-2189
Title           : Sex Heaven -Tall Girl With Hot Legs Gets Multiple Orgasm-
Date            : 2020-02-08
Year            : 2020
Runtime         : 64
Director        :
Maker           : HEYZO
Label           :
Series          : Sex Heaven
Rating          :
Actress         : 日向るな
ActressThumbUrl : https://images.javbus.com/actress/nowprinting.gif
Genre           : {ギャル, shaved, AV女優, Creampie…}
CoverUrl        : https://images.javbus.com/cover/18xd_b.jpg
ScreenshotUrl   : {https://images.javbus.com/bigsample/18xd_b_1.jpg, https://images.javbus.com/bigsample/18xd_b_2.jpg, https://images.javbus.com/bigsample/18xd_b_3.jpg, https://images.javbus.com/bigsample/18xd_b_4.jpg…}

DEBUG: [2020-06-15T17:02:09][Get-JavbusDataObject] Function ended
DEBUG: [2020-06-15T17:02:09][Get-Jav321DataObject] Function started
DEBUG: [2020-06-15T17:02:09][Get-Jav321Url] Function started
DEBUG: [2020-06-15T17:02:09][Get-Jav321Url] Performing [GET] on Uri [https://jp.jav321.com/search]
DEBUG: [2020-06-15T17:02:09][Get-Jav321Url] Searching [1] of [1] results for [HEYZO-2189]
DEBUG: [2020-06-15T17:02:09][Get-Jav321Url] Performing [GET] on Uri [https://jp.jav321.com/video/heyzo2189]
DEBUG: [2020-06-15T17:02:10][Get-Jav321DataObject] Performing [GET] on Uri [https://jp.jav321.com/video/heyzo2189]
DEBUG: [2020-06-15T17:02:10][Get-Jav321DataObject] jav321 data object:
DEBUG:
Source          : jav321
Url             : https://jp.jav321.com/video/heyzo2189
Id              : HEYZO-2189
Title           :
Date            : 0000-00-00
Year            : 0000
Runtime         : 64
Maker           :
Actress         :
ActressThumbUrl :
Genre           :
CoverUrl        :
ScreenshotUrl   :

DEBUG: [2020-06-15T17:02:10][Get-Jav321DataObject] Function ended
DEBUG: [2020-06-15T17:02:10][Get-AggregatedDataObject] Ignored genres: []
DEBUG: [2020-06-15T17:02:10][Get-NewFileDirName] Function started
DEBUG: [2020-06-15T17:02:11][Get-NewFileDirName] Function ended
DEBUG:
Search               : HEYZO-2189
Id                   : HEYZO-2189
Title                : Sex Heaven -Tall Girl With Hot Legs Gets Multiple Orgasm-
AlternateTitle       : Sex Heaven -Tall Girl With Hot Legs Gets Multiple Orgasm-
Description          :
ReleaseDate          : 2020-02-08
ReleaseYear          : 2020
Runtime              : 64
Director             :
Maker                : HEYZO
Label                :
Series               : Sex Heaven
Rating               :
RatingCount          :
Actress              : {日向るな}
Genre                : {ギャル, shaved, AV女優, Creampie…}
ActressThumbUrl      : https://images.javbus.com/actress/nowprinting.gif
CoverUrl             : https://images.javbus.com/cover/18xd_b.jpg
ScreenshotUrl        : {https://images.javbus.com/bigsample/18xd_b_1.jpg, https://images.javbus.com/bigsample/18xd_b_2.jpg, https://images.javbus.com/bigsample/18xd_b_3.jpg, https://images.javbus.com/bigsample/18xd_b_4.jpg…}
TrailerUrl           :
DisplayName          : [HEYZO-2189] Sex Heaven -Tall Girl With Hot Legs Gets Multiple Orgasm-
FolderName           : HEYZO-2189
ScreenshotFolderName : extrafanart
ScreenshotImgName    : fanart
ActorImgFolderName   : .actors
FileName             : HEYZO-2189
PosterName           : folder
ThumbnailName        : fanart
TrailerName          : HEYZO-2189-trailer
NfoName              : HEYZO-2189
OriginalFileName     : HEYZO-2189.mp4
OriginalBaseName     : HEYZO-2189
OriginalDirectory    : D:\asian\sort3
OriginalFullName     : D:\asian\sort3\HEYZO-2189.mp4
PartNumber           :

DEBUG: [2020-06-15T17:02:11][Get-AggregatedDataObject] Function ended
DEBUG: [2020-06-15T17:02:11][Set-JavMovie] Function started
DEBUG: [2020-06-15T17:02:11][Set-JavMovie] Crop path: [C:\Users\User\Documents\PowerShell\Modules\Javinizer\1.6.0\crop.py]
DEBUG: [2020-06-15T17:02:11][Set-JavMovie] Folder path: [D:\asian\sort3\HEYZO-2189]
DEBUG: [2020-06-15T17:02:11][Set-JavMovie] Nfo path: [D:\asian\sort3\HEYZO-2189\HEYZO-2189.nfo]
DEBUG: [2020-06-15T17:02:11][Set-JavMovie] Cover path: [D:\asian\sort3\HEYZO-2189\fanart.jpg]
DEBUG: [2020-06-15T17:02:11][Set-JavMovie] Poster path: [D:\asian\sort3\HEYZO-2189\folder.jpg]
DEBUG: [2020-06-15T17:02:11][Set-JavMovie] Screenshot path: [D:\asian\sort3\HEYZO-2189\extrafanart]
DEBUG: [2020-06-15T17:02:11][Set-JavMovie] Trailer path: [D:\asian\sort3\HEYZO-2189\HEYZO-2189-trailer.mp4]
DEBUG: [2020-06-15T17:02:11][Test-RequiredMetadata] Function started
DEBUG: [2020-06-15T17:02:11][Convert-CommaDelimitedString] Begin string: [coverurl,genre,id,maker,title,releasedate,releaseyear], End string [coverurl genre id maker title releasedate releaseyear]
DEBUG: [2020-06-15T17:02:11][Test-RequiredMetadata] Function ended
DEBUG: [2020-06-15T17:02:11][Set-JavMovie] Function ended

**Comment by jvlflame** [comment]
I can't reproduce the issue with your settings on my environment.
From your debug logs, it seems to be missing the nfo creation function `Get-MetadataNfo`. 

If you check your settings, is `create-nfo=True` set?

e.g. here's my logs showing that the NFO string is being output at the end
```
PS C:\Users\jvlflame\Downloads\test> Javinizer -Path . -Strict -ImportSettings .\uncensored.ini
DEBUG: [2020-06-15T14:26:10][Javinizer] R18: [False]; R18Zh: [False] Dmm: [False]; Javlibrary: [False]; JavlibraryZh: [False]; JavlibraryJa: [False]; Javbus: [True]; JavbusJa: [False]; Jav321: [True]

<redacted for brevity>

DEBUG: [2020-06-15T14:26:11][Test-RequiredMetadata] Function started
DEBUG: [2020-06-15T14:26:11][Convert-CommaDelimitedString] Begin string: [coverurl,genre,id,maker,title,releasedate,releaseyear], End string [coverurl genre id maker title releasedate releaseyear]
DEBUG: [2020-06-15T14:26:11][Test-RequiredMetadata] Function ended
DEBUG: [2020-06-15T14:26:11][Get-MetadataNfo] NFO String:
        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<movie>
    <title>[HEYZO-2189] Sex Heaven -Tall Girl With Hot Legs Gets Multiple Orgasm-</title>
    <originaltitle>Sex Heaven -Tall Girl With Hot Legs Gets Multiple Orgasm-</originaltitle>
    <id>HEYZO-2189</id>
    <releasedate>2020-02-08</releasedate>
    <year>2020</year>
    <director></director>
    <studio>HEYZO</studio>
    <rating></rating>
    <votes></votes>
    <plot></plot>
    <runtime>64</runtime>
    <trailer></trailer>
    <mpaa>XXX</mpaa>
    <set>Sex Heaven</set>
    <tag>Sex Heaven</tag>
    <genre>ギャル</genre>
    <genre>shaved</genre>
    <genre>AV女優</genre>
    <genre>Creampie</genre>
    <genre>騎乗位</genre>
    <genre>バック</genre>
    <genre>Shiofuki</genre>
    <genre>69</genre>
    <genre>指マン</genre>
    <genre>Office Lady</genre>
    <genre>Lust woman</genre>
    <actor>
        <name>日向るな</name>
        <thumb>https://pics.r18.com/mono/actjpgs/hinata_runa.jpg</thumb>
        <role>Actress</role>
    </actor>
</movie>
DEBUG: [2020-06-15T14:26:12][Set-JavMovie] Function ended

**Comment by demiurge21** [comment]
i found the issue, i had a duplicate [Metadata] section header in the ini file. I removed the dupe and it's working now, thanks!
