### ISSUE TITLE
Don't truncate genres and etc in -Find?

### ISSUE THREAD

**Issue by luckworr** [jvlflame/Javinizer#55]
When using `-Find` command, I would like to see all the information in the output with nothing is being truncated to `...`, especially for Genres and ScreenshotUrl. 

I tried `-Verbose` switch it did not do anything.

How to achieve this?

**Comment by jvlflame** [comment]
Can you give an example of which movie is giving you `...` outputs? Also the exact command you're running if possible.

None of the fields should be truncating, but there may be an error somewhere that I've missed.

**Comment by luckworr** [comment]
Example: ` Javinizer -Find IPX-497 -Aggregated`

```
Search               : IPX-497
Id                   : IPX-497
AjaxId               : 440755
JavlibraryUrl        : http://www.javlibrary.com/en/?v=javme2yozu
Title                : BEAUTY VENUS VII
AlternateTitle       :
Description          :
ReleaseDate          : 2020-07-11
ReleaseYear          : 2020
Runtime              : 243
Director             : Usa-pyon.
Maker                : Idea Pocket
Label                : Dish
Series               : BEAUTY VENUS
Rating               :
RatingCount          :
Actress              : {Hatsukawa Minami, Sakamichi Miru, Kaede Karen}
Genre                : {Blow, Squirting, Slut, 4HR+…}
ActressThumbUrl      :
CoverUrl             : https://pics.r18.com/digital/video/ipx00497/ipx00497pl.jpg
ScreenshotUrl        : {https://pics.r18.com/digital/video/ipx00497/ipx00497jp-1.jpg, https://pics.r18.com/digital/video/ipx00497/ipx00497jp-2.jpg,
                       https://pics.r18.com/digital/video/ipx00497/ipx00497jp-3.jpg, https://pics.r18.com/digital/video/ipx00497/ipx00497jp-4.jpg…}
TrailerUrl           : {https://awscc3001.r18.com/litevideo/freepv/i/ipx/ipx00497/ipx00497_dmb_w.mp4}
DisplayName          : [IPX-497] BEAUTY VENUS VII
FolderName           : IPX-497 [Idea Pocket] - BEAUTY VENUS VII (2020)
ScreenshotFolderName : extrafanart
ScreenshotImgName    : fanart
ActorImgFolderName   : .actors
FileName             : IPX-497
PosterName           : folder
ThumbnailName        : fanart
TrailerName          : IPX-497-trailer
NfoName              : IPX-497
OriginalFileName     :
OriginalBaseName     :
OriginalDirectory    :
OriginalFullName     :
PartNumber           :
```

Notice the genre line is `Blow, Squirting, Slut, 4HR+…`
The full list should be `Blow, Squirting, Slut, 4HR+, Slender, Digital Mosaic`

<details> 
  <summary>settings.ini</summary> 
  <pre>
[Main]
scrape-r18=True
scrape-r18zh=False
scrape-dmm=False
scrape-javlibrary=True
scrape-javlibraryja=True
scrape-javlibraryzh=False
scrape-javbus=False
scrape-javbusja=False
scrape-jav321=False  

# Actress scrapers  
scrape-actress-en=True
scrape-actress-ja=True

[General]
# Maximum number of threads to sort with if parameter '-Multi' is applied (range 1-15)
multi-sort-throttle-limit=5
move-to-folder=True
rename-file=True
# Available tags for file/folder rename string
# <ID> <TITLE> <STUDIO> <YEAR> <RELEASEDATE> <RUNTIME> <ACTORS> <LABEL> <ORIGINALTITLE> <SET>
# I do not recommend changing the filename other than <ID> as you may have to manually rename files if you need to re-sort them at a later date
rename-file-string="<ID>"
rename-folder-string="<ID> [<STUDIO>] - <TITLE> (<YEAR>)"
cms-displayname-string="[<ID>] <TITLE>"
actors-name-delimiter=", "
poster-file-string="folder"
thumbnail-file-string="fanart"
trailer-file-string="<ID>-trailer"
# nfo-file-string will only apply if create-nfo-per-file=False
nfo-file-string="<ID>"
screenshot-folder-string="extrafanart"
screenshot-img-string="fanart"
actorimg-folder-string=".actors"
# Max-title-length will limit the length of your <TITLE> string
max-title-length=100
# Max-path-length will limit the sorting of a file if its full path is greater than this number
max-path-length=255
# This option will allow Javinizer to ignore video files below a certain size (in MB)
minimum-filesize-to-sort=0
included-file-extensions=asf,avi,flv,m4v,mkv,mp4,mov,rmvb,dat
excluded-file-strings=*-trailer.*,*-5.*
# Allows you to use a regex string to match files if the default Javinizer matcher doesn't work
# (e.g. In regex ([a-zA-Z|tT28]+-\d+z{0,1}Z{0,1}e{0,1}E{0,1})(?:-pt){0,1}(\d{1,2})? , "[ABP-123] Title text-pt3.mp4", match 1 is "ABP-123, match 2 is "3")
regex-match=False
# The match value of your movie ID (e.g. "ID-112")
regex-id-match=1
# The match value of your movie part number (e.g. "2")
regex-pt-match=2
regex=([a-zA-Z|tT28]+-\d+z{0,1}Z{0,1}e{0,1}E{0,1})(?:-pt){0,1}(\d{1,2})?

[Metadata]
# General metadata options
# If you use Emby/Jellyfin, create-nfo-per-file is required (nfo is required to have the same filename)
create-nfo=True
create-nfo-per-file=True
download-thumb-img=True
# Download-poster-img requires download-thumb-img to be true
download-poster-img=True
download-screenshot-img=False
download-trailer-vid=False
download-actress-img=False
translate-description=True
# View language codes: https://developers.google.com/admin-sdk/directory/v1/languages
translate-description-language=en
# Use this if you want R18 series names to be set as clickable tag in Emby. If you primarily use Plex, you can set this to false.
add-series-as-tag=False
# True = FirstName LastName / False = LastName FirstName
first-last-name-order=False
# This option will convert actress names matching 'Alias' in r18-thumbs.csv to their original full name
convert-alias-to-originalname=True
# This will convert all JavLibrary genres to their R18 counterparts to keep a consistent genre schema. If you want to use JAVLibrary genres, set this to false.
normalize-genres=False
# List of genres to ignore in comma separated format (no spaces)
ignored-genres="Featured Actress,Hi-Def,Blu-ray"

# Metadata scraping priorities
# Javinizer will fail the sort on a movie if any fields listed in required-metadata-fields is null
required-metadata-fields=coverurl,genre,id,maker,title,releasedate,releaseyear
actress-priority=javlibrary,r18
actressthumburl-priority=r18
alternatetitle-priority=dmm
coverurl-priority=r18,dmm,javlibrary
description-priority=dmm
director-priority=r18,javlibrary
genre-priority=javlibrary,r18
id-priority=r18,javlibrary
label-priority=r18,javlibrary
maker-priority=r18,javlibrary
rating-priority=dmm
ratingcount-priority=dmm
releasedate-priority=r18,javlibrary,dmm
releaseyear-priority=r18,javlibrary,dmm
runtime-priority=r18,javlibrary,dmm
series-priority=r18
screenshoturl-priority=r18,dmm
title-priority=r18,javlibrary
trailerurl-priority=r18

[Locations]
# These locations will only be used if you are running Javinizer with the -Apply parameter
input-path="C:\Downloads\Unsorted"
output-path="C:\Downloads\Sorted"

[Emby/Jellyfin]
# You can create an Emby/Jellyfin API key under Dashboard -> Advanced -> Security
server-url=192.168.0.1:8096
server-api-key=

[JavLibrary]
set-owned=False
username=
session-cookie=
request-timeout-sec=90

[Other]
# Log path will default to the javinizer.log file inside your module directory
log-path=
check-updates=True
verbose-shell-output=True
debug-shell-output=False

  </pre> 
</details> 
Did not change much besides Metadata scraping priorities

I am using `PowerShell 7.0.2`

**Comment by jvlflame** [comment]
Ah, got it. [That would actually be a  PowerShell console-specific issue with truncating objects.](https://greiginsydney.com/viewing-truncated-powershell-output/)

If you set in your console:
```
$FormatEnumerationLimit = -1
```
then the output shouldn't be truncated. You'll need to set this value every time you re-open your console unless you add that command to your PowerShell profile. You could also assign the Javinizer command to a variable to reference certain fields.

![image](https://user-images.githubusercontent.com/17932235/87333662-495a3600-c4f2-11ea-9223-72676ba3c550.png)

**Comment by luckworr** [comment]
Ahh ok it worked. Thank you.
