### ISSUE TITLE
Actor/genre lists have maximum of 4 objects

### ISSUE THREAD

**Issue by AceGene** [jvlflame/Javinizer#58]
On each of the the three default sources ( javlibrary, dmm, javlibrary) there seems to be a limit on the number of actors/genres that can display. After 4 objects there is an appended '…' and no further displayed objects. If intended behavior, perhaps this behavior couldbe toggle-able via the settings.ini? If this will not be fixed, could a suggestion be made for where in the code to fix this locally?

Example command and output below
`Javinizer -Find XRW-806`

Source        : javlibrary
....
Actress       : {Hiiragi Mai, Yukino Akari, Harukawa Mari, KamiSaki Miyu…}
Genre         : {Transsexual, Futanari, 4HR+, Incest…}

Javinizer 1.7.3

**Comment by jvlflame** [comment]
That's a console specific issue. Check #55 for a workaround

**Comment by AceGene** [comment]
wow fail for me... thanks for the prompt reply. This is great work btw, I hope to contribute when I am able, I will close the issue
