### ISSUE TITLE
JAvbusja actress scrape

### ISSUE THREAD

**Issue by fidofido300** [jvlflame/Javinizer#59]
While Scraping IENF-085 with following settings

[Main]
scrape-r18=True
scrape-r18zh=False
scrape-dmm=True
scrape-javlibrary=False
scrape-javlibraryja=True
scrape-javlibraryzh=False
scrape-javbus=False
scrape-javbusja=False
scrape-jav321=True

actress-priority=javlibraryja,r18,jav321

Following lines are added to r18-thumbs.,cvs

"一条みお","System.Object[]","一条みお 藤井林檎 聖星姫花 河合亜依 掘ななか","System.Object[]","https://pics.r18.com/mono/actjpgs/fujii_ringo.jpg",""
"一条みお","System.Object[]","一条みお 藤井林檎 聖星姫花 河合亜依 掘ななか","System.Object[]","https://pics.r18.com/mono/actjpgs/kawana_ai2.jpg",""

## Expected Behavior
As you can see all the actress names are added in single line something broken with javlibraryja scraper

## Your Environment

* Module version used: 1.7.3
* Operating System and PowerShell version: Windows 10,   Powershell 7.0.2

**Comment by jvlflame** [comment]
Will fix in the next update

**Comment by jvlflame** [comment]
Fixed in 2.0.0
