### ISSUE TITLE
Misleading/improperly documented priority options

### ISSUE THREAD

**Issue by Still34** [jvlflame/Javinizer#61]
## Expected Behavior

1. Begin the scraping process
2. Results should contain JA results from `JavLibraryJa`, `JavBusJa`, etc.

## Current Behavior

1. Begin the scraping process
2. Results does not contain JA results from `JavLibraryJa`, `JavBusJa`, etc.

## Possible Solution

It seems that many alternative variables within `Get-AggregatedDataObject` are currently ignored, as detected by the PowerShell Script Analyzer in VSC (e.g. `$javbusJaData`, `$javlibraryJaData`)

Edit: Upon further investigation, it seems that we are expected to put `javLibraryJa` in the priority list instead of `javLibrary` (see `$var = Get-Variable -Name "$($priority)Data"`). Perhaps this could be made clearer in the configuration file?

**Comment by jvlflame** [comment]
Hey, thanks for raising the issue. Seems like you solved it yourself, and yeah I haven't gotten around to updating all documentation for the latest version.

I'm currently doing a pretty large rewrite to move into v2.0.0, so I will have documentation updated following that release.

**Comment by Still34** [comment]
I see, thanks! Looking forward to it. This PowerShell module has been of great help ever since JavMovieScraper's demise. Hope to see this project getting more love!

**Comment by jvlflame** [comment]
Version [2.0.0](https://github.com/jvlflame/Javinizer/releases) released with updated documentation in the README. Hopefully that is sufficient!
