### ISSUE TITLE
Feature Req: option to create folder.jpg and poster.jpg

### ISSUE THREAD

**Issue by zuko7177** [jvlflame/Javinizer#66]
Thanks for creating this project.  I just discovered it.
My plan is to use Javinizer to do initial sorting, and use JAVMovieScraper for manual edits.
JAVMovieScraper support creating both folder.jpg and poster.jpg.

To further interoperability, could you add this feature to Javinizer?
Perhaps support the following setting:
poster-file-string="`folder`","`<ID>-poster`"

Thanks again.

**Comment by jvlflame** [comment]
Both poster and thumbnail is supported in both v1.7.3 and the upcoming v2.0.0 release.
A dependency there is Python as well as the Pillow module listed in the [installation](https://github.com/jvlflame/Javinizer/blob/release/1.7.3/README.md#installation) instructions.

**Comment by zuko7177** [comment]
Let me clarify... the request is to generate poster as two files:  folder.jpg and poster.jpg.  
Both are same image. Just different names.

**Comment by jvlflame** [comment]
Ah got it.
That functionality can be added, but can you clarify for what purpose you would need both?

**Comment by zuko7177** [comment]
JAVMovieScraper uses poster.jpg.  while windows uses folder.jpg for thumbnail.

**Comment by jvlflame** [comment]
Thanks, I see what you mean now. Haven't used javmoviescraper for that purpose before so I didn't know about that functionality.
I'll add it in the next version.

**Comment by zuko7177** [comment]
Thank you!

**Comment by zuko7177** [comment]
I see this request has been implemented in alpha5. Looks good!
