### ISSUE TITLE
Bug: Write-Error ... Invoke-Parallel.ps1:539

### ISSUE THREAD

**Issue by zuko7177** [jvlflame/Javinizer#69]
Using 2.0alpha5.  Scraping APKH-140 yields following error

![image](https://user-images.githubusercontent.com/39366879/92337089-eb624e80-f05b-11ea-90c5-9d001caeb4a4.png)

The movie is still moved to the "sorted" folder, but nfo file is empty. All other files (fanart, poster, etc) are created OK.

When we hit an error or missing "sort.metadata.requiredfield" field, should Javinizer just leave the movie file in the "unsorted" folder rather than still move it out?

**Comment by jvlflame** [comment]
Can you post your settings and which movie you tried to sort that got this error? I believe I received this error once during testing but I thought I resolved it.

**Comment by zuko7177** [comment]
Attached is my jvSettings.json.  Movie file is APKH-140.mp4. 
To test, you can create an empty text file call APKH.140.mp4 and scrape it (I'm sure you already know this).
[jvSettings.zip](https://github.com/jvlflame/Javinizer/files/5180640/jvSettings.zip)

**Comment by jvlflame** [comment]
Thanks. I see what's going on now. When there's some weird characters from the translated description it's automatically switching it to an array. I'll put in a fix for this.

![image](https://user-images.githubusercontent.com/17932235/92342193-efe73100-f074-11ea-9a0a-3ae3eb557180.png)
