### ISSUE TITLE
Feature Req: add <year> tag to NFO

### ISSUE THREAD

**Issue by zuko7177** [jvlflame/Javinizer#70]
2.0 alpha5 is not generating year tag in NFO.
Could we add the year tag?  Perhaps parse the year from \<releasedate\> tag ?
Thanks.

**Comment by jvlflame** [comment]
It's been readded in [dev](https://github.com/jvlflame/Javinizer/commit/611363eeb9852bb0059c56b7a606dd7ba632b9dd).
