### ISSUE TITLE
Bug: bad character found in jvthumbs.csv

### ISSUE THREAD

**Issue by zuko7177** [jvlflame/Javinizer#73]
Backslash character found in actress name is causing double quote to be escaped. Remove backslash from fullname and lastname column.

https://github.com/jvlflame/Javinizer/blob/743c9351a6aafe9084592d4495f7b4f7a1750f06/src/Javinizer/jvthumbs.csv#L8038

Also, file name should be jvThumbs.csv to maintain naming consistency.

**Comment by jvlflame** [comment]
Interesting, seems like R18 itself is the one with the issue. I'll add a string replacement for all R18 actresses to remove any `\` backslash characters if they appear in the names.

https://www.r18.com/videos/vod/movies/list/id=9665/pagesize=60/price=all/sort=new/type=actress/page=1/
