### ISSUE TITLE
Feature Req: filter out "sale" genres

### ISSUE THREAD

**Issue by zuko7177** [jvlflame/Javinizer#75]
Could we have an option to filter out any genres with the word "sale" in it?  
Using "sort.metadata.genre.ignore" might not be feasible since the text for Sale genre changes.

Here's some current genre examples (from R18 I believe) that's coming through.

KRU-089 "SOD / Aurora Project ANNEX / BabyEntertainment SALE"
KRU-093 "Prestige / Hot Entertainment / SOD / Nagae Style / SMS SALE"
KRU-094 "Prestige / Hot Entertainment / SOD / Nagae Style / SMS SALE"
RBD-938 "Sale (limited time)"
HUNTA-832 "Triple Happy SALE 2"

**Comment by jvlflame** [comment]
I'll add wildcard support for the `sort.metadata.genre.ignore` setting.
