### ISSUE TITLE
Bug: Get-RunspaceData: ... Invoke-Parallel.ps1:539

### ISSUE THREAD

**Issue by zuko7177** [jvlflame/Javinizer#77]
Alpha7.  Movie file is HOKS-066.mp4

![image](https://user-images.githubusercontent.com/39366879/92629986-f8fa1d00-f283-11ea-8e7a-5df7be8da003.png)

I can confirm my settings are

    "location.thumbcsv": "D:\\Bin\\jvData\\jvThumbs.csv",
    "location.genrecsv": "D:\\Bin\\jvData\\jvGenres.csv",

Is it trying to update thumbnail data into jvGenres.csv?

**Comment by jvlflame** [comment]
Good catch. Seems like I mismatched the thumb csv path when it's not using the default.
