### ISSUE TITLE
Bug: INFO "Complete" message is missing [ID]

### ISSUE THREAD

**Issue by zuko7177** [jvlflame/Javinizer#78]
Using Alpha7.  
Perhaps this is more of a feature request.  The logging for completed is

[2020-09-09T13:06:34][INFO ] Completed [E:\unsorted\USBA-015.mp4] => [E:\\sorted\USBA-015\USBA-015.mp4]

Could we include the [ID] to keep logging consistent the other logging messages?
[2020-09-09T13:06:34][INFO ]  [USBA-015] Completed [E:\unsorted\USBA-015.mp4] => [E:\\sorted\USBA-015\USBA-015.mp4]

I'm using a program to tail the log and having it consistent helps with the parsing. 
Thanks.

Also sneak in to this ticket a spelling correction in README.md:
![image](https://user-images.githubusercontent.com/39366879/92657441-ae8b9700-f2a9-11ea-8d61-bf429b11dae1.png)
That one had me scratching my head for 5 mins.

**Comment by jvlflame** [comment]
I can make them consistent. I originally wanted to make the verbose logs shorter so they wouldn't clog up the console so I omitted them.
