### ISSUE TITLE
Bug: Get-RunspaceData ... Invoke-Parallel.ps1:539

### ISSUE THREAD

**Issue by zuko7177** [jvlflame/Javinizer#80]
Alpha8.  File is JUFE-197.mp4.
![image](https://user-images.githubusercontent.com/39366879/92759626-ccf2a080-f344-11ea-8949-9826d5754247.png)

I don't think it's a server issue since I'm able to browse thumbnail image on all three... r18, dmm, javlibrary

**Comment by jvlflame** [comment]
Is that a consistent error?

I'm not seeing any issues on my side.

If you run `Javinizer -Find jufe-197 -R18 -Javlibrary -Dmm -Aggregated`, do you get a bad url in the coverurl field?

**Comment by zuko7177** [comment]
When I run with `Javinizer -Find jufe-197 -R18 -Javlibrary -Dmm -Aggregated`, it comes back with aggregated data successfully.
When I run with just `Javinizer`, I get that error.
Attached is my settings.  
[jvSettings.zip](https://github.com/jvlflame/Javinizer/files/5203633/jvSettings.zip)
I compared my jvSettings with the default and don't see anything weird.

**Comment by jvlflame** [comment]
Ok, confirmed an issue on my side as well.

It actually seems to be occurring on all videos, not just `JUFE-197`. Interestingly though, if I change the method in which the file is downloaded over to `Invoke-Webrequest` rather than the `System.Net.Webclient` class, it works.
