### ISSUE TITLE
javinizer removes the actual video file when updating nfo file

### ISSUE THREAD

**Issue by damenootoko** [jvlflame/Javinizer#87]
## Expected Behavior
recreate nfo file

## Current Behavior
removes the video file

## Steps to Reproduce (for bugs)
(from inside sorted directory for a single video file) (e.g. F:\jav_sorted\SNIS-596)
execute `javinizer -Path . -MoveToFolder:$false`

## Your Environment
* Module version used: 2.0.0
* Operating System and PowerShell version: 7

this command only updates / get missing components (image, trailer, etc) on previous version. on 2.0.0 it removes the actual video file

**Comment by damenootoko** [comment]
it seems like to achieve the same result as previous version i need to use the -update command like so `javinizer -Path . -Update -Verbose` but I think it would be safer to check why the -MoveToFolder:$false is removing the file

**Comment by jvlflame** [comment]
2.0.0 works a bit differently with the DestinationPath now.

From release notes:

- Path will default to your current commandline location if -Path is not specified and setting location.input is blank
- DestinationPath will default to the sorted file's current directory if -DestinationPath is not specified and setting location.output is blank

It seems like you noticed the `-Update` parameter, but your file shouldn't be removed. It was most likely re-sorted to the destination path listed in your `location.output` setting. If you open your log file you should be able to see where your files went.
```
Javinizer -OpenLog
```

**Comment by damenootoko** [comment]
Sorry, turns out that windows file search is acting up a bit
the -MoveToFolder actually moved the file into inside the destination path but doesn't move it to it's own folder. the file is still there. thanks

**Comment by damenootoko** [comment]
oh, and also a bit of heads  up
windows defender somehow start blocking curl commands, which result in failing hit to r18.com and javlibrary.com
found out after actually trying to run curl manually on powershell and it throws windows antivirus blocked message
@jvlflame

**Comment by jvlflame** [comment]
Javinizer doesn't use any `curl` commands, so I don't think it should affect anything there.

I did a quick search and I couldn't find any info on curl being blocked by Windows Defender, but if you have any screenshots of the error or any other info that might be helpful.
