### ISSUE TITLE
Feature request: auto translate japanese text

### ISSUE THREAD

**Issue by org0ne** [jvlflame/Javinizer#89]
I have a collection of 1pondo, caribbeancom, etc movies and have much better success using Javinizer compared to JavMovieScraper, however the older entries in JavBus are only in Japanese.  

Would it be possible to optionally translate Titles, Genres and Actors?

Attached is an example of a JavBus scraped result that could use some translation magic
[010112_248-1pon-whole1_hd.txt](https://github.com/jvlflame/Javinizer/files/5248182/010112_248-1pon-whole1_hd.txt)

**Comment by jvlflame** [comment]
Title and Genres seem doable in addition to description, though actors get a bit tricky. You may end up with wildly inaccurate data for the names since a automated translator isn't going to know or select the correct pronunciation of the Japanese name in many instances.

**Comment by org0ne** [comment]
Thanks!  (Agreed actors would be tricky.)

Interesting suggestion about manually adding actors to the thumb csv.  How exactly does Javinizer use the csv?  
- Does it try to match the Japanese characters when that is the only data it finds and then look up an english name?
- Is it possible to manually add an actor and then re-scrape a movie to update the actor names?

Wondering how to fix the large number of movies I have w/ only Japanese names, or will adding manual entries just fix subsequent occurrences?

**Comment by jvlflame** [comment]
> Is it possible to manually add an actor and then re-scrape a movie to update the actor names?

The `-Update` parameter can be run on directories to update the nfo without moving already sorted files, so yes you could just rescrape the movies. Currently in 2.0.0, if it JapaneseName for the actress pulled from the scraper has a match in the thumb csv, then the english name will be replaced with the entry. I wrote a bit about how the thumb csv works in the [README](https://github.com/jvlflame/Javinizer#actress-thumb-csv).

I have a few changes in the actress matching workflow in my dev branch for 2.0.1 that will follow this:
![image](https://user-images.githubusercontent.com/17932235/93661264-4bb5a080-fa0b-11ea-8421-6bd062bc4ffb.png)

**Comment by org0ne** [comment]
This will be very useful.  Am currently digging into previous databases and seeing what I can export into a new local thumbs csv file to rename these japanese only named actresses.

Thanks for the flowchart!  Looking forward to checking this out in action.

**Comment by jvlflame** [comment]
Added support for translation for additional scraper fields, configurable via the settings JSON.

```
# Example Settings

    "sort.metadata.nfo.translate": 1,
    "sort.metadata.nfo.translate.field": ["description", "title", "genre"],
    "sort.metadata.nfo.translate.language": "en",
```

The full list of supported fields are as follows:
```
                $translatedObject = [PSCustomObject]@{
                    Title          = $null
                    AlternateTitle = $null
                    Description    = $null
                    Director       = $null
                    Series         = $null
                    Maker          = $null
                    Label          = $null
                    Genre          = $null
                }
```

I chose not to include Actor/Actress name translation due to the extended logic that would be needed for it.

**Comment by RockmanNeo** [comment]
> I have a collection of 1pondo, caribbeancom, etc movies and have much better success using Javinizer compared to JavMovieScraper, 

Sorry for reviving an old thread, but how do you even use Javinizer with 1pondo, caribbeancom, etc?

**Comment by jvlflame** [comment]
> > I have a collection of 1pondo, caribbeancom, etc movies and have much better success using Javinizer compared to JavMovieScraper,
> 
> Sorry for reviving an old thread, but how do you even use Javinizer with 1pondo, caribbeancom, etc?

You can enable the [AVentertainment](https://www.aventertainments.com/ppv/main.aspx?languageID=1&vodtypeid=1) scraper in the settings and add it to your metadata priorities.

```
Javinizer -Find 'DL1pon_022521_001' -Aventertainment

Source        : aventertainment
Url           : https://www.aventertainments.com/ppv/new_detail.aspx?ProID=55290&languageID=1&VODTypeID=1
Id            : DL1pon_022521_001
Title         : Browjob and SEX in the Futon : Airi Mikumo (FullHD) 2021) | Video On Demand
ReleaseDate   : 2021-02-25
ReleaseYear   : 2021
Runtime       : 61
Maker         : 1pondo
Actress       : @{LastName=Mikumo; FirstName=Airi; JapaneseName=美雲あい梨; ThumbUrl=}
Genre         : {All Sex, Beautiful Skin, Big Tits, Blowjob…}
CoverUrl      : https://imgs02.aventertainments.com//vodimages/gallery/large/1pon_022521_001/001.jpg
ScreenshotUrl : {https://imgs02.aventertainments.com//vodimages/screenshot/large/1pon_022521_001/001.jpg,
                https://imgs02.aventertainments.com//vodimages/screenshot/large/1pon_022521_001/002.jpg,
                https://imgs02.aventertainments.com//vodimages/screenshot/large/1pon_022521_001/002.jpg,
                https://imgs02.aventertainments.com//vodimages/screenshot/large/1pon_022521_001/003.jpg…}
```
