### ISSUE TITLE
Error while scraping

### ISSUE THREAD

**Issue by Yukkun** [jvlflame/Javinizer#97]
## Expected Behavior
Its supposed to scrape the files in the folder

## Current Behavior
Instead of scraping, it throws this error

```
Get-RunspaceData : Exception calling "EndInvoke" with "1" argument(s): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: [ABP-064] [Get-JVData] Error occured during scraper jobs: Cannot validate argument on parameter 'ThrottleLimit'. The 100 argument is greater than the maximum allowed range of 50. Supply an argument that is less than or equal to 50 and then try the command again."
At C:\Users\myste\Documents\PowerShell\Modules\Javinizer\2.0.1\Private\Invoke-Parallel.ps1:532 char:21
+                     Get-RunspaceData
+                     ~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Get-RunspaceData], MethodInvocationException
+ FullyQualifiedErrorId : ActionPreferenceStopException,Get-RunspaceData

```
## Steps to Reproduce (for bugs)
Run the script

## Your Environment
* Module version used: 2.0.1
* Operating System and PowerShell version: Windows 10, version 2004.  Powershell 6.2.4

Sidenote: With latest version PowerShell 7, it seems to be working

**Comment by jvlflame** [comment]
2.x.x versions require to be run on PowerShell 6 or PowerShell 7.

Throttlelimit needs to be within values 1-5 per the [settings docs](https://github.com/jvlflame/Javinizer#settings-information), not sure why that error message is saying 50.

**Comment by Yukkun** [comment]
I have the throttlelimit as default value of 3. For some reason that only happens in PowerShell 6. In PowerShell 7 its completely fine.. Maybe there is some changes in 7 that makes that work differently than in 6?

**Comment by jvlflame** [comment]
Thanks for that info, I figured out what's going on now.
PowerShell 6 seems to have some hard limits on a parameter that doesn't exist in PowerShell 7.
